# -*- coding: utf-8 -*-
"""cnyusd2019.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KI9GfUkfKGL8PQv016zknRCy0RljLwEQ
"""

from sklearn.preprocessing import MinMaxScaler
import numpy as np

def weekly_score(df):
  transfer=MinMaxScaler(feature_range=(0.1,0.5))
  df_1=np.array(df.iloc[:,2]).reshape(-1, 1)
  df_1=transfer.fit_transform(df_1)
  d=np.array(df.iloc[:,1])*df_1.reshape(1, -1)
  upper=int(sum(np.maximum(d,0).T))
  lower=int(sum(np.minimum(d,0).T))
  return upper,lower

bound=[]
raw_data=[]

import pandas as pd
#1
data = {
    "Topic": ["Internationalization of RMB", "US-China Trade War Costs", "Shift Away from US Dollar",
              "Australian Dollar Hits 10-Year Low", "USD as Global Reserve Currency",
              "British Pound vs. US Dollar", "China's Long Term Trade and Currency Goals",
              "USD/CAD Performance", "Impact of Bank Stocks on Exchange Rates", "New Law Impact on Daigou",
              "Stock Market Volatility", "Pound Exchange Rate", "Ringgit's Performance",
              "FTSE 100 Performance", "AUD/USD Performance", "Gold Price Performance"],
    "Sentiment Score": [75, -80, -70, -90, 60, 85, 70, -60, -55, 45, -75, 80, 50, -65, -85, -70],
    "Importance Score": [0.408, 0.489, 0.378, 0.612, 0.231, 0.284, 0.325, 0.165, 0.201, 0.141,
                         0.423, 0.212, 0.151, 0.587, 0.715, 0.371]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)



import pandas as pd
#2
data = {
    "Topic": ["Federal Reserve's Impact on Yuan", "Global Economic Outlook", "Shift Away from US Dollar",
              "China's Forex Reserves", "Capital Market Assumptions", "Impact of Oil Prices on Stock Market",
              "Emerging Markets Dominance by 2030", "Rupee Performance Against USD",
              "Impact of Global Risk Sentiment on USD", "Renminbi's Internationalization Efforts"],
    "Sentiment Score": [80, -75, -90, 70, 65, -85, 75, 60, 85, 70],
    "Importance Score": [0.324, 0.432, 0.519, 0.241, 0.193, 0.624, 0.274, 0.182, 0.243, 0.162]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#3
data = {
    "Topic": ["China's Economic Stimulus Measures", "Impact of U.S.-China Trade Talks",
              "Emerging Market Economies Growth Outlook", "Currency Exchange Rates: CHY vs. USD",
              "Impact of Ringgit's Performance", "U.S.-China Relations: Political Dynamics",
              "Trade War Effect on Exports and Imports", "U.S. Policy Shift towards China",
              "China's Influence in Global Affairs", "Impact of China's Military Strategy"],
    "Sentiment Score": [-70, 85, 70, 60, 75, -80, -85, -90, 70, -75],
    "Importance Score": [0.342, 0.471, 0.523, 0.294, 0.612, 0.382, 0.721, 0.483, 0.264, 0.143]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#4
data = {
    "Topic": ["Economic Activity in Latin America", "China's Economic Downturn",
              "Collaboration Between China and Japan", "Impact of US-China Trade War on China",
              "Currency Strength: JPY vs. USD", "Industrial Transformation in China",
              "Agricultural Collaboration Between US and China", "Basic Materials Breakout due to China's Plans",
              "Concerns Over Chinese Investments in Philippines", "Growth of Emerging Market Economies: China"],
    "Sentiment Score": [60, -70, 70, -85, 0, 50, 75, 80, -60, 70],
    "Importance Score": [0.612, 0.483, 0.264, 0.721, 0.294, 0.382, 0.143, 0.523, 0.342, 0.612]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#5
data = {
    "Topic": ["Renminbi Trading Volume Increase",
              "Impact of US Dollar Strength on iPhone Prices",
              "Tech Industry Challenges in China",
              "Travel Industry Trends in China",
              "Venezuelan Crisis and US Sanctions",
              "Foreign Investment in Chinese Stocks",
              "Latin American Market Performance Amid Trade Talks",
              "Global Economic Order Manifesto",
              "Euro vs. US Dollar Exchange Rate",
              "Impact of Federal Reserve Policy on Gold Prices"],
    "Sentiment Score": [70, -80, -50, 60, -90, 75, 55, -30, 50, 40],
    "Importance Score": [0.476, 0.345, 0.264, 0.189, 0.543, 0.732, 0.412, 0.156, 0.632, 0.298]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#6
data = {
    "Topic": ["Impact of US Tariffs on Chinese Exports",
              "US-China Trade Tensions and Profiting Countries",
              "US Debt and Exchange Rate Dynamics",
              "Challenges in Middle Eastern Economic Diversification",
              "Global Economic Standoffs and Central Bank Actions",
              "Foreign Reserves Management and Intervention",
              "Historical Pound to Dollar Exchange Rate Analysis",
              "Canadian Dollar Exchange Rate Trends",
              "Australian Dollar Exchange Rate Outlook",
              "Impact of Oil Prices on Currency Markets"],
    "Sentiment Score": [-90, 60, -70, -50, -30, 70, 50, 40, 80, -60],
    "Importance Score": [0.423, 0.189, 0.345, 0.264, 0.156, 0.732, 0.612, 0.298, 0.512, 0.432]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#7
data = {
    "Topic": ["US Tariffs and Their Impact on China",
              "FX Market Themes in 2019",
              "US-China Investment in Research and Development",
              "Zhou Xiaochuan's Contribution",
              "Future of the US Stock Market",
              "Australian Dollar and Financial Conditions",
              "Ant Financial's Expansion",
              "Exchange Rate Forecasts for USD/CNY",
              "Impact of China's Economic Growth on Trading Partners",
              "Myanmar's Currency Settlement Expansion"],
    "Sentiment Score": [-80, 40, -50, 70, -60, 60, 80, -30, -40, 50],
    "Importance Score": [0.432, 0.211, 0.343, 0.599, 0.265, 0.512, 0.643, 0.178, 0.288, 0.456]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#8
data = {
    "Topic": ["Kenyan Bank to Offer Trading in Chinese Yuan",
              "The Dominance of the US Dollar",
              "Maersk's Profits and Trade Conflict Warning",
              "China's Rise and Its Impact on Global Relations",
              "Uncertainty in US-China Trade Relations",
              "Global Economic Challenges and Best-Positioned Countries",
              "Asian-American Community in Detroit",
              "Argentina's President Macri's Re-election Outlook",
              "South China Sea Conflict and Its Costs",
              "North Korea's Economy Ahead of Hanoi Summit"],
    "Sentiment Score": [60, -70, -50, 30, -40, -30, 70, -50, -60, 50],
    "Importance Score": [0.421, 0.298, 0.343, 0.232, 0.288, 0.176, 0.543, 0.389, 0.321, 0.456]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#9
data = {
    "Topic": ["US-China Trade Talks Progress",
              "Impact of US Trade Policy on Chinese Economy",
              "Market Confidence in Chinese Economy",
              "Chinese Yuan Appreciation",
              "US-China Trade Disputes",
              "Chinese Economic Growth",
              "US-China Trade Negotiations",
              "US-China Trade War",
              "US-China Trade Relations",
              "US-China Trade Agreement Progress"],
    "Sentiment Score": [70, -50, 80, 60, -40, 90, 50, -60, 40, 30],
    "Importance Score": [0.700, 0.621, 0.567, 0.544, 0.511, 0.478, 0.456, 0.389, 0.355, 0.300]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#10
# Create the dataframe
data = {
    'Topic': [
        "US-China trade deal",
        "China's economic growth",
        "Global trade tensions",
        "US-China technology war",
        "Impact of US tariffs on China's economy",
        "China's response to US tariffs",
        "US-China relations",
        "Chinese investments in the US",
        "US-China trade negotiations progress",
        "China's economic slowdown"
    ],
    'Sentiment Score': [
        80.000,
        65.000,
        -50.000,
        -70.000,
        -60.000,
        -55.000,
        70.000,
        60.000,
        75.000,
        -75.000
    ],
    'Importance Score': [
        0.495,
        0.390,
        0.375,
        0.360,
        0.355,
        0.350,
        0.345,
        0.340,
        0.335,
        0.330
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#11
# Creating the data
data = {
    "Topic": [
        "US-China Trade Talks",
        "Impact of US-China Trade Deal on Economies",
        "China's Yuan Valuation",
        "Economic Consequences of US-China Trade War",
        "China's Slowdown and Growth Story",
        "Impact of US-China Trade War on Global Internet Grid",
        "China's Banking Revolution",
        "Chinese Yuan Overvaluation",
        "Impact of US-China Trade War on Global Security",
        "China's Current Account Deficit"
    ],
    "Sentiment Score": [
        -60,
        -50,
        -70,
        -65,
        -55,
        -40,
        50,
        -70,
        -45,
        -60
    ],
    "Importance Score": [
        0.297,
        0.291,
        0.272,
        0.263,
        0.258,
        0.250,
        0.231,
        0.221,
        0.210,
        0.205
    ]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#12
# Creating the data
data = {
    "Topic": [
        "Impact of US Dollar Strength on International Markets",
        "Impact of E-commerce Growth on Chinese Economy",
        "Indian Rupee Performance",
        "BMW's Profit Warning",
        "Titanium Dioxide Prices in Asia",
        "FedEx's Warning on Global Economic Slowdown",
        "Skoda's Efforts to Halt Profit Decline",
        "Outlook for Various Asian Currencies",
        "Impact of US-China Trade Deal on Global Economy",
        "Impact of Corporate Debt Pileups on Markets"
    ],
    "Sentiment Score": [
        -60,
        50,
        80,
        -70,
        30,
        -80,
        20,
        50,
        -70,
        -60
    ],
    "Importance Score": [
        0.324,
        0.296,
        0.283,
        0.270,
        0.257,
        0.244,
        0.234,
        0.224,
        0.215,
        0.202
    ]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#13
# Creating the data
data = {
    "Topic": [
        "China's Efforts to Make Yuan Rate More Transparent",
        "Impact of Chinese Investment in Africa",
        "US Pressure on Chinese Investments",
        "Impact of US-China Trade Talks on Yuan",
        "Chinese Economy's Historical Transformation",
        "Outlook for US Dollar's Status",
        "Impact of Chinese Investment in Caribbean",
        "Chinese Yuan's Role in Global Markets",
        "China's Bond Market Opening",
        "South Korean Won's Performance"
    ],
    "Sentiment Score": [
        60,
        40,
        -70,
        -50,
        70,
        -30,
        20,
        50,
        30,
        -40
    ],
    "Importance Score": [
        0.342,
        0.311,
        0.285,
        0.270,
        0.257,
        0.242,
        0.234,
        0.224,
        0.215,
        0.202
    ]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#14
# Creating the data
data = {
    "Topic": [
        "Use of Chinese Currency in Hong Kong",
        "Impact of US Foreign Exchange Policy on Trade",
        "Potential Chinese Current Account Deficit",
        "Global Economic Conditions",
        "Belt and Road Initiative",
        "Chinese Disposable Hygiene Products Industry",
        "Global Trade Growth Trends",
        "Government Measures Against Illegal Religious Groups in China",
        "Influence of Bitcoin News",
        "Ruhnn's IPO Impact on Chinese Economy"
    ],
    "Sentiment Score": [
        20,
        -40,
        -60,
        -30,
        -50,
        40,
        -20,
        -70,
        60,
        30
    ],
    "Importance Score": [
        0.342,
        0.311,
        0.285,
        0.270,
        0.257,
        0.242,
        0.234,
        0.224,
        0.215,
        0.202
    ]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#15
# Creating the data
data = {
    "Topic": [
        "Resumption of Malaysia-China Railway Project",
        "Growth of China's Foreign Exchange Reserves",
        "Impact of U.S.-China Trade War on Global Economies",
        "Currency Rate Trends and Forecasts",
        "U.S.-China Trade Relations",
        "Tech Hub Cities' Cost of Living",
        "Implications of Big Banks in China",
        "Arrest of Chinese Woman at Mar-a-Lago",
        "Investments Focused on China",
        "Macau's Position in U.S. Money Laundering Jurisdictions"
    ],
    "Sentiment Score": [
        60,
        50,
        -40,
        30,
        -50,
        -30,
        20,
        -70,
        40,
        -20
    ],
    "Importance Score": [
        0.345,
        0.312,
        0.287,
        0.272,
        0.259,
        0.244,
        0.231,
        0.221,
        0.213,
        0.202
    ]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#16
# Creating the data
data = {
    "Topic": [
        "China's Financial System Control and Foreign Exposure",
        "U.S. WTO Ruling Against China's Grain Import Quotas",
        "ETF Investments in China",
        "Currency Forecast: EUR/USD Trends",
        "Kazakh Tenge Exchange Rates",
        "OECD GDP Outlook for China",
        "US-China Trade War Impact on Global Economies",
        "Currency Fraud and Victimization in the US",
        "Impact of US Dollar on International Markets",
        "Currency Volatility in Forex Market"
    ],
    "Sentiment Score": [
        -60,
        -40,
        20,
        30,
        40,
        -50,
        -70,
        -80,
        50,
        -20
    ],
    "Importance Score": [
        0.345,
        0.312,
        0.287,
        0.272,
        0.259,
        0.244,
        0.231,
        0.221,
        0.213,
        0.202
    ]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#17
# Creating the data
data = {
    "Topic": [
        "Trade War Impact on Global Macroeconomics",
        "China's Banks Running Out of USD",
        "Huawei's Investment in 5G Technology",
        "China's Surveillance System Export",
        "US Economic Growth Outlook",
        "Luckin Coffee's Expansion Plans",
        "China's Closer Ties with Latin America",
        "Euro to South African Rand Exchange Rate",
        "Asian Development Outlook",
        "China's Efforts to Internationalize the Renminbi"
    ],
    "Sentiment Score": [
        -70,
        -60,
        30,
        -50,
        20,
        40,
        50,
        60,
        10,
        70
    ],
    "Importance Score": [
        0.378,
        0.346,
        0.312,
        0.287,
        0.264,
        0.242,
        0.221,
        0.202,
        0.183,
        0.169
    ]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

#18
import pandas as pd

# Creating the data
data = {
    "Topic": [
        "US-China Tariff War Negotiations",
        "Chinese Wine Imports Decline",
        "Impact of Machine Tool Boom on China",
        "Chinese Student Admissions Scandal",
        "Importance of European Union in US-China Relations",
        "ASEAN Currency Safety Nets",
        "US Participation in Belt and Road Initiative",
        "Global Logistics Market Growth",
        "Hershey Company Sales Growth",
        "Exchange Rate Forecasts"
    ],
    "Sentiment Score": [
        -70,
        -50,
        -30,
        -80,
        60,
        40,
        50,
        20,
        30,
        10
    ],
    "Importance Score": [
        0.324,
        0.299,
        0.276,
        0.254,
        0.234,
        0.216,
        0.199,
        0.183,
        0.169,
        0.156
    ]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the data
data = {
    "Topic": [
        "US-China Tariff War Escalation",
        "Yuan Exchange Rate Flexibility",
        "Trade Talks and Tariffs Impact",
        "Exchange Rate Stability Concerns",
        "Central Bank's Convergence Policy",
        "Impact of US-China Investment Trends",
        "Japanese Yen and Swiss Franc Strength",
        "North Korean Trade Impact",
        "Role of Tariffs in Global Trade Disruption",
        "Chinese-American Financial Relations"
    ],
    "Sentiment Score": [
        -80,
        -40,
        -60,
        -70,
        40,
        60,
        20,
        -30,
        -50,
        70
    ],
    "Importance Score": [
        0.323,
        0.299,
        0.276,
        0.254,
        0.234,
        0.216,
        0.199,
        0.183,
        0.169,
        0.156
    ]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#20
# Creating the data
data = {
    "Topic": [
        "US-China Trade War Escalation",
        "Impact of Tariffs on Apple",
        "Cost Increase for iPhone Due to Tariffs",
        "Chinese Response to Tariffs",
        "Rupee's Movement Against Dollar",
        "Iron Ore Prices Impact on Australian Dollar",
        "Euro-Australian Dollar Exchange Rate",
        "Pound-Indian Rupee Exchange Rate",
        "Pakistani Rupee Depreciation",
        "IMF Loan to Pakistan"
    ],
    "Sentiment Score": [
        -80,
        -60,
        -40,
        -70,
        30,
        50,
        60,
        20,
        -50,
        -30
    ],
    "Importance Score": [
        0.312,
        0.289,
        0.266,
        0.244,
        0.223,
        0.206,
        0.189,
        0.173,
        0.159,
        0.146
    ]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#21
# Creating the data
data = {
    "Topic": [
        "US-China Trade Tensions Impact",
        "China's Currency Decision",
        "US Administration Expands Currency Penalties",
        "Yuan Depreciation Amid Trade War",
        "Euro-Dollar Upside Amid Brexit Uncertainty",
        "Vietnam Stabilizes Dong with USD Sales",
        "Pound's Decline Against Dollar",
        "Indian Rupee Vulnerable Amid Election & Trade War",
        "Impact of USMCA on GBP/CAD Exchange Rate",
        "Tech Cold War and Its Impact"
    ],
    "Sentiment Score": [
        -80,
        -60,
        -40,
        -70,
        20,
        40,
        -50,
        -30,
        50,
        60
    ],
    "Importance Score": [
        0.312,
        0.289,
        0.266,
        0.244,
        0.223,
        0.206,
        0.189,
        0.173,
        0.159,
        0.146
    ]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": [
        "US-China Trade War's Impact on Chinese Firms",
        "Yuan Approaching 7 Against Dollar amid Trade War Escalation",
        "Chinese Concerns over Weaponizing U.S. Treasury Bonds",
        "Impact of Trade War on Global GDP",
        "Vietnam's Trade Success Amid Trade War",
        "Singapore Added to US Currency Manipulation Watchlist",
        "Concerns Over China Dumping US Debt",
        "United States Imposes Duties on Currency Manipulators",
        "India Removed from US Currency Monitoring List",
        "Malaysia Denies Currency Exchange Interference"
    ],
    "Sentiment Score": [
        -80, -70, -50, -75, 60, -30, -40, -60, 40, 20
    ],
    "Importance Score": [
        0.127, 0.123, 0.115, 0.110, 0.107, 0.105, 0.102, 0.100, 0.098, 0.096
    ]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#23
data = {
    "Topic": [
        "Impact of US-China Trade War on Trade Negotiations",
        "Vietnam's Currency Practices Amid US Scrutiny",
        "UK's Economic Benefits from Chinese Investment",
        "Chinese Exporters' Tariff Avoidance Tactics",
        "Visa Restrictions' Impact on US Universities",
        "China's Innovation Board and Capital Market Reforms",
        "US Stock Market's Losses Due to Trade Wars",
        "South Korea's Economic Concerns Amid Weaker Currency",
        "Media Agencies' Market Share in China",
        "US Dollar's Weekly Forecast Amid Trade Uncertainties"
    ],
    "Sentiment Score": [
        -80, -70, -50, -75, -90, 60, -30, -40, 40, 20
    ],
    "Importance Score": [
        0.143, 0.137, 0.132, 0.128, 0.124, 0.120, 0.115, 0.110, 0.105, 0.100
    ]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": [
        "Chinese yuan weakens amid trade tensions",
        "Impact of Chinese tariffs on US manufacturing exports",
        "Chinese middle class turns to offshore assets",
        "Euro gains as global reserve currency",
        "Sino-US trade war comparisons",
        "Trump's warning on further tariffs",
        "Importance of Chinese onshore bonds",
        "Transparency in China's banking system",
        "Goldman Sachs predicts yuan depreciation",
        "Impact of China's bank lending on yuan strength"
    ],
    "Sentiment Score": [
        -80, -70, -60, 50, -30, -85, 70, 80, -45, -55
    ],
    "Importance Score": [
        0.140, 0.135, 0.130, 0.125, 0.120, 0.115, 0.110, 0.105, 0.100, 0.095
    ]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": [
        "Chinese middle class rise boosts export potential",
        "Stability expected in Chinese yuan",
        "Call to combat currency manipulation",
        "Lessons from Japan's trade war with US",
        "Trump's potential currency war escalation",
        "China's tariff strategy amid trade tensions",
        "Hong Kong protests' impact on stability",
        "Stock opportunities amidst market volatility",
        "Gold prices outlook amid global economic headwinds",
        "China's economic slowdown spillover to Australia"
    ],
    "Sentiment Score": [
        70, 50, -85, -30, -90, -55, -65, 60, 75, -40
    ],
    "Importance Score": [
        0.160, 0.155, 0.150, 0.145, 0.140, 0.135, 0.130, 0.125, 0.120, 0.115
    ]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#26
data = {
    "Topic": [
        "Dollar strength against most Asian currencies",
        "Expectations of US rate cuts affecting dollar",
        "Trump's trade war actions affecting currency dynamics",
        "Currency manipulation concerns and global instability",
        "National currency policy changes impacting Zimbabwe",
        "US-China trade tensions and tariff negotiations",
        "Facebook's Libra and its potential impact on currencies",
        "Russia and China's shift away from US dollar",
        "G20 summit outcome and its implications",
        "UK-Germany economic data and its effect on pound-euro"
    ],
    "Sentiment Score": [
        -50, -40, -60, -70, -80, -55, 30, 50, 70, 40
    ],
    "Importance Score": [
        0.150, 0.145, 0.140, 0.135, 0.130, 0.125, 0.120, 0.115, 0.110, 0.105
    ]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": [
        "Impact of US-China trade truce on CNY/USD exchange rate",
        "Iran's multi-rate foreign exchange system",
        "Venezuela's currency devaluation and lessons learned",
        "Eurozone PMI's effect on EUR/ZAR exchange rate",
        "RBA's interest rate decision impact on AUD/USD",
        "China's intervention amid US-China trade truce",
        "US-China competition and missile tests in South China Sea",
        "Demographic impact on US-China rivalry",
        "Progress in US-China trade talks",
        "Market reaction to US-China trade truce"
    ],
    "Sentiment Score": [
        60, -70, -80, 40, -50, 70, -60, -30, 50, 30
    ],
    "Importance Score": [
        0.180, 0.175, 0.170, 0.165, 0.160, 0.155, 0.150, 0.145, 0.140, 0.135
    ]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": [
        "Impact of US-China trade tensions on CNY/USD exchange rate",
        "China's foreign exchange reserves rise unexpectedly",
        "US-China trade talks and their effect on currency",
        "Trump's currency war rhetoric persists",
        "China's possible currency manipulation amid tariffs",
        "Drop in Chinese imports of US goods",
        "China's imports from US plunge amid tariff war",
        "Taiwan defends arms deal with US amid China's sanctions",
        "China's efforts to counter US 'offset' strategy",
        "China's rising tech scene and potential brain drain"
    ],
    "Sentiment Score": [
        -50, 40, 30, -60, -70, -80, -90, 20, 10, 50
    ],
    "Importance Score": [
        0.200, 0.190, 0.180, 0.170, 0.160, 0.150, 0.140, 0.130, 0.120, 0.110
    ]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

#29
import pandas as pd

data = {
    "Topic": [
        "Impact of China's currency manipulation on US trade",
        "US-China trade tensions and their effect on global growth",
        "Potential actions by Trump to weaken the dollar",
        "Gold as a hedge in currency wars",
        "Impact of US-China trade war on VLGC fleet",
        "Slowdown in Chinese investment in the US",
        "Importance of US dollar's position in global economy",
        "Economic consequences of Facebook regulation concerns",
        "Establishing a Hong Kong holding company for Chinese investments",
        "Forecast on world's best currency rally heading for a crash"
    ],
    "Sentiment Score": [
        -80, -70, -60, 30, -50, -40, 50, -30, 20, -20
    ],
    "Importance Score": [
        0.200, 0.190, 0.180, 0.170, 0.160, 0.150, 0.140, 0.130, 0.120, 0.110
    ]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": [
        "Impact of US-China trade war on unemployment rates",
        "Potential benefits of ending U.S. dollar hegemony",
        "Trump's statements on weakening the U.S. dollar",
        "Impact of U.S.-China trade tensions on FX markets",
        "Globalization's evolution amidst U.S. policy changes",
        "Monetary stability concerns in Hong Kong",
        "USD/CAD exchange rate movements",
        "Trump's stance on currency intervention",
        "Comparison of USD value against other currencies",
        "China's STAR Market and its impact on global finance"
    ],
    "Sentiment Score": [
        -80, 70, -60, -40, 30, -50, -20, 50, 40, 20
    ],
    "Importance Score": [
        0.200, 0.190, 0.180, 0.170, 0.160, 0.150, 0.140, 0.130, 0.120, 0.110
    ]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Weakening of China's currency below key threshold",
              "Impact of Trump's tariff threats on yuan and USD",
              "China's retaliation threats against Trump's tariff hike",
              "Escalation of US-China trade war affecting global markets",
              "Chinese yuan reaches lowest level against USD",
              "China's use of currency devaluation as trade war strategy",
              "Revelation of China's foreign exchange reserves composition",
              "Impact of trade spats and Fed outlook on South Korean won",
              "Ongoing trade negotiations between US and China",
              "Effect of trade war on global tech companies, including Apple"],
    "Sentiment Score": [-90, -80, -70, -85, -75, -80, 70, -60, 50, -70],
    "Importance Score": [0.652, 0.423, 0.285, 0.524, 0.389, 0.362, 0.798, 0.201, 0.756, 0.618]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

#32 Create the DataFrame
data = {
    "Topic": [
        "U.S.-China Currency War",
        "Yuan Devaluation",
        "China's Currency Manipulation",
        "Trade War Escalation",
        "Impact on Global Markets",
        "IMF Report Contradicting Currency Manipulation",
        "China's Economic Vulnerability",
        "Yuan's Psychological Importance",
        "Trump Administration Actions",
        "Impact on US-China Relations"
    ],
    "Sentiment Score": [
        -90, -70, -80, -75, -65, 50, -60, 70, -85, -70
    ],
    "Importance Score": [
        0.456, 0.234, 0.345, 0.234, 0.189, 0.123, 0.178, 0.067, 0.234, 0.167
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#33
data = {
    "Topic": [
        "US accuses China of currency manipulation",
        "Escalation of US-China trade war to currency war",
        "US labels China as a currency manipulator",
        "Fallout from US-China trade war spreads",
        "Impact of US-China trade war on advertising",
        "IMF report refutes US claim of currency manipulation",
        "Political dynamics in currency war",
        "Concerns about reignition of currency war",
        "Analysis of US-China currency war implications",
        "Trade war winners and losers"
    ],
    "Sentiment Score": [
        -90, -80, -70, -60, -50, 40, 50, -40, 30, 20
    ],
    "Importance Score": [
        0.230, 0.220, 0.210, 0.200, 0.190, 0.180, 0.170, 0.160, 0.150, 0.140
    ]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Labeling China as a currency manipulator by the US",
              "Impact of escalating trade tensions on the global economy",
              "IMF warning against currency devaluations",
              "Change in Indian rupee's performance due to trade war",
              "Causal relationship between budget deficit and current account deficit in China",
              "Western reaction to Trump's 'Currency War' with China",
              "Debate over China's currency manipulation accusation",
              "Federal Reserve's stance on sustaining economic expansion",
              "China-Pakistan relations and their implications",
              "Impact of global economic concerns on North Korean won"],
    "Sentiment Score": [-80, -85, -75, -70, -65, -70, -60, 60, 50, -65],
    "Importance Score": [0.738, 0.602, 0.489, 0.324, 0.267, 0.556, 0.405, 0.817, 0.201, 0.733]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#35
data = {
    "Topic": ["Yuan hitting an 11-year low",
              "Impact of trade war on China's currency",
              "Decline in yuan's value and its implications",
              "Hong Kong protests affecting yuan's global standing",
              "Effect of trade war fear on AUD/USD exchange rate",
              "Speculations on trade war turning into a currency war",
              "Efforts by China's central bank to stabilize the yuan",
              "Concerns over China's stimulus measures affecting currency",
              "Predictions on yuan's future stability",
              "Impact of US-China trade war on global economies"],
    "Sentiment Score": [-80, -85, -75, -70, -65, -70, 60, 50, 55, -60],
    "Importance Score": [0.812, 0.678, 0.569, 0.423, 0.312, 0.765, 0.921, 0.235, 0.678, 0.789]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#36
data = {
    "Topic": ["Trade tensions between US and China impacting currency",
              "Impact of US dollar strength on global economies",
              "Effect of trade war on Chinese currency",
              "Renminbi's slow adoption as a reserve currency",
              "US-China trade relations affecting manufacturing",
              "US Dollar Index hitting a two-year high",
              "Trade war repercussions on global companies",
              "Domestic economic indicators affecting currency",
              "Tariff impact on Chinese products and industries",
              "Global economic uncertainty leading to currency fluctuations"],
    "Sentiment Score": [-85, -80, -75, -70, -75, 70, 65, 60, 55, -60],
    "Importance Score": [0.823, 0.678, 0.569, 0.423, 0.312, 0.765, 0.921, 0.235, 0.678, 0.789]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Impact of China's monetary policy on currency stability",
              "Introduction of China's new digital currency",
              "Trade tensions between US and China affecting currency manipulation accusations",
              "Effect of tariffs and trade policies on currency fluctuations",
              "European Central Bank's actions influencing US-China trade relations",
              "Impact of safe-haven demand on exchange rates",
              "Discussion on currency manipulation accusations by the US",
              "Effects of currency fluctuations on remittances and exchange rates",
              "Global economic trends influencing currency value",
              "Investor reactions to currency fluctuations and economic policies"],
    "Sentiment Score": [80, 75, -70, -65, -60, 60, -55, -50, 45, 40],
    "Importance Score": [0.865, 0.739, 0.632, 0.578, 0.521, 0.469, 0.413, 0.365, 0.317, 0.274]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Renminbi's potential as a reserve currency",
              "Impact of US-China trade tensions on global markets",
              "Currency fluctuations in Zimbabwe",
              "Iranian geopolitical tensions affecting oil supply",
              "Liberalization of China's portfolio flows",
              "US-China trade war implications for the Indian economy",
              "Emerging markets response to global monetary policies",
              "Foreign exchange trading volume and dominance of USD",
              "Attractiveness of Southeast Asian real estate markets",
              "Factors influencing monetary policy decisions"],
    "Sentiment Score": [80, -85, -90, -75, 70, -60, 65, 55, 60, -70],
    "Importance Score": [0.921, 0.823, 0.678, 0.569, 0.423, 0.312, 0.765, 0.235, 0.678, 0.789]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["US-China trade tensions and their impact on global economy",
              "Trump administration's policies affecting US-China economic relations",
              "Potential delisting of Chinese companies from US stock exchanges",
              "Currency fluctuations affecting emerging markets",
              "Chinese economic size relative to the US and its implications",
              "Impact of US-China trade tensions on specific industries",
              "Russian efforts to reduce dependency on the US dollar",
              "Currency fluctuations affecting Indian and South Korean economies",
              "Exchange rate movements between USD/CAD",
              "Attractiveness of Southeast Asian real estate markets"],
    "Sentiment Score": [-80, -85, -90, -75, 70, 60, 55, -60, 65, 60],
    "Importance Score": [0.921, 0.823, 0.678, 0.569, 0.423, 0.312, 0.765, 0.235, 0.678, 0.789]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#40
data = {
    "Topic": ["US-China trade tensions and their impact on global economy",
              "Policy decisions by the Trump administration affecting US-China relations",
              "Potential delisting of Chinese companies from US stock exchanges",
              "Global economic uncertainty and its effect on exchange rates",
              "Comparison of military strength between China and the US",
              "Impact of US dollar devaluation on global markets",
              "Chinese market influence on US-based platforms like Amazon",
              "Gold as an alternative investment compared to equities",
              "Comparative analysis of different Chinese regions' economic futures",
              "Discussion of monetary policy and its impact on globalization"],
    "Sentiment Score": [-80, -85, -90, -75, 70, 60, 55, -60, 65, 60],
    "Importance Score": [0.923, 0.822, 0.675, 0.567, 0.420, 0.310, 0.760, 0.233, 0.675, 0.789]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Impact of US-China trade tensions on global economy",
              "Monetary policy implications and fiscal spending strategies",
              "US tariffs and their effects on the US economy",
              "Progress and setbacks in US-China trade negotiations",
              "Central bank actions and currency wars",
              "Sanctions and geopolitical tensions affecting trade dynamics",
              "Global competitiveness rankings and economic outlook",
              "Analysis of central bank policies and easing measures",
              "Market reactions to trade talks and geopolitical developments",
              "Chinese economic indicators and gold purchases"],
    "Sentiment Score": [-80, -75, -85, 70, 60, 55, -60, 65, -90, 60],
    "Importance Score": [0.923, 0.822, 0.675, 0.567, 0.420, 0.310, 0.760, 0.233, 0.675, 0.789]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Strength of the US Dollar against Chinese Yuan",
              "China's Central Bank Digital Currency (CBDC)",
              "Trade War implications for global economies",
              "China's economic slowdown indicators",
              "Intellectual Property Rights (IPR) improvements in China",
              "Market speculation and forecasts on the Yuan's performance",
              "Impact of US-China trade tensions on the global economy",
              "Currency manipulation concerns",
              "Economic slowdown in China affecting global growth",
              "US-China trade negotiations and their outcomes"],
    "Sentiment Score": [80, 70, -85, -75, 60, 55, -90, -70, -80, 75],
    "Importance Score": [0.900, 0.800, 0.925, 0.850, 0.750, 0.700, 0.975, 0.600, 0.825, 0.775]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Impact of US-China Trade Deal on Yuan Stability",
              "Hong Kong's Influence on Chinese Financial Stability",
              "Progress in US-China Trade Negotiations",
              "Forecasting Yuan-Dollar Exchange Rate",
              "Concerns Over Dollar Weaponization",
              "Role of China in South African Economic Zones",
              "Chinese Response to IMF Quota Adjustments",
              "China's Yuan-Denominated Contracts with Global Companies",
              "Shift in Wealth Rankings: China vs. US",
              "Global Market Impact on Australian Dollar"],
    "Sentiment Score": [75, -60, 80, 70, -50, 55, 65, 60, 70, -45],
    "Importance Score": [0.850, 0.700, 0.925, 0.800, 0.650, 0.750, 0.675, 0.600, 0.725, 0.775]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Dollar Losing Reserve Currency Status",
              "Impact of US-China Trade War on Global Economies",
              "US Economic Sanctions and Global Health",
              "Chinese Financial Behavior and Debt Trends",
              "Federal Reserve's Interest Rate Decisions",
              "China's Position in Global Technology and Trade",
              "Impact of US-China Trade Talks on Global Markets",
              "China's Belt and Road Initiative",
              "China's Digital Currency Development",
              "China's Investment Patterns and Economic Trends"],
    "Sentiment Score": [-80, -70, -60, -50, -30, 60, 50, 70, 75, 55],
    "Importance Score": [0.875, 0.800, 0.725, 0.650, 0.550, 0.425, 0.375, 0.300, 0.250, 0.200]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["East Asian Value Chains and Regional Exchange Rates",
              "US-China Trade War Impact on Global Technological Leadership",
              "Pandas as Diplomatic Currency",
              "Trade Protectionism and Global Economic Outlook",
              "Australian Dollar Performance Amid Economic Surveys",
              "GBP/USD Exchange Rate Dynamics Amid Trade Hopes",
              "Bangladesh's Apparel Industry and Currency Devaluation",
              "EUR/USD Exchange Rate Response to Eurozone Economy",
              "Euro's Response to Christine Lagarde and Trade Hopes",
              "Euro's Decline Due to Trade Tensions and Strong US Data"],
    "Sentiment Score": [-70, -60, 60, -50, 70, -30, -20, 40, 50, -40],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#46
data = {
    "Topic": ["China's Diversification Away from USD",
              "Japanese Yen's Global Importance",
              "Impact of US-China Trade War on Trade Deficit",
              "Geopolitical Shifts in East Asia",
              "Market Skepticism on Currency Agreements",
              "China's Economic Challenges Amid Trade War",
              "Lessons from Asian Financial Crisis for Hong Kong",
              "US Dollar Stability and Federal Reserve's Stance",
              "Currency Trends in Southeast Asia",
              "Global Economic Impact on Forex Earnings"],
    "Sentiment Score": [-80, 70, -60, -40, -50, -70, -30, 40, -20, 50],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Impact of U.S. Foreign Exchange Policy on Dollar",
              "Effects of US-China Trade War on US Communities",
              "Potential Veto of Legislation Affecting China",
              "China's GDP Growth and Data Reliability",
              "Decline in Japanese Exports Amid Trade War",
              "Trump Administration's Influence on Dollar Value",
              "Stock Market Performance and Investor Sentiment",
              "Changes in Foreign Investment Requirements",
              "Diplomatic Relations Between US and China",
              "Impact of China-US Trade War on Global Economy"],
    "Sentiment Score": [-80, -70, -60, 50, -50, 30, 40, -30, -20, -10],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Impact of US-China Trade Conflict on Europe and the Euro",
              "Taxation on Imports from China and its Economic Ramifications",
              "Chinese Investment in the Cambodian Economy",
              "Forecast for the US Dollar in 2020 by Financial Institutions",
              "Outlook for the US Dollar Amid Federal Reserve's Interest Rate Cuts",
              "Economic Slowdown in South Korea Due to Trade War and Tech Issues",
              "BRICS Nations Exploring Cryptocurrency to Reduce Dependence on USD",
              "Political Tensions in Taiwan Regarding Anti-Infiltration Bill",
              "Market Performance Comparison between Samsung and TSMC",
              "Perception and Reality of Forex Trading Success Stories"],
    "Sentiment Score": [-80, -70, 50, -50, 30, -20, 40, -30, -10, -5],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["New US Dollar Transfers Frozen by Chinese Bank",
              "Views of the Balance of Power Between US and China",
              "The Beginning of a New Cold War Between US and China",
              "China's New Foreign Exchange Rules to Ease Transactions",
              "The Importance of the Japanese Yen in Global Currency",
              "Long-term Correlation Shifts Between Dollar and Gold Prices",
              "Impact of Trump's Tweet on Brazil and Argentina on Exchange Rates",
              "Strategies for Maintaining Chinese Economic Growth in 2020",
              "Trade War Effects: US Tariffs on Brazil and Argentina",
              "Economic Indicators and Trade Deficits with China"],
    "Sentiment Score": [-80, -70, -60, 40, 50, 20, -30, 30, -40, -20],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#50
data = {
    "Topic": ["US-China Phase One Trade Deal",
              "Impact of US-China Trade Deal on Currency Markets",
              "Future Prospects of US-China Trade Deal",
              "China's Role in Global Trade Slowdown",
              "China's Smart Cities and Economic Growth",
              "Long-term Growth Trends in China",
              "Impact of UK Election Results on GBP/USD Exchange Rate",
              "GBP/NZD Exchange Rate Ahead of UK Election",
              "Rupee Performance Against Dollar",
              "GBP/JPY Exchange Rate Trends"],
    "Sentiment Score": [80, 70, 60, -50, 70, 60, 50, 50, 40, 40],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Launch of Digital Chinese Yuan by PBOC",
              "Efforts to Control Capital Outflows from China",
              "Impact of US-China Trade War on Chinese Economy",
              "Chinese Economic Growth and Its Implications",
              "Exchange Rate Pressure Predictions for 2020",
              "Trade-based Headlines and Currency Trajectories",
              "Influence of China's Economy on CADUSD Exchange Rate",
              "Significance of US-China Trade Deal on Exchange Rates",
              "US-China Relations and Economic Policy Implications",
              "Concerns about China's Economic Weaknesses and Policy Development"],
    "Sentiment Score": [80, -60, -50, -40, -30, 20, 30, 40, -10, -20],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Weakening of Chinese Yuan Against USD",
              "Globalization of Chinese Currency to Challenge Dollar",
              "Impact of US-China Trade Deal on Korean Won",
              "False Claims Regarding China and Tariffs by President Trump",
              "Iran's Turn to China and India Amid US Sanctions",
              "Money Laundering Scandal in British Columbia's Casinos",
              "North Korea's Relation with China and Russia Amid US Defiance",
              "Improvement in China Trade Sentiment Impacting NZ Dollar",
              "US-China Trade War Impact on Taiwan's Economy",
              "Reversal of Thai Baht's Performance"],
    "Sentiment Score": [-80, 70, 60, -70, -60, -50, -40, 50, -30, -20],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

len(bound)

bound=pd.DataFrame(bound)
bound.to_csv('cnyusdscore2019.csv')