# -*- coding: utf-8 -*-
"""cnyusd2021.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rKbOFYCR3GhyZx-xUm-pIL-3sqcaaBGW
"""

from sklearn.preprocessing import MinMaxScaler

import numpy as np

def weekly_score(df):
  transfer=MinMaxScaler(feature_range=(0.1,0.5))
  df_1=np.array(df.iloc[:,2]).reshape(-1, 1)
  df_1=transfer.fit_transform(df_1)
  d=np.array(df.iloc[:,1])*df_1.reshape(1, -1)
  upper=int(sum(np.maximum(d,0).T))
  lower=int(sum(np.minimum(d,0).T))
  return upper,lower

bound=[]
raw_data=[]

import pandas as pd

# Create the dataframe
df = pd.DataFrame({
    "Topic": [
        "Chinese Yuan At Strongest Level Against US Dollar Since Mid-2018",
        "Best Pound-Dollar Exchange Rate for Over Two-and-a-Half Years",
        "Pound Sterling sees Gains Evaporate as 2021 Gets Underway",
        "Euro-Dollar Rate Gains Ahead of Key Georgia Senate Race",
        "Chinese exchange rate seeking a catalyst",
        "U.S. Dollar As 'Global Reserve Currency' Amid Fed's QE And ...",
        "Central banks accelerate shift from dollar to gold worldwide",
        "U.S. Dollar Holds Lead in G10 for 2021 after Second Half Comeback",
        "China calls for swift return of missing soldier held by India",
        "Nearly 3 million farmers embrace CIP-bred potatoes, raising ..."
    ],
    "Sentiment Score": [
        90, 85, -70, 75, -60, -90, 80, 70, -100, 45
    ],
    "Importance Score": [
        0.987, 0.956, 0.925, 0.894, 0.863, 0.832, 0.801, 0.770, 0.739, 0.708
    ]
})

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Biden stimulus plan impact on Dollar", "Canadian commodities boom", "Norwegian Krone attractiveness",
              "Exchange rate forecasts", "Pound to Dollar exchange rate", "Forex-3D kingpin caught",
              "Egyptian strawberry growth", "Banana prices increase in Ecuador", "Hira Textile Mills shift request",
              "Accused Forex-3D kingpin apprehended"],
    "Sentiment Score": [-60, 40, 60, 20, 50, -80, 20, 20, 10, -90],
    "Importance Score": [0.315, 0.234, 0.201, 0.154, 0.123, 0.098, 0.078, 0.061, 0.048, 0.038]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#w3
data = {
    "Topic": ["China's currency outlook under Biden administration", "China's economic performance in 2020 vs. US",
              "Hong Kong's role in Renminbi internationalization", "China issues new rules in response to Trump's sanctions",
              "Environmental impact of China's plastic import ban", "RLX Technology's trading debut",
              "Chinese securities firm's warrant output increase", "Emerging market bond ETF performance",
              "Euro-to-dollar exchange rate forecast", "Chinese car imports success in Vietnam"],
    "Sentiment Score": [50, 40, 60, -20, 20, 70, 30, 40, 20, 30],
    "Importance Score": [0.300, 0.250, 0.200, 0.150, 0.120, 0.090, 0.070, 0.050, 0.040, 0.030]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["China's potential challenge to US dollar hegemony", "Speculation about Plaza Accord II and its currency implications",
              "Impact of US-China trade policies on currency dynamics", "China's economic growth and its impact on global economy",
              "China's use of yuan for commodity stockpiling", "Volatility drivers in the global market",
              "Janet Yellen's stance on currency strength", "Reebok Instapump Fury OG release for Chinese New Year",
              "Currency exchange rate updates in Pakistan", "Impact of LyondellBasell's earnings on currency markets"],
    "Sentiment Score": [60, 50, -30, 40, 30, 20, -10, 70, 20, 40],
    "Importance Score": [0.300, 0.250, 0.200, 0.150, 0.120, 0.090, 0.070, 0.050, 0.040, 0.030]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["US monetary policy uncertainty drives global business cycles",
              "Will Biden Force U.S. Taxpayers To Fund a Massive International Monetary Fund Bailout of China?",
              "China should not count on strong US policy under Yellen to ease yuan pressure",
              "Strong full-year results demonstrate Unilever's resilience and agility",
              "Exchange-Traded Fund Services",
              "After 2020 trade surplus, why did China’s forex reserves grow so little?",
              "Container crunch upends global food trade while ships queue at U.S. ports",
              "New forex rules to rein in speculation",
              "Myanmar Coup Criticized by China, US, Other UN Security Council Members",
              "RIAC :: Barriers to de-Dollarization Within BRICS"],
    "Sentiment Score": [-50, -40, -30, 40, 50, 60, -70, -80, -90, 100],
    "Importance Score": [0.350, 0.320, 0.290, 0.260, 0.230, 0.200, 0.170, 0.140, 0.110, 0.080]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix #6
data = {
    "Topic": ["China and SWIFT Partner to Take Digital Currency Global",
              "Biden aims to isolate China on coal — but it could blow back on the U.S.",
              "Three ways the EU, China and US should deepen cooperation on climate in 2021",
              "Overview of China outbound investment in H1 2020",
              "China's record corn purchases have traders wondering if bump can last",
              "Joe Biden holds first call with Xi Jinping since taking office",
              "Exclusive: Vietnam intervened in currency markets weeks after U.S. censure: sources",
              "The top 20 largest economies in the world by GDP",
              "Tibet’s geo-strategic relevence in the Indo-Pacific theatre: Military analyses",
              "US admiral says Chinese military activity is rising in S China Sea"],
    "Sentiment Score": [30, -20, 40, 50, 60, -70, -80, 90, 100, -100],
    "Importance Score": [0.320, 0.290, 0.260, 0.230, 0.200, 0.170, 0.140, 0.110, 0.080, 0.050]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["China targets rare earth export curbs to hobble US defence industry",
              "US concerned at Chinese law allowing coast guard use of arms",
              "Biden aims to isolate China on coal — but it could blow back on the U.S.",
              "Cutting China off from the U.S. would cost America hundreds of billions of dollars, report says",
              "China mulls allowing more overseas investment in stocks, insurance",
              "New Balance 2002R 'Year of the Ox'",
              "HSBC intensifies pivot to Asia with job moves and US exit",
              "Kenya Is Becoming a Global Hub of FinTech Innovation",
              "Here's why China's trade deal with Mauritius matters",
              "Bitcoin offers freedom from political repression—and that’s a key to its future"],
    "Sentiment Score": [-80, -70, -60, -40, -20, 20, 40, 60, 70, 80],
    "Importance Score": [0.350, 0.320, 0.290, 0.260, 0.230, 0.200, 0.170, 0.140, 0.110, 0.080]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix #8
data = {
    "Topic": ["China mulls allowing citizens to invest in overseas stocks",
              "China, UAE join Hong Kong, Thai cross border CBDC trials",
              "Central bank digital currencies breakthrough in Asia",
              "Parity for yuan-USD rises 47 bps",
              "How vulnerable is China to US bond ‘taper tantrum’?",
              "The yuan is on a tear, but is it sustainable?",
              "China's Xi declares victory in ending extreme poverty",
              "Allowing foreign exchange purchases may not affect yuan rate much",
              "Statistical Communiqué of the People's Republic of China on the 2020 National Economic and Social Development",
              "Column「U.S. Dollar Reliance and International Monetary System in East Asia」"],
    "Sentiment Score": [-90, -80, -70, -60, -40, -20, 20, 40, 60, 90],
    "Importance Score": [0.350, 0.320, 0.290, 0.260, 0.230, 0.200, 0.170, 0.140, 0.110, 0.080]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Excess liquidity risks may see China relax overseas investment rules",
              "China commenced the annual meeting of its National People's Congress",
              "Chinese experts on potential dollar collapse: growing bearish consensus",
              "Wall Street is kicking out yet another big Chinese company",
              "Soft power as a policy rationale for international education in China",
              "China Claims It Has Eliminated Poverty But Is That True?",
              "Understanding China's 2021 Defense Budget",
              "Big Mac Prices – No Bull",
              "Rare Chinese bowl bought for $35 could fetch up to $500000 at auction",
              "China, India Lead FinTech Adoption; US, Korea, Japan Below Global Average"],
    "Sentiment Score": [-100, -90, -80, -70, -60, -50, -40, -30, -20, -10],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["China's Yuan Erases 2021 Gain as Dollar Rises With U.S. Yield",
              "China approves $1.5 billion currency swap with Sri Lanka",
              "FX Markets Provide Opportunity to Hedge in Copper Trades",
              "AI Report: Competition Grows Between China and the U.S.",
              "Bailouts From Beijing: How China Functions as an Alternative to the IMF",
              "Taiwan governor optimistic over US currency dispute",
              "Chinese stocks enter correction territory - China",
              "The problem with linking debt forgiveness to the Sustainable Development Goals",
              "Westerners are increasingly scared of traveling to China as threat of detention rises",
              "Microsoft's big email hack: What happened, who did it, and why it matters"],
    "Sentiment Score": [-100, -90, -80, -70, -60, -50, -40, -30, -20, -10],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["U.S.-China talks in Alaska got off to a rough start",
              "Spamming of US dollar will hurt emerging markets",
              "U.S., Chinese diplomats clash in high-level meeting of Biden administration",
              "China Hikes Defense Budget Again as U.S. Weighs Flatlining Pentagon Spending",
              "India’s middle class shrinks amid COVID-19 as China sees less change",
              "Terse Alaska meeting ignites anti-US Chinese nationalism",
              "Steel spreads analysis: US-China HRC price difference hits historic high",
              "Shell, Transsion among 10 picked by China for cross-border currency plan",
              "China and U.S. appear set for a frosty Alaska summit",
              "First U.S.-China meeting under Biden gets off to a rocky start"],
    "Sentiment Score": [-90, -100, -85, -70, -50, -30, -10, 20, 40, 60],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix #12
data = {
    "Topic": ["Foreign-exchange reserves are both an insurance policy and a lightning rod for criticism | Finance & economics.",
              "Spamming of US dollar will hurt emerging markets",
              "The hidden repercussions of public debt in the West – GIS Reports",
              "Trade inflows in Asia fuel debate over currency intervention",
              "China's Vision 2035 Plan: Megacities, Trade, Market Consumption",
              "Riel benefits: CSX index helps to build currency confidence in Kingdom",
              "US-China Diplomacy: Dueling Accusations Set Testy Tone",
              "Pound Yen Exchange Rate Climbs As Japanese Private Sector Businesses Subdued",
              "12-Month GBP/AUD Forecast: Pound-to-Australian Dollar Rate To Target 1.72 Says Westpac Analyst",
              "GM Wuling Pickup Launched In China At USD 9k (Rs 6.5 L Approx)"],
    "Sentiment Score": [-80, -100, -60, -40, 70, 80, -20, 90, 100, 60],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["China's currency set for worst month since US trade war",
              "US economy strength keeps pressure on yuan",
              "Worst Yuan Selloff in Year Drives Traders Back to Daily Fix",
              "The US dollar’s hegemony is looking fragile",
              "Opinion | Don't Let China Mint the Money of the Future",
              "Impact of Fed policy changes on China's markets is limited",
              "Doing business in China is difficult. A clash over human rights is making it harder",
              "Gold and US Dollar Hegemony",
              "China, With $400 Billion Iran Deal, Could Deepen Influence in Mideast",
              "China’s stock exchange plan to lure overseas-listed firms home"],
    "Sentiment Score": [-80, -70, -60, -50, -40, -30, -20, -10, 20, 40],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["China Creates Its Own Digital Currency, a First for Major Economy",
              "China's Digital Currency Is About To Disrupt Money",
              "China's digital yuan will be distributed with the help of commercial banks",
              "Digital yuan another sign that U.S. must accept China's rise",
              "China's Digital Yuan Offers Privacy Protection for 'Small Transactions'",
              "US envoy warns China-backed Colombo Port project may create safe haven for money launderers",
              "China's Xi and Trump tee up Mar-a-Lago summit",
              "Sanctions Are Destroying U.S. Dollar's Status as World's Top Currency",
              "US billionaire Peter Thiel calls bitcoin a Chinese financial weapon",
              "The pushback from U.S. rivals underscores the limits of dollar deterrence"],
    "Sentiment Score": [80, 70, 60, 50, 40, -40, -50, -60, -70, -80],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix15
data = {
    "Topic": ["China's digital currency is a threat to dollar dominance",
              "Rate Rises Spell Success for Canadian Dollar and Euro",
              "Chinese, US luxury lovers power rebound at LVMH",
              "New Wuling Hong Guang MINI EV Macaron Launches In China",
              "Chinese vs. American Buick Enclave: Side By Side Comparison",
              "US finds no 'currency manipulators'",
              "U.S. stops short of branding Vietnam, Switzerland, Taiwan currency manipulators",
              "Taiwan dollar weakens over fears of US action",
              "US starts pushing Taiwan to address undervalued currency",
              "Taiwan dollar drops with US set to apply currency manipulator tag"],
    "Sentiment Score": [90, 80, 70, 60, 50, 40, -40, -50, -60, -70],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["China's yuan is overvalued, and that could stoke global inflation",
              "Chinese Firms Are Listing in the U.S. at a Record-Breaking Pace",
              "Indonesian rupiah slide ties central bank's hands",
              "Heavily indebted developer China Evergrande to sell onshore bonds worth US$1.3 billion",
              "NT dollar gains as US hints at valuation pressure",
              "The U.S. Treasury's Foreign Exchange Report Signals a Shift in Approach",
              "China’s ‘goal is not to replace US dollar’ with the yuan",
              "China emerging as a major destination for African students",
              "Digital yuan gives China a new tool to strike back at critics",
              "China Reaffirms its Digital Yuan Poses No Threat to the U.S. Dollar Dominance"],
    "Sentiment Score": [-90, -80, -70, -60, -50, 40, 30, 20, 10, 5],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["China's Central Bank Works with Ant, Tencent to Develop Digital Currency",
              "Explainer: An e-yuan, euro or dollar? Central banks get to grips with digital cash",
              "Meituan Rises In Hong Kong Trading As Lufax Earnings Beat Expectations",
              "CECEP Wind decides to build 75 MW of wind parks in China",
              "PayPal’s ambition and uphill battle in China",
              "Economic Crises in Foreign Markets Reduce U.S. Agricultural Exports",
              "Fed's Powell: China's approach to digital currency would not work in U.S.",
              "After Xiaomi, Baidu and Alibaba, another internet giant is joining the EV race.",
              "Asian Equities Rejoice Over Powell’s Comments, Tencent’s Fine Is A Rounding Error",
              "Why investors in China private equity might be missing out on most of the market"],
    "Sentiment Score": [90, 80, 70, 60, -70, -60, -50, -40, -30, -20],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix18
data = {
    "Topic": ["China’s Most Popular Podcast Platform Files for U.S. Listing",
              "Rain Called Kim Tae Hee 'Nuna' And Now We're All Falling For His Charms",
              "BTS V's Chinese Fanclub Sets Record Breaking Fundraiser For His Birthday In December",
              "An interview with Mohammed Zaki Bashir, CEO of Gul Ahmed Textiles Limited",
              "An uneven global economic recovery in 2021 promises to invert a longstanding principle of success and failure",
              "CBIRC Fines Shanghai Pudong Development Bank For Mis-selling",
              "Three Chinese telecom companies to be delisted by NYSE",
              "Combined China and Russian Defense Spending Exceeds U.S. Defense Budget",
              "Tesla Faces Backlash in China from Viral Video",
              "NYSE to Delist Chinese Telecom Carriers After Rejecting Appeals"],
    "Sentiment Score": [90, 80, 70, 60, -70, -60, -50, -40, -30, -20],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["USD/JPY Price Forecast for 2021 and Future Predictions | FX Leaders",
              "China's much-hyped digital yuan leaves early users underwhelmed",
              "Myanmar currency hits record low as economy fails to normalize",
              "USD/JPY Price Forecast for 2021 and Future Predictions | FX Leaders",
              "USD/JPY Price Forecast for 2021 and Future Predictions | FX Leaders",
              "Myanmar coup, from Apr. 16 to May 14: Japan pledges food aid through WFP",
              "Nancy Qian | The two sides of Chinese GDP",
              "China's digital currency could be the future of money – but does it threaten global stability?",
              "USD/JPY Price Forecast for 2021 and Future Predictions | FX Leaders",
              "Euro-Dollar Week Ahead Forecast: Eyeing 1.22 as USD Blinks in Fed Stare Down"],
    "Sentiment Score": [-90, -80, -70, -60, -50, 50, 60, 70, 80, 90],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix20
data = {
    "Topic": ["China to keep yuan exchange rate basically stable: PBOC",
              "PBOC Says It Will Maintain Exchange Rate 'Basically Stable'",
              "No plans to ease yuan exchange rate controls, central bank says",
              "PBOC: Two-way fluctuations of yuan will become norm in the future",
              "China's much-hyped digital yuan leaves early users underwhelmed",
              "Trump's Tariffs Were Much More Damaging Than Thought",
              "Bitcoin falls further as China cracks down on crypto-currencies",
              "China must ‘let go’ of yuan exchange rate to boost global use",
              "US Remains Preeminent Economic Superpower as China Rises",
              "Russia supports China's peaceful rise - Chinadaily.com.cn"],
    "Sentiment Score": [90, 80, 70, 60, -90, -80, -70, -60, 50, 60],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Yuan rally fuels debate about using it to fight surging commodity prices",
              "RMB climbs to three-year high against dollar",
              "China's renminbi hits three-year high against dollar",
              "Yuan continues to climb as regulators warn on speculative currency bets",
              "How China went from laggard to leader in distributing COVID-19 vaccines",
              "Australia shrugs off China trade dispute and opens new markets",
              "Pakistan economic crisis intensifies as China refuses to provide debt relief",
              "The demise of the dollar? Reserve currencies in the era of 'going big'",
              "HKEX is key to China's plan to internationalize its economy",
              "Tech Pro Scandal Is Hong Kong's Latest Regulatory Black Mark"],
    "Sentiment Score": [80, 70, 60, 50, 40, -80, -70, -60, -50, -40],
    "Importance Score": [0.300, 0.270, 0.240, 0.210, 0.180, 0.150, 0.120, 0.090, 0.060, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix22
data = {
    "Topic": ["China taps financial tools to slow yuan’s surge against USD",
              "China rushes to pull back the yuan from a three-year high",
              "China Moves to Cool Yuan Rally With Fixing, Verbal Warnings",
              "How long will the yuan continue to rise before Beijing intervenes?",
              "China's banks are bursting with dollars, and that's a worry",
              "Russia To Ditch Dollar From $185Bln Reserve Fund",
              "Is U.S. Dollar At Risk Of Losing Reserve Currency Status?",
              "Multiple factors make exchange rate stable till year-end: experts",
              "Why do foreign banks expand in China despite weakening prfitability?",
              "China’s e-Yuan to race against the US dollar in market dominance"],
    "Sentiment Score": [-80, -70, -60, -50, -40, -30, -20, -10, 0,  20],
    "Importance Score": [0.250, 0.230, 0.210, 0.190, 0.170, 0.150, 0.130, 0.110, 0.090,  0.050]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Behold, North Korea has Asia's hottest currency",
              "American Pork Exports See Record Growth Due to Surging Demand in Asia-Pacific",
              "Iron ore price rises as China sees inflation 'under control' - MINING.COM",
              "EUR/USD Forecast: Euro-Dollar To Rise To 1.26 By End 2021 Say MUFG",
              "Can an underperforming Australian dollar help shift trade away from China?",
              "China Undercuts Efforts to Make the Renminbi an International Currency",
              "Dollar 'Should be Stable or go a Bit Higher Between Now and June 16': HSBC's Donnelly",
              "The 500-million-vehicle question: What will it take for China to decarbonize transport?",
              "US dollar and Chinese reminbi plummet against North Korean won once again - Daily NK English",
              "The Making of a G7 Summit"],
    "Sentiment Score": [100, 90, 80, 70, -100, -90, -80, -70, -60, -50],
    "Importance Score": [0.250, 0.225, 0.200, 0.175, 0.150, 0.125, 0.100, 0.075, 0.050, 0.025]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Central bank targets exchange rate stability - Chinadaily.com.cn",
              "Does the US-China trade war affect co-movements between US and Chinese stock markets?",
              "China's shadow bank crackdown is finally working",
              "Why China remains a springboard for electric vehicles",
              "PBOC sets USD/ CNY reference rate for today at 6.4546",
              "Rise of C-Derma (Chinese Derm Care) Beauty in China",
              "Hong Kong e-dollar study in spotlight as currency peg stays strong",
              "He Warned Apple About the Risks in China. Then They Became Reality.",
              "Citizens Anxious as Food Prices Fluctuate in North Korea",
              "Inside Chinese Developer Oceanwide's Wave of Trouble"],
    "Sentiment Score": [90, 80, 70, 60, 50, 40, -100, -90, -80, -70],
    "Importance Score": [0.200, 0.180, 0.160, 0.140, 0.120, 0.100, 0.080, 0.060, 0.040, 0.020]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix25
data = {
    "Topic": ["China Banks Stockpile Record $1 Trillion of Foreign Exchange",
              "2022 may be e-CNY's breakout - Chinadaily.com.cn",
              "Central bank targets exchange rate stability - Chinadaily.com.cn",
              "Exchange rate forecasted to touch Rs.205-215 against US dollar",
              "PBOC Instructs China's Banks to Forbid All Cryptocurrency Related Activities Immediately – Bitcoin News",
              "Why is Didi worth so much less than Uber?",
              "GBP/NZD Exchange Rate Dips as Confidence Grows in New Zealand Economy",
              "China's yuan at six-week low as rate outlook lifts dollar",
              "Food prices in North Korea soar; 1 kg of bananas costs $45 as borders remain closed",
              "Kenya leads others in providing financial inclusion"],
    "Sentiment Score": [90, 80, 70, 60, 50, 40, -100, -90, -80, -70],
    "Importance Score": [0.200, 0.180, 0.160, 0.140, 0.120, 0.100, 0.080, 0.060, 0.040, 0.020]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Central banks up reserves of RMB to a high",
              "Chart of the Day: Yuan Again Boosts Its Share of Global Forex Reserves to Record High",
              "What Will Be the Impact of China's State-Sponsored Digital Currency?",
              "China's role in amplifying Southern Africa's extreme uneven development",
              "Indonesia, China to reduce USD in bilateral trade​",
              "Power, Privacy and China's Digital Currency",
              "Most Americans Have 'Cold' Views of China. Here's What They Think About China, In Their Own Words",
              "Shenzhen skyscraper shakes up Chinese thinking on growth",
              "The Political Economy of the U.S.-China Technology War",
              "The New Cold War on China"],
    "Sentiment Score": [90, 80, 70, 60, 50, 40, -100, -90, -80, -70],
    "Importance Score": [0.200, 0.180, 0.160, 0.140, 0.120, 0.100, 0.080, 0.060, 0.040, 0.020]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix27
data = {
    "Topic": ["China's Foreign Currency Reserves Drop First Time in 3 Months",
              "Foreign currency deposits pass US$1 trillion, but why is this bad for China?",
              "Could the RMB Dislodge the Dollar As a Reserve Currency?",
              "China is cracking down on stocks that trade on U.S. exchanges. Here's what it means if you hold them",
              "U.S. IPO market a danger zone for Chinese firms after Beijing crackdown",
              "USD/CAD Exchange Rate Forecast – USD/CAD Rallies Breaking Out Ahead of FOMC Minutes",
              "North Korea Cracks Down on Counterfeiting, on the Rise as Economy Worsens",
              "China Energy Engineering takes part in EPC deal for big renewables hybrid",
              "How Didi’s data debacle doomed China’s love affair with Wall Street",
              "Unitree Robotics develops personal robot dogs that can jog with you"],
    "Sentiment Score": [-80, -70, -60, -50, -40, -30, -20, 10, 20, 30],
    "Importance Score": [0.200, 0.180, 0.160, 0.140, 0.120, 0.100, 0.080, 0.060, 0.040, 0.020]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Foreign travelers to China will be able to use the digital yuan, central bank says",
              "Four Reasons to Consider Increasing China Bond Exposure",
              "Understanding China's Latest RRR Cut - by Matthew C. Klein",
              "What the Crackdown on China's Big Tech Firms Is Really About",
              "China’s carbon-trading exchange kicks off en route nation’s 2060 goal",
              "China will benefit from internationalizing the RMB, including as a force to drive domestic financial sector reform",
              "COVID-19 and the Sri Lankan Economy | Economic and Political Weekly",
              "BTS V's Chinese fan club starts Taehyung's birthday celebration early by building a primary school under his name for ...",
              "Japan's current account balance with China: Is there a change in trend? | Japan Center for Economic Research",
              "Intel Core i9-12900K Alder Lake-S Qualification Samples available on black market for 1064 USD"],
    "Sentiment Score": [70, 60, 50, 40, 30, 20, -10, -20, -30, -40],
    "Importance Score": [0.200, 0.180, 0.160, 0.140, 0.120, 0.100, 0.080, 0.060, 0.040, 0.020]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["US resolves currency dispute with Vietnam",
              "Vietnam pledges not to devalue currency in agreement with U.S. Treasury",
              "A U.S. Exchange Rate Deal Positions Vietnam's Economy for Growth",
              "Vietnam, US Reach Accord on Alleged Currency Manipulation",
              "Vietnam Still Trolling Donald Trump With Economic Successes",
              "Trading Begins under China's National ETS",
              "China's global yuan push regains momentum",
              "The dollar, the yen, or the renminbi? Invoicing currency choices by Japanese overseas subsidiaries",
              "U.S. and Canada blame China for Microsoft Exchange hack earlier this year",
              "\"$60K is now more likely for Bitcoin than $20K, Bloomberg's senior strategist asserts\""],
    "Sentiment Score": [80, 70, 60, 50, 40, 30, 20, 10, -10, -20],
    "Importance Score": [0.200, 0.180, 0.160, 0.140, 0.120, 0.100, 0.080, 0.060, 0.040, 0.020]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the data
data = {
    "Topic": [
        "China’s capital controls: here to stay?",
        "Global renminbi role not now in China’s interest",
        "China's renminbi needs convertibility to internationalize",
        "U.S.-listed Chinese companies must disclose government interference risks -SEC official",
        "U.S. SEC says Chinese IPO hopefuls must provide additional risk disclosures",
        "Chinese yuan and Hong Kong dollar sell off as regulatory fears spread",
        "Tesla reduces Model 3 price in China",
        "China raises export tariffs for some steel products again in green push",
        "Lessons from 'two Nixon shocks' of 1971 still valid for Japan",
        "Gold Price Today: Yellow Metal Slides, Silver Also Down"
    ],
    "Sentiment Score": [-20, -30, 10, -40, 20, -50, 30, -60, 40, 50],
    "Importance Score": [0.234, 0.456, 0.789, 0.567, 0.123, 0.890, 0.345, 0.678, 0.912, 0.456]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    'Topic': ["U.S.-China Trade War: Origins, Timeline and Consequences",
              "China’s capital controls: here to stay?",
              "US-Vietnam Reach Agreement on Currency, No Tariffs Imposed",
              "Cambodia aims to wean off US dollar dependence with digital currency",
              "What is Currency Peg | Definition and Meaning",
              "Chinese yuan weakens to 6.4691 against US dollar Thursday — National Accord Newspaper",
              "Tesla reduces Model 3 price in China",
              "Naira sustains gain at black market as currency speculators record heavy losses",
              "U.S.-listed Chinese companies must disclose government interference risks -SEC official",
              "China threatens the West’s primacy, not its democratic systems"],
    'Sentiment Score': [-80, -70, -20, 30, 10, -40, 50, 20, -10, -60],
    'Importance Score': [0.764, 0.893, 0.632, 0.455, 0.321, 0.556, 0.234, 0.687, 0.512, 0.799]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data 32
data = {
    'Topic': ["U.S. dollar, yen rise after soft China data, amid Afghan unrest",
              "China NPC: Three-child policy formally passed into law",
              "U.S. and I.M.F. Apply a Financial Squeeze on the Taliban (Published 2021)",
              "A 50-year quest for monetary stability",
              "Cryptocurrency Companies Are Leaving China in 'Great Mining Migration'",
              "What will happen to Afghanistan’s economy under Taliban rule?",
              "The relative decline of US imperialism",
              "China’s Vaccine Diplomacy Stumbles in Southeast Asia",
              "China Is Bloodlessly Dominating the South Pacific",
              "Kris Wu Officially Arrested On Suspicion Of Rape In China"],
    'Sentiment Score': [-60, 30, -80, 10, -30, -50, -70, -50, -30, -90],
    'Importance Score': [0.871, 0.629, 0.958, 0.791, 0.512, 0.731, 0.987, 0.418, 0.815, 0.145]
}

# Create the dataframe
df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data
data = {
    'Topic': ["U.S. dollar, yen rise after soft China data, amid Afghan unrest",
              "China NPC: Three-child policy formally passed into law",
              "U.S. and I.M.F. Apply a Financial Squeeze on the Taliban (Published 2021)",
              "A 50-year quest for monetary stability",
              "How China Is Grabbing 'Our' Electric Market",
              "Cryptocurrency Companies Are Leaving China in 'Great Mining Migration'",
              "Blockchain in China • Stimson Center",
              "What will happen to Afghanistan’s economy under Taliban rule?",
              "The relative decline of US imperialism",
              "Myanmar tightens grip on forex rates to combat kyat slippage"],
    'Sentiment Score': [20, 70, -80, 40, -30, -60, -50, -40, -50, -70],
    'Importance Score': [0.831, 0.982, 0.225, 0.648, 0.419, 0.782, 0.561, 0.398, 0.718, 0.158]
}

# Create the dataframe
df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data
data = {
    'Topic': ["China's Digital Yuan: A Threat to Freedom | Cato at Liberty Blog",
              "Timeline of the US-China trade war since July 2018",
              "U.S. Accuses China of Hacking Microsoft",
              "EXCLUSIVE SEC gives Chinese companies new requirements for U.S. IPO disclosures",
              "U.S.-China Cancer Collaboration Could Open Door For New “Ping-Pong Diplomacy”: Kevin Rudd",
              "Understanding the real impact of the 'Nixon Shock'",
              "China reportedly weighs ban on U.S. IPOs from domestic tech companies with sensitive data",
              "Goal 2049: Modern, strong nation despite hurdles - Chinadaily.com.cn",
              "How Germany Can Prevent a Balkan Debt Trap | DGAP",
              "Thousands of Microsoft Customers May Have Been Victims of Hack Tied to China (Published 2021)"],
    'Sentiment Score': [-80, -60, -70, -50, -40, 40, -50, 20, -50, -70],
    'Importance Score': [0.658, 0.285, 0.176, 0.718, 0.398, 0.591, 0.451, 0.831, 0.708, 0.189]
}

# Create the dataframe
df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data
data = {
    'Topic': ["Benefits and Effects of China’s New Digital Currency Electronic Payment (DCEP) System",
              "What’s Happening in the World Economy: Fear Is Driving Global Currency Markets",
              "Chinese banks halting services amid investment risks, yuan volatility concerns",
              "B.C.-based Chinese currency exchange implodes amid tangle of lawsuits and failed transfers",
              "How to Buy Chinese Stocks Now That U.S.-Listed Shares Have Become Risky",
              "China's Severe COVID Lockdowns Come At A Serious Cost : Goats and Soda",
              "AUD/USD forecast: How low can the pair go before the next rebound?",
              "How Richard Nixon rocked the world 50 years ago with just the greenback and gold",
              "China, Pakistan, Iran: who can the Taliban count on?",
              "Russia's Gazprom Neft moves to yuan in fuelling planes in China"],
    'Sentiment Score': [70, -30, -60, -70, -80, -50, -30, 40, -60, -70],
    'Importance Score': [0.921, 0.671, 0.781, 0.815, 0.918, 0.599, 0.735, 0.871, 0.658, 0.802]
}

# Create the dataframe
df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data36
data = {
    'Topic': ["Assessing China's 'common prosperity' campaign",
              "The Real Cause of China's Alibaba Crackdown",
              "Asian currencies face headwinds from depreciation pressure on yuan",
              "China-Plus-One Strategy",
              "NIH Documents Provide New Evidence U.S. Funded Gain-of-Function Research in Wuhan",
              "China’s Yuan Set for Highest Close Since June",
              "Rethinking Of Bretton Woods - Looking Back To Address The Future",
              "El Salvador Accepts Bitcoin as Legal Tender",
              "Singapore’s diplomacy outreach on the US-China rivalry",
              "Contract Tobacco Farmers in Zimbabwe Say They Are ‘Drowning in Debt’"],
    'Sentiment Score': [-20, -80, -50, 20, -30, 70, 40, -80, -10, -60],
    'Importance Score': [0.821, 0.918, 0.705, 0.602, 0.837, 0.921, 0.875, 0.918, 0.785, 0.769]
}

# Create the dataframe
df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data
data = {
    'Topic': ["Policymakers can learn from Nixon's 'dollar shock'",
              "Is China already the world's most dominant economy?",
              "Exchange Stabilization Fund (ESF): Meaning, Creation, In Action",
              "Russia, China and EU are pushing towards de-dollarization: Will India follow?",
              "How China Avoided Soviet-Style Collapse - NOEMA",
              "U.S. freed from burden of high crude oil prices",
              "Next China: Xi Snubs Biden",
              "Pandora Aims to Double Its U.S. Business, Triple in China",
              "China calls on US to 'stop official exchanges' with Taiwan",
              "Soho China’s Shares Plummet After Blackstone Abandons $3 Billion Takeover"],
    'Sentiment Score': [60, 80, 50, 30, 70, 60, -40, 70, -30, -50],
    'Importance Score': [0.801, 0.924, 0.702, 0.635, 0.819, 0.777, 0.512, 0.825, 0.676, 0.584]
}

# Create the dataframe
df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data
data = {
    'Topic': ["U.S. Is Losing the Global Race on Digital Currency | TIME",
              "Digital yuan could come to overseas users to challenge dollar dominance: policy bank expert",
              "Central bank sync puts foreign exchange market to sleep",
              "China drafts new rules on overseas yuan lending to boost use",
              "China's Stock Markets - An Introductory Guide for Foreign Investors",
              "Myanmar's Currency Falls to All-Time Low Amid Post-Coup Turmoil",
              "From the margins: CGBs vie to join the collateral club",
              "CDR – The Belt and Road Initiative | Singapore | CDR Magazine",
              "Evergrande's place in China's house of cards",
              "China declares all crypto-currency transactions illegal"],
    'Sentiment Score': [-30, 60, 0, 50, 70, -50, 40, 20, -30, -80],
    'Importance Score': [0.643, 0.856, 0.512, 0.759, 0.924, 0.475, 0.689, 0.548, 0.632, 0.381]
}

# Create the dataframe
df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data39
data = {
    'Topic': ["Bitcoin Stalls as U.S., China Go After Cryptocurrencies",
              "5 Ways US Debt Default Would Echo Through Global Economy",
              "China's answer to crypto is the digital yuan",
              "U.S. needs to work with Europe to slow China's innovation rate, Raimondo says",
              "American Siblings Barred From Leaving China for 3 Years Return to U.S. (Published 2021)",
              "China's Shanghai gas exchange launches spot pricing for imported LNG",
              "US Dollar Status as Dominant 'Global Reserve Currency' amid Reckless QE & Government Deficits",
              "Many Exchanges in China Continue to Operate OTC Desks Despite 'Ban'",
              "Countries Have $385 Billion In 'Hidden Debts' To China, Study Finds",
              "Venezuela Changes Currency as Inflation Skyrockets, Price of Dollar Rises"],
    'Sentiment Score': [-60, -50, 70, -40, 20, 30, 10, 40, -30, 10],
    'Importance Score': [0.752, 0.611, 0.924, 0.587, 0.368, 0.452, 0.526, 0.678, 0.409, 0.562]
}

# Create the dataframe
df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data
data = {
    'Topic': ["The International Role of the U.S. Dollar",
              "An Update on the U.S.–China Phase One Trade Deal - Liberty Street Economics",
              "Debating defence budgets: Why military purchasing power parity matters",
              "The Truth About Tariffs",
              "5 Things U.S. Policymakers Must Understand About China-Africa Relations",
              "Cost of shipping between China and U.S. plunges",
              "To Get Back Arrested Executive, China Uses a Hardball Tactic: Seizing Foreigners (Published 2021)",
              "General Motors to Outline Plans for Decade of Growth, Doubling of Annual Revenues by 2030 with Increased Margins",
              "U.S. Won't Follow China in Banning Crypto, SEC Chief Says",
              "KraneShares China Innovation ETF | KGRO"],
    'Sentiment Score': [40, 20, 10, 30, 20, 20, 40, 50, 60, 50],
    'Importance Score': [0.723, 0.615, 0.589, 0.682, 0.511, 0.456, 0.723, 0.821, 0.635, 0.722]
}

# Create the dataframe
df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix41
data = {
    "Topic": ["Chinese yuan gains value against USD during pandemic",
              "North Korea's currency surges against USD despite sanctions",
              "Debt politics impact U.S. creditworthiness",
              "China's expanding influence in Europe",
              "Strong dollar squeezes energy-poor countries",
              "China's economic slowdown affects global economy",
              "Denial of Chinese role in Iranian housing plans",
              "China's rising exports affect U.S. dependency",
              "U.S. dominance in Bitcoin mining post-China crackdown",
              "Central Asians push Chinese firms to localize operations"],
    "Sentiment Score": [80, -60, -70, 20, -40, -20, 0, 30, 10, 50],
    "Importance Score": [1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100]
}

# Create DataFrame
df = pd.DataFrame(data)

# Print DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    'Topic': ["China's yuan facing challenges despite gains against the US dollar",
              "China's currency regulator confident in handling shocks from US tapering",
              "Yuan sees biggest jump since January, raising concerns over China's currency fixing",
              "Rivalry between the US and China and its impact on currency dynamics",
              "Modern Monetary Theory challenges traditional views on currency management",
              "China's ban on cryptocurrency transactions and its implications for the yuan",
              "Slowing Chinese economic growth and its effect on the yuan-dollar exchange rate",
              "Introduction of Central Bank Digital Currency (CBDC) and its potential impact on yuan's value",
              "Neocolonialism and IMF's role in currency stability and development",
              "Luckin Coffee's strategy to increase revenue and stem losses amidst currency fluctuations"],
    'Sentiment Score': [10, 50, -30, 10, 20, -80, -30, 20, -10, 30],
    'Importance Score': [0.750, 0.900, 0.500, 0.600, 0.550, 0.950, 0.600, 0.700, 0.300, 0.850]
}

df = pd.DataFrame(data)

print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["China's booming exports sustain yuan's rally",
              "Mystery surrounding Chinese defense spending",
              "China's dominance in biopharma innovation",
              "China's digital channels reshape consumer engagement",
              "Impact of U.S.-China relations on solar industry in Xinjiang",
              "Impact of inflationary pressures on global currencies",
              "Tesla's significant sales growth in China",
              "Tax system disparities in China favoring the wealthy",
              "Impact of currency movements on agriculture and food trade",
              "Pakistan's interest payment to China under currency swap"],
    "Sentiment Score": [70, -60, 50, 40, -30, 20, 60, -20, 10, -40],
    "Importance Score": [0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550, 0.500, 0.450, 0.400]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

# Export DataFrame to CSV
df.to_csv('parity_analysis.csv', index=False)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": ["Yuan's potential weakening in 2022",
              "PBoC interventions in offshore renminbi",
              "China's media propaganda against the West",
              "Promotion of RMB for reducing exchange volatility",
              "Growth of China's ABS market",
              "Social media influence on financial markets",
              "Evaluation of China's stock market performance",
              "China's integration in global trade organizations",
              "Advantages of using Renminbi for international payments",
              "Container rates reduction on China-US trade route"],
    "Sentiment Score": [-80, -30, -40, 60, 70, -20, 0, 0, 50, 40],
    "Importance Score": [0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550, 0.500, 0.450]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

# Export DataFrame to CSV
df.to_csv('parity_analysis.csv', index=False)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": ["China's Foreign Exchange Reserves",
              "US-China Trade War",
              "Chinese Government Monetary Policy",
              "Economic Growth Disparities between US and China",
              "Renminbi Internationalization Efforts",
              "Market Sentiment towards Renminbi",
              "Geopolitical Tensions Impacting Currency Markets",
              "Impact of US Federal Reserve Policy on Renminbi",
              "Currency Manipulation Allegations",
              "Tech Innovation Influence on Renminbi Performance"],
    "Sentiment Score": [-70, -80, -60, -50, 60, 40, -30, -20, -40, 50],
    "Importance Score": [0.932, 0.891, 0.854, 0.812, 0.773, 0.736, 0.702, 0.671, 0.642, 0.615]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

# Export DataFrame to CSV
df.to_csv('parity_analysis.csv', index=False)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": ["China's Foreign Exchange Reserves",
              "US-China Trade Relations",
              "Chinese Government Monetary Policy",
              "Economic Impact of CNY/USD Exchange Rate",
              "Renminbi Internationalization Efforts",
              "Market Sentiment towards CNY/USD Exchange Rate",
              "Geopolitical Tensions and Currency Markets",
              "Impact of US Federal Reserve Policies on CNY/USD",
              "Allegations of Currency Manipulation",
              "Technological Innovation and CNY/USD Performance"],
    "Sentiment Score": [-70, -80, -60, -50, 60, 40, -30, -20, -40, 50],
    "Importance Score": [0.921, 0.883, 0.845, 0.807, 0.772, 0.738, 0.705, 0.674, 0.645, 0.617]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

# Export DataFrame to CSV
df.to_csv('parity_analysis.csv', index=False)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data47
data = {
    "Topic": ["Impact of US-China Tariff War on China's Economy",
              "Need for China-US Cooperation on Climate Change",
              "RBI Shifts Focus to Chinese Yuan",
              "Financial Stress in China",
              "Latin America Economic Outlook",
              "Yuan as Benchmark for Rupee",
              "Global Equity Market Outlook",
              "US Market Trends for Scan Tools",
              "Food Inflation in Nigeria",
              "Impact of US-China Tariff War on China's Economy"],
    "Sentiment Score": [-80, -70, -60, -50, 40, 50, -30, -20, -40, 60],
    "Importance Score": [0.945, 0.917, 0.890, 0.862, 0.835, 0.808, 0.781, 0.754, 0.727, 0.700]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

# Export DataFrame to CSV
df.to_csv('unique_scores_parity_analysis.csv', index=False)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "China's warning of yuan speculation risks",
        "Yellen suggests tariff reduction to ease price pressure",
        "China's growing role in rising US inflation",
        "China's payments system evolution",
        "Turkey's lira depreciation and worsening crisis",
        "Didi's delisting from NYSE and China's influence",
        "Philippines-China maritime tensions",
        "China's semiconductor industry rise",
        "Vietnam and Taiwan's currency thresholds",
        "Impact of exchange rates on imported items"
    ],
    "Sentiment Score": [
        -90, -80, -70, -60, -50, -40, 30, 40, 50, 60
    ],
    "Importance Score": [
        0.987, 0.932, 0.876, 0.820, 0.764, 0.708, 0.651, 0.595, 0.539, 0.483
    ]
}

df = pd.DataFrame(data)

# Print the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the data
data = {
    'Topic': ["China ups forex deposit reserve requirement ratio in bid to curb yuan rally",
              "China's currency is having an even better year than the US dollar. Here's why",
              "Foreign Ministry Spokesperson Zhao Lijian's Regular Press Conference on December 6, 2021",
              "China's Yuan Highest Since 2018 as Easing Covid Worry Fuels Risk-On",
              "Will the renminbi surprise the market?",
              "China’s yuan strengthens as trade surplus hits US$72 billion in November",
              "Didi is delisting in New York. Here's what happens if you own a delisted stock",
              "China joined rules-based trading system — then broke the rules",
              "U.S.-listed Chinese firms with secondary listings at home and Hong Kong",
              "Here's How Reserve Currencies Have Evolved Over 120 Years"],
    'Sentiment Score': [-80, 70, -60, 60, -40, 50, -20, -10, 30, 40],
    'Importance Score': [0.967, 0.913, 0.859, 0.805, 0.752, 0.698, 0.644, 0.590, 0.536, 0.483]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data50
data = {
    "Topic": ["US inflation is driving dollar-yuan exchange rate",
              "What’s needed two decades on from China’s accession to the WTO",
              "Will the Dual Circulation Strategy Enable China to Compete in a Post-Pandemic World?",
              "China and Russia to create financial system not influenced by ‘third parties’",
              "Global Debt Reaches a Record $226 Trillion",
              "It's 'game over' for U.S.-listed Chinese companies, global asset manager says",
              "Stay, swap or shed: Investors brace for delisting of U.S.-listed China stocks",
              "How the Chinese Fast Fashion Brand Shein is Conquering the…",
              "China overtakes U.S. in national net worth to grab top spot",
              "China’s SenseTime Postpones I.P.O. After U.S. Sanctions"],
    "Sentiment Score": [-80, -50, 60, 70, -30, -10, 40, 50, 30, 20],
    "Importance Score": [0.917, 0.869, 0.823, 0.776, 0.729, 0.682, 0.636, 0.589, 0.542, 0.494]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["China to stem yuan rise amid ‘uncertainties, instability and imbalance’",
              "U.S.-China technology competition | Brookings",
              "Why China could win the new global arms race",
              "Import-Export Taxes and Duties in China in 2022",
              "How Argentina Pushed Chinese Investors to Help Revitalize Its Energy Grid",
              "Chinese exchange rate seeking a catalyst",
              "The Future of the Sino-Venezuelan Relationship: Make or Break?",
              "From Surging Recovery to Elegant Advance: The Evolving Future of Luxury",
              "Global Markets in 2021: Recoveries, reflation and wrecking balls",
              "Business environment risk: Upgrades continue to prevail while the economic outlook requires caution"
             ],
    "Sentiment Score": [-80, -20, -50, 10, 40, -70, 30, 60, 70, 80],
    "Importance Score": [0.900, 0.858, 0.816, 0.774, 0.732, 0.689, 0.647, 0.605, 0.563, 0.520]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the topic, sentiment score, and importance score
data = {
    "Topic": [
        "China’s top-performing yuan posts second straight year of gains against US dollar",
        "China's yuan looks set for second year of gains in 2021, rises 2.5%",
        "US Dollar’s Status as Dominant “Global Reserve Currency” at 25-Year Low. And USD Exchange Rates?",
        "Chinese exchange rate seeking a catalyst",
        "Central banks accelerate shift from dollar to gold worldwide",
        "China–Myanmar Border Opens for Limited Trade, Yuan Formally Recognized",
        "Yuan’s current strength to reverse in 2022: Fitch",
        "All About China",
        "The Doctors Are In: Cancer Experts Try To Boost Ailing U.S.-China Relations",
        "Emerging markets seen rising in 2022, but not until July"
    ],
    "Sentiment Score": [
        85, 80, -90, -60, 70, 75, -70, 50, 45, 40
    ],
    "Importance Score": [
        0.950, 0.905, 0.860, 0.815, 0.770, 0.725, 0.680, 0.635, 0.590, 0.545
    ]
}

# Create the dataframe
df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

len(bound)

bound=pd.DataFrame(bound)
bound.to_csv('cnyusdscore2021.csv')

raw_data.to_csv('cnyusdrawdata2021.csv')