# -*- coding: utf-8 -*-
"""cnyusd2020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ypPug9X_Y1wxyOcY9CpeF1FpPg6-VmhE
"""

from sklearn.preprocessing import MinMaxScaler
import numpy as np

def weekly_score(df):
  transfer=MinMaxScaler(feature_range=(0.1,0.5))
  df_1=np.array(df.iloc[:,2]).reshape(-1, 1)
  df_1=transfer.fit_transform(df_1)
  d=np.array(df.iloc[:,1])*df_1.reshape(1, -1)
  upper=int(sum(np.maximum(d,0).T))
  lower=int(sum(np.minimum(d,0).T))
  return upper,lower

bound=[]
raw_data=[]

import pandas as pd

data = {
    "Topic": ["US-China Trade War Impact on Stock Market",
              "China's Economic Performance and Foreign Exchange Reserves",
              "China's Response to US Carbon Tariffs",
              "World Bank's Outlook on US-China Trade Tensions",
              "US-China Trade Deal and President Trump's Role",
              "Global Outlook on US Dollar Dominance",
              "Forecast for Currency Performance in 2020",
              "Gold Prices Surge Amid US-Iran Tensions",
              "Australian Dollar's Performance Amid US-China Trade Talks",
              "Monetary Policy's Impact on Economic Growth"],
    "Sentiment Score": [-60, 70, 60, -50, 80, 70, 50, 60, 40, 50],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["US-China Trade Deal Signing and Currency Manipulator Label Removal",
              "Impact of US-China Trade Deal on Renminbi",
              "Renminbi Rebound Amid US-China Trade Tensions",
              "US-China Phase One Trade Deal Provisions",
              "US-China Trade War's Impact on Currency Markets",
              "Yen Weakening Amid US-China Trade Optimism",
              "China's Economic Performance and Middle-Class Concerns",
              "China's Per Capita GDP Exceeds $10,000",
              "US Dollar Exchange Rate Stability Amid US-China Trade Talks",
              "Pound's Response to US-China Trade Deal and Market Sentiment"],
    "Sentiment Score": [80, 60, 70, 50, -40, -30, -20, 40, 30, 20],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#3
data = {
    "Topic": ["Impact of Wuhan Virus on Yuan and Recent Gains",
              "Global Economic Outlook and Yuan Stability",
              "US Dollar as the Most Traded Currency Globally",
              "Zimbabwe-China Currency Swap Deal and its Implications",
              "China's Rise as the Major Trading Partner vs. the US",
              "Concerns over China's Economy Amid Trade War and Virus Outbreak",
              "US-China Phase One Trade Deal and Trump's Remarks on Relationship",
              "Vietnam's Economic Growth amid US-China Trade War",
              "Euro-to-Dollar Rate Weakness and Short-Term Expectations",
              "Rupee's Performance Amid Economic Slowdown and Inflation"],
    "Sentiment Score": [-70, 60, 50, -40, 30, -60, 40, 20, -10, -20],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)

#4
import pandas as pd

data = {
    "Topic": ["Impact of Coronavirus Outbreak on Chinese Yuan",
              "Yuan Breaching Critical Level of 7 to the Dollar",
              "China's Yuan Tumble and Potential Disruption",
              "Phase One Trade Deal Lessons and China's Import Promises",
              "Potential Digital Currency Breakthrough and Japanese Admission",
              "China's Response to Libra and Digital Currency Fast-Tracking",
              "Vietnam's Economic Squeeze Amid US-China Trade War",
              "Concerns Over Wuhan Coronavirus's Global and Economic Impacts",
              "Counterfeit $1 Notes Seized in the US, Originating from China",
              "China's Economic Stimulus Amid Coronavirus Growth Fears"],
    "Sentiment Score": [-70, -50, -60, 40, 30, 20, -40, -70, -30, 50],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#5
data = {
    "Topic": ["US-China Trade War Truce and Phase One Deal Skepticism",
              "US Department of Commerce Rule to Investigate Currency Undervaluation",
              "China's Thousand Talents Program and Alleged Intellectual Property Theft",
              "China's Emphasis on Innovation and Technology for Economic Growth",
              "US Commerce Department's Anti-Dumping and Countervailing Duty Rules",
              "Global Trends in Luxury Goods and Changing Consumer Behavior",
              "Corporate Debt Refinancing and Global Credit Trends",
              "India and Australia's Economic and Political Roles",
              "Gulf Economies Considering Rethinking Dollar Peg",
              "Mongolia's Border Closure Impacting Yuan Exchange Rate"],
    "Sentiment Score": [-80, -60, -70, 60, -40, 50, 40, 20, 30, -30],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Globalization of the Renminbi (RMB) and China's Currency Swaps",
              "Impact of Coronavirus on Asia-Pacific Currencies",
              "African Countries' Preference for Strong Currencies",
              "Trade Instability and Manufacturing Strategies",
              "Euro's Decline Reflecting Political Turmoil and Economic Woes",
              "Chinese New Year's Effect on Markets",
              "People's Bank of China's (PBOC) Plans for Digital Currency",
              "Emerging Markets and Recent Market Volatility",
              "Potential Yuan Devaluation Due to Coronavirus",
              "External Debt Sustainability in Kazakhstan"],
    "Sentiment Score": [70, -80, 60, -50, -70, 40, 50, -30, -60, 20],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

#7
import pandas as pd

data = {
    "Topic": ["Impact of Coronavirus on Latin American Economies",
              "China's A-Share Market Performance Amidst Coronavirus Concerns",
              "Rising Housing Markets in China and Eastern Europe",
              "Singapore Dollar's Vulnerability Due to Coronavirus",
              "Accusations Against the U.S. Regarding HSBC and Huawei",
              "China's Economic Recovery and Stimulus Measures",
              "Euro's Continued Decline and Potential for Further Falls",
              "Investment Opportunities in China's Economy",
              "Exchange Rate Impact on Mining Salaries",
              "Australia's Position as the Most Valuable Beef Exporter"],
    "Sentiment Score": [-80, 70, 60, -50, -70, 40, -30, 50, -60, 20],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["China's Role in International Finance and Debt Owed to China",
              "Impact of Coronavirus on Global Economy and Currency Markets",
              "US-China Business Outlook and Trade Relations",
              "Global Dollar Short Squeeze and its Effects",
              "China's Economic Relations with Morocco",
              "US Trade Deficit and Broken Promises",
              "Bitcoin and Ethereum Mining Power Concentration in China",
              "Japanese Firms' International Operations Survey",
              "Australian Dollar's Weakening and Coronavirus Impact",
              "Euro's Exchange Rate Trends and Italian Contagion"],
    "Sentiment Score": [70, -80, 60, -70, 50, -60, 40, -50, -30, 20],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#9
data = {
    "Topic": ["US-China Phase One Trade Deal Implementation and Impact",
              "Economic Effects of COVID-19 on China and Global Trade",
              "US Exclusions of Chinese Medical Products from Tariffs",
              "Coronavirus Impact on China's Economy",
              "Economic Impact of Coronavirus in the US and Policy Responses",
              "Currency Exchange Rate Stability Amid Coronavirus Fears",
              "Global Retail Trends and Market Dynamics",
              "Iran's Response to Coronavirus Outbreak",
              "Ghana's Currency Performance Amid COVID-19",
              "Financial Challenges Faced by Chinese Conglomerate Wanda Group"],
    "Sentiment Score": [70, -80, 60, -70, 50, -60, 40, -50, -30, 20],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

#10
import pandas as pd

data = {
    "Topic": ["China's Reopening to US LPG Imports",
              "Impact of US-China Trade Deal Tariffs on Retailers",
              "US Exclusions of Certain Chinese Medical Products from Tariffs",
              "Valuations in Chinese M&A Transactions",
              "ECB's March 2020 Macroeconomic Projections for Euro Area",
              "Economic Impact of COVID-19 on India",
              "Challenges Faced by a Central Bank with No Capital Markets",
              "Impact of Brexit on Global Textile Industry",
              "Forecasts and Analyst Outlook on Euro to Dollar Exchange Rate",
              "Considerations for Prepaid Travel Cards Amid Currency Fluctuations"],
    "Sentiment Score": [70, -60, 50, -30, 40, -20, 10, -40, 20, -10],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["China's Digital Yuan and Its Economic Impact",
              "Global Leadership Maneuvering Amidst Coronavirus Crisis",
              "Financial Stability Amidst COVID-19 Pandemic",
              "Stability of RMB Exchange Rate with USD",
              "US-China Trade Dynamics and Conspiracies",
              "Need for Fed-PBoC Swap Line",
              "Global Rush for USD and Dollar Shortage",
              "Government Actions on Banknotes Amid Coronavirus",
              "Currency Swap Between BOK and US Fed",
              "Global Cost of Living and Currency Strength"],
    "Sentiment Score": [70, 60, 50, 40, -30, -40, -50, -20, -10, -5],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Impact of Oil Price War on China",
              "China's Ability to Play the 'Carry Game'",
              "Disappearance of 'Made in China 2025' Initiative",
              "Analysis of China's Defense Spending",
              "Effects of Coronavirus on China's Economy",
              "US Support of Taiwan and Its Implications",
              "Need for American Belt and Road Initiative",
              "Chinese Investment in Syria",
              "Sell-off in Chinese Stocks and Its Temporariness",
              "US Tariffs on Chinese Imports"],
    "Sentiment Score": [-60, -40, -50, -30, -20, -10, 40, 50, 60, 70],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["China's Digital Yuan and Its Implications for Economic Warfare",
              "China's Strategic Maneuvering for Global Leadership",
              "Central Banks' Response to Financial Collapse",
              "Stability of the RMB Exchange Rate Against the US Dollar",
              "Conspiracy Theories Regarding COVID-19's Impact on China's Economy",
              "Case for a Fed-PBoC Swap Line and Dollar Funding Challenges",
              "Potential Reformation of US Foreign Policy under Biden",
              "Global Rush for Dollars and Its Impact on Foreign Exchange Markets",
              "Efforts to Address the Global Dollar Shortage",
              "Currency Swap Agreements Between Central Banks"],
    "Sentiment Score": [80, 70, -60, 40, -20, -30, 50, -40, 20, 10],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Strategic Rivalry Between United States and China",
              "China's COVID-19 Information Sharing and International Cooperation",
              "Impact of COVID-19 on Chinese Workers in the US",
              "Post-Pandemic Scenarios for China's Belt and Road Initiative",
              "COVID-19's Threat to Latin America's Small Businesses",
              "Huawei's Funding and US Government Claims",
              "China's Rise in Science and Technology and the Associated Criticism",
              "Coronavirus Pandemic's Impact on the Mexican Economy",
              "Effects of Fed Easing on the US Dollar in the Long Run",
              "Rupee's Record Low Against US Dollar and Recovery"],
    "Sentiment Score": [80, 70, -60, 40, -20, -30, 50, -40, 20, 10],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#15
data = {
    "Topic": ["China's Rise in Finance Amid Dollar Dominance",
              "Lebanon's Order for Money Transfer Services to be Paid in Local Currency",
              "Impact of COVID-19 on Global Economy and Currency Values",
              "Analysis of Asian Banks Amid Economic Slowdown",
              "Impact of Coronavirus Pandemic on Nepalese Economy",
              "Trump Administration's Tensions and Their Effects on Financial Markets",
              "India's Dollar Swap Line with the US Fed and Its Implications",
              "Impact of Chinese Data on the New Zealand Dollar Exchange Rate",
              "Global Stock Market Trading Hours and Their Influence on Currency Markets",
              "Role of International Financial Institutions in Economic Stability"],
    "Sentiment Score": [70, -60, -20, 40, -30, -50, 60, 20, 10, 50],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["China's Digital Currency Initiatives and Potential Challenge to the Dollar",
              "Impact of Coronavirus Pandemic on Global Debt and Economic Strategies",
              "Chinese Financial Innovations Amidst the COVID-19 Crisis",
              "US-China Economic Relations Amid Dollar Dominance",
              "Role of Digital Currencies in Post-Pandemic Economic Recovery",
              "American Dependency on Chinese Products and Economic Implications",
              "Expert Views on the Significance of Digital Currencies for Global Finance",
              "China's Transition Towards a Cashless Society",
              "Geopolitical Implications of China's Economic Influence",
              "US Dollar Strength and its Impact on Global Financial Markets"],
    "Sentiment Score": [80, -40, 50, -30, 60, -70, 40, 70, 20, -50],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#17
data = {
    "Topic": ["First USD/CNY Cross-Currency Swap using SOFR",
              "Class Politics of the Dollar System",
              "China's Metals Stockpiling Programs",
              "Comparison of US and China Responses to COVID-19",
              "US Dependency on Chinese Products",
              "Global Crop Protection Market Trends",
              "Russia's Military Spending and its Implications",
              "Scandal Impacting Chinese Coffee Chains",
              "Market Gap between Emerging and Developed Economies",
              "Potential Greater Depression of the 2020s"],
    "Sentiment Score": [80, -40, 60, -20, -70, 30, -10, -50, 10, -30],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["U.S. Dollar Dominance Amid COVID-19 Pandemic",
              "China's Response to Dollar Peg in Stock Exchange Transactions",
              "Impact of Tariffs on Import and Export Price Indexes",
              "Shift towards Yuan-Denominated Bonds Amid Pandemic",
              "Changing Relationship between Trade and Gold Reserves",
              "US-China Trade Tensions during COVID-19",
              "Comparison of COVID-19 and 2008 Financial Crises",
              "Remaining Tariffs on U.S.-China Trade",
              "Effect of Trade Tensions on Gold Prices",
              "Bilateral Payments Dynamics between China and UAE"],
    "Sentiment Score": [80, -60, 40, -20, 70, -50, 30, -40, -30, 10],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#19
data = {
    "Topic": ["Trump's Threats to China Over Coronavirus",
              "Yuan-Denominated Iron Ore Sale to China",
              "US-China Rivalry Post-COVID-19",
              "Introduction of China's Sovereign Digital Currency",
              "Effect of U.S. Imports on Manufacturing Employment",
              "North Korea Bans Use of Foreign Currency",
              "China Pursuing UN Dues from the US",
              "China's Central Bank Leading in CBDC Development",
              "Nigeria's Foreign Exchange Shortage Amid Oil Price Collapse",
              "Impact of US-China Exchange on Australian Dollar"],
    "Sentiment Score": [-80, 60, -50, 40, -30, -20, -10, 20, -70, -40],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["China's Digital Currency Proposal for Trade",
              "Impact of Trump's Trade Deal with China",
              "US Dollar Demand Spurred by Trump's Statements",
              "Stablecoin Currency Proposal for HK, China, Korea, Japan",
              "Bipartisan Support for Delisting Chinese Stocks",
              "Rising Tensions between China and the US",
              "Impact of China's Debt on Global Financial Markets",
              "Chinese Investment Impact on Pakistan",
              "Alibaba's Financial Performance Announcement",
              "Chinese Students' Second Thoughts on Studying in the US"],
    "Sentiment Score": [60, -40, -70, 30, -20, -50, -30, -10, 20, -80],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#21
data = {
    "Topic": ["China's Use of Digital Currency to Compete with the USD",
              "China's Embrace of a Weaker Currency Amid Economic Slowdown",
              "Efforts to Stabilize Yuan Amid Tumbles and US-China Tensions",
              "Impact of US-China Tensions on Hong Kong's US Dollar Peg",
              "Speculation on Yuan/Dollar Exchange Rate Amid Higher US-China Tensions",
              "Complexity of US-China Economic Relationship and Decoupling",
              "Comparison of China and the US as Financial and Economic Powers",
              "Impact of Illicit Currency Trade on Lebanon's Economy",
              "Effects of Losing Special Status on Hong Kong's Economy",
              "Implications of China's Digital Currency on the Supremacy of the US Dollar"],
    "Sentiment Score": [80, -50, -20, -30, -40, -10, 20, -70, -30, 60],
    "Importance Score": [0.900, 0.825, 0.750, 0.675, 0.600, 0.525, 0.450, 0.375, 0.300, 0.225]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["US-China Relations and Trade War",
              "Hong Kong's Role in US-China Relations",
              "China's Digital Currency and its Impact on USD",
              "Geopolitical Tensions and Flashpoints",
              "US Policies and Sanctions on China",
              "Impact of US Protests on US-China Relations",
              "China's Economic Growth and Technological Advancements",
              "Global Perception of China's Leadership",
              "Impact of Pandemic on China's Economy",
              "US-China Military Tensions and Strategic Moves"],
    "Sentiment Score": [-70, -60, 60, -50, -80, -40, 70, 50, -30, -60],
    "Importance Score": [0.9, 0.85, 0.95, 0.85, 0.9, 0.8, 0.85, 0.75, 0.7, 0.8]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#23
# Create the matrix
data = {
    "Topic": ["US-China Trade Tensions and Impact on Currency Markets",
              "US Dollar Dominance and International Trade",
              "Chinese Companies' Listing Plans and US-China Relations",
              "Global Economic Contraction and its Effects on Exchange Rates",
              "Geopolitical Tensions and Currency Speculation in Hong Kong",
              "Rumors Surrounding Chinese Central Bank's Gold Reserves",
              "Impact of US Legislation on Chinese Companies' Delistings",
              "Currency Market Volatility Amidst COVID-19 Pandemic",
              "Investment Opportunities and Forex Trading Tips",
              "Potential Economic Stimulus Measures by Chinese Authorities"],
    "Sentiment Score": [-80, 60, -70, -60, -50, 40, -30, -20, 30, 50],
    "Importance Score": [1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Turkey's Use of Chinese Yuan for Import Payment",
              "Cambodia-China Rice Trade in Local Currencies",
              "China's Residential Property Sector",
              "China's Strategic Financial Market Opening",
              "Impact of US Financial Warfare in the Middle East",
              "Japan's Triple Economic Shock",
              "Rice Deals in Riel and Yuan between Cambodia and China",
              "China's Role as the Largest Foreign Exchange Reserve Holder",
              "China's Influence on Indian Funding Options",
              "South African Rand Troubled by Resurgent Dollar"],
    "Sentiment Score": [70, 60, 50, 40, -70, -60, 30, 20, -50, -40],
    "Importance Score": [1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Impact of U.S.-China Trade War on Global Supply Chains",
              "Lebanese Currency Crisis and Dollar Shortage",
              "Benefits of U.S.-China Relationship Amidst Pandemic",
              "India's Protectionist Policies and Export Ambitions",
              "Palm Oil Market Trends in China",
              "Blockchain and Fintech Developments in China",
              "Medical Instrument Sales in China and Market Billionaires",
              "COVID-19 Effects on China's Trade and Agrochemical Prices",
              "Gold Prices and Dollar Performance",
              "Long-term Impact of COVID-19 on Exchange Rates"],
    "Sentiment Score": [-70, -80, 50, -60, 30, 20, 40, -50, 60, -30],
    "Importance Score": [1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Impact of U.S. Missile Defense on China",
              "Effect of Zero Interest Rates on Currency Volatility",
              "NAFTA and USMCA Restructuring",
              "COVID-19 Accelerating China-US Convergence",
              "Resilience of Global Supply Chains",
              "Entrepreneurship in US-China Tech Businesses",
              "China's Strategic Headache from Wooing Companies",
              "Rupee Movement Predictions by Currency Traders",
              "US Dollar Performance and Global Investor Sentiment",
              "Naira Appreciation and Central Bank Policy"],
    "Sentiment Score": [-70, -50, -30, -60, 20, 40, 60, 30, 50, -40],
    "Importance Score": [1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

#27
import pandas as pd

# Create the matrix
data = {
    "Topic": ["Impact of China's Economic Recovery on Currency Strength",
              "China-Iran Trade and Military Partnership Defiance",
              "Proposals to Undermine Hong Kong Dollar Peg by Trump Admin",
              "Uncertainty Surrounding China's Support for US Dollar",
              "China's Role in Lebanon's Economic Crisis",
              "Opportunities in Chinese Corporate Bond Market",
              "Scandal Involving Fake Gold Bars and Loan Scams in China",
              "Gold Market Trends Amid China's Economic Revival",
              "Effects of COVID-19 on Exchange Rate Management",
              "Impact of U.S. Dollar Strength on Global Markets"],
    "Sentiment Score": [80, -70, -60, -50, -30, 20, -40, 30, -50, 40],
    "Importance Score": [1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Weakening of Chinese Yuan Against US Dollar",
              "Impact of China's Economy on Currency Strength",
              "Lessons from Eurodollar Market for Hong Kong Renminbi",
              "US Efforts to Contain China and its Impact on Currency",
              "Hong Kong-US Dollar Peg Mechanism and Stability",
              "US Dollar as Safe-Haven Asset and its Influence on Currency",
              "Vulnerability of Hong Kong Dollar Against US Dollar",
              "Threats to Hong Kong Dollar Peg by Trump Administration",
              "China's Economic Size Compared to World Bank Estimates",
              "Significance of Hong Kong Dollar Peg and its Maintenance"],
    "Sentiment Score": [-80, 60, 40, -90, 50, 70, -70, -90, 30, 80],
    "Importance Score": [1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Impact of Hong Kong Autonomy Issue on Exchange Rate",
              "China's Strategy to Maintain Foreign-Investment Flows",
              "Importance of Hong Kong's Role in Global Financial Market",
              "Need for Institutional Reform in China's Economy",
              "Renewal of China-Argentina Currency Swap",
              "Hope for Improved US-China Relations",
              "Enhanced Cross-Border Financial Services in Greater Bay Area",
              "Cuba's Decision to Eliminate Surcharge on Dollar Exchange",
              "Increased Demand for D&O Insurance in Chinese Corporates",
              "Prevalence of US Dollar and its Impact on Developing Economies"],
    "Sentiment Score": [-60, 70, 80, 20, 50, 60, 70, 50, 60, -70],
    "Importance Score": [1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#30
# Create the matrix
data = {
    "Topic": ["Weakening of Chinese Yuan Against USD",
              "Chinese Banks Urged to Reduce Dependence on SWIFT",
              "Impact of US-China Trade War on American Competitiveness",
              "Weakness of US Dollar and its Effect on Global Currency Markets",
              "Future of USD as World's Reserve Currency",
              "Renewal of China-Argentina Currency Swap",
              "Chinese EV Startup Li Auto Goes Public in the US",
              "Potential Shift Away from USD in International Trade",
              "Rise of Gold Prices Amidst USD Weakness",
              "Impact of USD Weakness on Forex Risk Management"],
    "Sentiment Score": [-70, -60, -50, -30, -40, -20, 40, 50, 70, 30],
    "Importance Score": [1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["China-Russia Partnership to Reduce Dollar Dependence",
              "Impact of US-China Trade War on US Economy",
              "Strengthening of Chinese Yuan Against USD",
              "Global Imbalances and COVID-19 Crisis",
              "Green Stimulus Proposals in US and China",
              "Impact of Beijing's Actions on Hong Kong's Financial Hub",
              "Outperformance of Chinese Yuan and Korean Won",
              "Potential Impact of Biden Presidency on Stock Prices",
              "XPeng's IPO and Expansion in China",
              "Rise of Gold Prices Amidst Geopolitical Tensions"],
    "Sentiment Score": [40, -70, 80, 20, 50, -60, 30, -50, 60, 70],
    "Importance Score": [1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Gold-backed Yuan vs Flagging Dollar",
              "Impact of US-China Cold War on Global Economy",
              "Strengthening of Chinese Yuan",
              "Chinese Electric Car Makers Seeking US IPOs",
              "Gold Prices and US Dollar",
              "US Debt Repayment and Its Implications",
              "False Claims About US-China Relations",
              "Exchange Rate Forecasts for Major Currencies",
              "CBN's Devaluation of the Naira",
              "Comparison of iPhone Prices Worldwide"],
    "Sentiment Score": [80, -70, 70, 60, -50, -40, -30, 40, -60, -20],
    "Importance Score": [1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Impact of Chinese Yuan Strength on USD Exchange Rate",
              "Central Bank Digital Currency and China's Interests",
              "Effect of US Economic Recovery on Dollar",
              "China's Monetary Policy and Yuan",
              "Significance of Dollar as World's Reserve Currency",
              "Gold Prices Amid US-China Tensions",
              "Vulnerability of Chinese Economy",
              "Xpeng's IPO and Tesla Challenge",
              "Impact of Weakening Dollar on Gold Prices",
              "Relocation Costs of Supply Chains from China"],
    "Sentiment Score": [80, 70, -60, 50, 40, 30, -70, 60, -50, -40],
    "Importance Score": [1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Impact of Dollar Depreciation on Reserve Currency Status",
              "Role of Cryptocurrencies in Evading Capital Controls",
              "China's International Development Strategy in Latin America",
              "Market Update: Ant Group IPO and US-China Trade Talks",
              "Transformation of Shenzhen since 1980",
              "Performance of South African Rand against Dollar and Sterling",
              "GBP/USD Exchange Rate Stability Ahead of Federal Reserve Speech",
              "Factors Influencing GBP/NZD Exchange Rate",
              "Impact of Dollar Depreciation on Reserve Currency Status (Repeat)",
              "Role of Cryptocurrencies in Evading Capital Controls (Repeat)"],
    "Sentiment Score": [70, 60, 50, 40, 30, 20, 10, 5, 71, 61],
    "Importance Score": [1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": ["Potential Rise of Chinese Yuan as Reserve Currency by 2030",
              "China's Policy to Allow Faster Yuan Gains for Economic Goals",
              "Impact of Pandemic on Brazil's Reliance on China",
              "Continuous Appreciation of Chinese Yuan Against USD",
              "Potential Influence of Chinese Yuan in Tech and Trade",
              "Post-Brexit Tariff Changes on British Imports from China",
              "Possible Consequences of China Reducing US Treasury Holdings",
              "Impact of Gold Prices on Dollar Amid US-China Trade War",
              "Relationship Between Interest Rates and GDP Growth Rate",
              "Procter & Gamble's Sales Rebound in Key Markets"],
    "Sentiment Score": [80, 70, 60, 50, 40, 30, 20, 10, 5, 90],
    "Importance Score": [1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#36
# Create the matrix
data = {
    "Topic": ["Prediction of Yuan Becoming No.3 Global Currency by 2030",
              "China's Hostage Situation in Multilateral System",
              "Impact of Chinese and American Trade Imbalances on Global Economy",
              "Perception of Strength and Confidence in Chinese Leadership",
              "Speculation on End of Dollar Dominance Amid US-China Tensions",
              "Increased Role of RMB in Cross-Border Capital Flow",
              "Potential Impact of Biden's Policy on Trump's China Tariffs",
              "Research on Neuromyelitis Optica Spectrum Disorder in China",
              "Decline of Iranian Rial Against US Dollar Amid Economic Struggles",
              "Potential Sanctions on China's SMIC Threaten Bitcoin Miners"],
    "Sentiment Score": [90, 70, 50, 30, 10, -10, -30, -50, -70, -90],
    "Importance Score": [1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": ["WTO ruling on US tariffs on China", "U.S.-China tech cold war", "US-China investment flows decline",
              "US-China trade tensions", "Impact of tariffs on cotton supply", "US Ambassador blaming Beijing",
              "Emerging US-China Cold War", "Biden administration's approach to China",
              "Semiconductor industry concerns", "US-China climate cooperation"],
    "Sentiment Score": [-80, -70, -60, -75, -50, -90, -85, 60, -70, 75],
    "Importance Score": [0.745, 0.820, 0.895, 0.665, 0.500, 0.720, 0.800, 0.935, 0.670, 1.000]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["China's Rising Currency and its Impact on Trump's Legacy",
              "Launch of China's Digital Yuan by PBOC",
              "Trump's Attempt to Adjust Dollar Exchange Rate",
              "Potential Global Adoption of China's Digital Currency",
              "Impact of Currency Depreciation on Brazil's Agriculture",
              "Decoupling of Asian Currencies from Yuan",
              "International Currency Jump-start Initiative",
              "Ant Group's Record-breaking IPO",
              "Importance of Armington Elasticity in Trade Models",
              "Impact of Sanctions and COVID-19 on Iran's Economy"],
    "Sentiment Score": [80, 70, -50, 75, -30, 20, 60, 90, 40, -70],
    "Importance Score": [0.384, 0.257, 0.280, 0.219, 0.206, 0.193, 0.171, 0.158, 0.143, 0.109]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["China's Yuan Strengthens Amid Economic Recovery",
              "US Investigates Vietnam's Alleged Currency Manipulation",
              "Establishment of Rupiah-Yuan Direct Settlement Framework",
              "US-China Trade War Dynamics",
              "Impact of Nationalism on Global Solidarity",
              "Indonesian and Chinese Central Banks Sign Currency Agreement",
              "US Dollar's Role as Global Reserve Currency During Q2 Turmoil",
              "China's Efforts to Downplay GDP Growth Target",
              "China's Sovereign Wealth Fund Performance",
              "Ghana's Cedi Performance Improvement"],
    "Sentiment Score": [70, -40, 60, -30, -60, 50, 45, 35, 75, 80],
    "Importance Score": [0.314, 0.248, 0.201, 0.179, 0.144, 0.130, 0.109, 0.086, 0.068, 0.021]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["U.S.-China Standoff Over WeChat Ban",
              "Impact of U.S.-China Tech Feud on Supply Chain",
              "US-China Decoupling in Tech Supply Chain",
              "U.S. Investigation into Chinese Tech Supply Chain",
              "US-China Trade War Dynamics",
              "US-China Rivalry in Arctic",
              "Impact of US-China Tensions on Taiwan",
              "US-China Relations: Views and Tensions",
              "China's Monopoly on Rare Earth Elements",
              "China's Disinformation Campaign in the Philippines"],
    "Sentiment Score": [-80, -60, -70, -65, -50, -45, -55, -40, 70, -30],
    "Importance Score": [0.274, 0.236, 0.204, 0.179, 0.144, 0.109, 0.086, 0.068, 0.041, 0.021]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#41
data = {
    "Topic": ["China's Yuan Stability",
              "China's Renminbi Internationalization",
              "China-Indonesia Currency Deal",
              "U.S.-China Cold War Dynamics",
              "U.S.-China Trade Relations",
              "China's Economic Rise and Impact",
              "China's Special Economic Zones",
              "China's Position as World's Largest Economy",
              "U.S.-China Relations on Tech Policies",
              "China's Investments in Foreign Assets"],
    "Sentiment Score": [40, 50, 30, -30, -20, 60, 25, 70, -50, 35],
    "Importance Score": [0.275, 0.250, 0.225, 0.200, 0.175, 0.150, 0.125, 0.100, 0.075, 0.050]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Yuan's Appreciation Against USD",
              "Impact of U.S. Deficit on Exchange Rates",
              "Biden Win's Potential Impact on Yuan",
              "Tariff Effects on U.S. Economy",
              "Technology Cold War Disruptions",
              "Divergence in Coronavirus Responses",
              "Impact of Weaker Dollar on Companies",
              "China's Strategic Yuan Considerations",
              "Hong Kong's Role in Geopolitical Dynamics",
              "Pound-NZD Exchange Rate Dynamics"],
    "Sentiment Score": [50, -30, 40, -20, -40, -10, 30, 60, -50, 20],
    "Importance Score": [0.300, 0.275, 0.250, 0.225, 0.200, 0.175, 0.150, 0.125, 0.100, 0.075]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["China's Currency Control Measures",
              "Impact of COVID-19 on Exchange Rates",
              "Potential Change in Yuan's Daily Fixing Mechanism",
              "Hong Kong's Role as Financial Gateway",
              "Yuan's Attractiveness",
              "China's Five-Year Economic Plan",
              "Trump Administration's Impact on U.S.-China Relations",
              "China's Economic Recovery",
              "RMB Bond Market Growth",
              "Weakening of the U.S. Dollar"],
    "Sentiment Score": [-50, -40, -30, 20, 30, 40, -10, 50, 60, -20],
    "Importance Score": [0.250, 0.225, 0.200, 0.175, 0.150, 0.125, 0.100, 0.075, 0.050, 0.025]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    'Topic': [
        "US-China trade tensions and rivalry persist",
        "China's economic growth and industrial policy",
        "Impact of US presidential election on Asia-Pacific",
        "Vaccine diplomacy and US-China rivalry in Africa",
        "US-China tech war and trade tensions",
        "US efforts to isolate China in Latin America",
        "COVID-19's impact on US-China relations",
        "Impact of US-China competition on global trading system",
        "US-China relations under Biden presidency",
        "China's efforts for internationalization of its currency"
    ],
    'Sentiment Score': [
        -80, 60, 20, -30, -70, -50, -10, -60, 40, 30
    ],
    'Importance Score': [
        0.651, 0.311, 0.208, 0.192, 0.159, 0.138, 0.123, 0.111, 0.096, 0.078
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": ["China's aspiration to internationalize the renminbi (RMB)",
              "Impact of US-China trade tensions on currency exchange",
              "China's economic growth prospects",
              "Chinese fintech giant Lufax's international expansion",
              "Chinese electric car approval for sale in the US",
              "Impact of US presidential election on US-China relations",
              "Importance of stable relations between US and China",
              "China's role in global vaccine race",
              "Chinese yuan's volatility amid US election swings",
              "US-China rivalry and its implications"],
    "Sentiment Score": [50, -30, 70, 60, 40, -20, 50, 80, -40, -20],
    "Importance Score": [0.396, 0.217, 0.174, 0.109, 0.058, 0.041, 0.034, 0.032, 0.032, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": [
        "Biden's election victory impact on world currencies",
        "Trump bans U.S. investments in Chinese companies",
        "US-China trade tensions",
        "Luxury brands raising prices",
        "Biotech industry growth in China",
        "Vietnam currency manipulation allegations",
        "Shanghai's RMB exchange policy",
        "Global trade slowdown",
        "Space-induced mutation breeding",
        "US-Japan defense treaty implications for Senkaku"
    ],
    "Sentiment Score": [
        75, -85, -65, -50, 70, -60, 60, -55, 45, 40
    ],
    "Importance Score": [
        0.227, 0.163, 0.122, 0.111, 0.107, 0.097, 0.082, 0.075, 0.068, 0.063
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd
#46
# Create a dictionary with the data
data = {
    "Topic": [
        "Rising value of yuan likely to raise import cost",
        "China's Yuan Is a G-10 Currency to HSBC's New FX Research Chief",
        "US Takes Action to Bar American Investments in Broad Range of Chinese Companies Deemed Linked to the Chinese",
        "Biden Likely Won't Reverse Trump's Trade War Against China",
        "Asia-Pacific Nations Sign Huge Trade Deal With China While U.S. Sits It Out",
        "US Imposes New Restrictions on Chinese Military Companies",
        "China takes out anger over U.S. missile system on South Korea",
        "US, China sleepwalking towards World War III",
        "How China Uses the People's Armed Police as Agents of Diplomacy",
        "Obama: ‘I could not have a trade war’ with China due to financial crisis"
    ],
    "Sentiment Score": [
        10.0, 35.0, -25.0, -15.0, -20.0, -30.0, -20.0, -60.0, 10.0, 30.0
    ],
    "Importance Score": [
        0.280, 0.266, 0.222, 0.189, 0.156, 0.123, 0.102, 0.075, 0.056, 0.035
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": [
        "China's renminbi on course for record six-month run",
        "Use of Chinese yuan in cross-border transactions surges",
        "Cooperative Competition Is Possible Between China and the U.S.",
        "AUD to USD forecast 2021: is now a good time to invest?",
        "How margin trading and short selling work in China",
        "Ticking time bomb: why Xi is dragging down the dragon",
        "What is the US dollar-yuan exchange rate and why is it important?",
        "Specialty Retailer Tiffany Earnings Beat Wall Street Estimates on Solid China Demand",
        "Free Trade Is Killing American Manufacturing",
        "China Construction Bank halts US$3 billion bond plan amid fintech backlash"
    ],
    "Sentiment Score": [
        40.0, 35.0, 20.0, 15.0, 5.0, -10.0, -25.0, -35.0, -50.0, -65.0
    ],
    "Importance Score": [
        0.303, 0.281, 0.256, 0.219, 0.188, 0.158, 0.131, 0.106, 0.083, 0.063
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": [
        "China wants to weaponize its currency. A digital version could help",
        "Yellen and dollar diplomacy",
        "US-China: New rules of engagement",
        "U.S. to Expel Chinese Graduate Students With Ties to China's Military Schools",
        "How much US debt does China own and why is it important?",
        "The Fraying of the US Global Currency Reserve System",
        "China could subsidize its digital renminbi currency",
        "Japan, Korea hold their nerve as currencies surge",
        "Is Wall Street ready to work on China time?",
        "Investing in Hong Kong-Listed Stocks: Which Broker Is the Cheapest?"
    ],
    "Sentiment Score": [
        70.0, 65.0, 60.0, 50.0, 45.0, 40.0, 30.0, 20.0, 10.0, 5.0
    ],
    "Importance Score": [
        0.305, 0.280, 0.257, 0.231, 0.213, 0.196, 0.164, 0.131, 0.099, 0.077
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": [
        "China widens DCEP digital yuan tests, advancing global ambitions",
        "10 reasons why renminbi will keep on rising",
        "China foreign minister tells American CEOs he hopes for less U.S. 'interference' in Chinese affairs",
        "China's November exports rise by 21.1% on strong global demand, beating forecasts",
        "Struggling Cuba plans 'big bang' currency devaluation",
        "Rupee settles 10 paise lower at 73.90 against US dollar",
        "Puntland Deploys Troops After Week Of Economic Unrest",
        "Plunging US dollar has wide ramifications for Australia and the world",
        "Global investors place Rmb1tn bet on China breakthrough",
        "Outlook 2021: China"
    ],
    "Sentiment Score": [
        80.0, 75.0, 70.0, 60.0, 50.0, 40.0, 30.0, 20.0, 10.0, 5.0
    ],
    "Importance Score": [
        0.300, 0.275, 0.252, 0.228, 0.204, 0.181, 0.158, 0.136, 0.115, 0.094
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": [
        "US labels Switzerland a currency manipulator",
        "U.S. Treasury labels Switzerland, Vietnam as currency manipulators",
        "US: Switzerland, Vietnam Manipulating Currencies",
        "Taiwan put on US’ currency watchlist",
        "US Includes India In The 'Monitoring List' Of Currency Manipulators After Removal In 2019 Here's All About It",
        "Will the US dollar’s slide undermine it as the world’s currency of choice?",
        "U.S. currency manipulator tag for Switzerland unlikely to deter FX approach",
        "Swiss refuse to roll over as Trump administration lashes out over currency",
        "Vietnam, with larger trade surplus than Japan, draws US ire",
        "Explained: What is currency manipulation, and why has US put India on its currency watchlist?"
    ],
    "Sentiment Score": [
        80.0, 75.0, 70.0, 60.0, 50.0, 40.0, 30.0, 20.0, 10.0, 5.0
    ],
    "Importance Score": [
        0.300, 0.275, 0.252, 0.228, 0.204, 0.181, 0.158, 0.136, 0.115, 0.094
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": [
        "China surpassing US in 2028 is faint praise: Global Times editorial",
        "US China Trade War Effect on Global Economy",
        "US Designation of Vietnam as Currency Manipulator Could Spur Talks, Changes, Analysts Say",
        "Biden will inherit a strong hand against China's Xi Jinping, thanks to Trump",
        "With Money, and Waste, China Fights for Chip Independence (Published 2020)",
        "European tech accuses US of using sanctions to shut it out of China",
        "Trump's final trade jab may be tariffs on Vietnamese goods - experts",
        "Businesses Refuse To Use Local Currency in Puntland",
        "Cambodia Reduces its Dependency on the US Dollar",
        "Something Is Odd in North Korea's Foreign Exchange Markets"
    ],
    "Sentiment Score": [
        85.0, 80.0, 75.0, 70.0, 65.0, 60.0, 55.0, 50.0, 45.0, 40.0
    ],
    "Importance Score": [
        0.300, 0.275, 0.252, 0.228, 0.204, 0.181, 0.158, 0.136, 0.115, 0.094
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": [
        "China's tweaks to CFETS index basket could drive yuan higher - analysts",
        "New York Stock Exchange to Delist China Mobile, Among Others",
        "US Dollar as “Global Reserve Currency” amid Fed’s QE and US Government Deficits: Dollar Hegemony in Decline",
        "UK stocks wrap up worst year since 2008 while US and China rebound",
        "Euro US Dollar Exchange Rate 2020 In Review: Key EUR/USD Events And Updated 2021 Forecasts",
        "Is China right to tame Ant?",
        "Trump Gets ‘Art Of The Deal’ Masterclass From Vietnam",
        "Louis Gave: «Inflation Will Come Back With a Vengeance»",
        "Why China's volatility is bad for Uganda's economy",
        "Pushback on Xi's Vision for China Spreads Beyond U.S."
    ],
    "Sentiment Score": [
        90.0, 85.0, 80.0, 75.0, 70.0, 65.0, 60.0, 55.0, 50.0, 45.0
    ],
    "Importance Score": [
        0.300, 0.275, 0.252, 0.228, 0.204, 0.181, 0.158, 0.136, 0.115, 0.094
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)

print(bound)

len(bound)

bound=pd.DataFrame(bound)
bound.to_csv('cnyusdscore2020.csv')