# -*- coding: utf-8 -*-
"""EUR2022.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JMYLtqAWt-TEYczPFe8umfo5gooiFFX4
"""

from sklearn.preprocessing import MinMaxScaler
import numpy as np

def weekly_score(df):
  transfer=MinMaxScaler(feature_range=(0.1,0.5))
  df_1=np.array(df.iloc[:,2]).reshape(-1, 1)
  df_1=transfer.fit_transform(df_1)
  d=np.array(df.iloc[:,1])*df_1.reshape(1, -1)
  upper=int(sum(np.maximum(d,0).T))
  lower=int(sum(np.minimum(d,0).T))
  return upper,lower

bound=[]
raw_data=[]

import pandas as pd

# Create the dataframe
data = {
    'Topic': ["China's foreign exchange reserves", "Impact of passive ETFs on exchange rates",
              "Dollar's weight in Yuan exchange-rate index", "Dollar's performance after U.S. jobs report",
              "Performance of different asset classes in 2021", "Apple's market value milestone",
              "U.S. Dollar/Japanese Yen technical analysis", "GBP/USD exchange rate analysis for 2021",
              "EUR/USD exchange rate forecasts and technical analysis", "Norway's seafood export records",
              "EU and euro-related news", "U.S. fiscal response to COVID-19",
              "Trade policies under Biden administration", "Central bank policies affecting exporters"],
    'Sentiment Score': [0, -50, 70, -10, 60, 80, 5, -30, 0, 10, 5, 10, -5, -5],
    'Importance Score': [0.077, 0.231, 1.000, 0.154, 0.923, 0.615, 0.308, 0.462, 0.308, 0.077, 0.385, 0.231, 0.462, 0.231]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    'Topic': ["Euro's 20th anniversary", "Euro vs. U.S. Dollar as global currency",
              "European Union's growth strategy", "Decoupling of USD-CNY relationship",
              "Future of the euro currency", "Euro/dollar crosses and benchmark rates",
              "Euro's history and key facts", "Views on the euro as a failed experiment",
              "Euro in trading and speculation", "Euro/USD exchange rate movements and forecasts"],
    'Sentiment Score': [0, 70, -30, -50, 10, 5, 5, -80, 0, 60],
    'Importance Score': [0.154, 1.000, 0.462, 0.231, 0.077, 0.308, 0.308, 0.923, 0.077, 0.615]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    'Topic': ["Origins of the euro: The ECU",
              "Regulatory issues in the crypto industry",
              "Preference of US investors for currency-hedged ETFs",
              "Supply chain crisis and its implications",
              "Anniversary and sentiments surrounding the euro",
              "Monetary policy discussions",
              "Economic comparisons between the US and Europe",
              "Global inflation concerns",
              "Investment trends in European startups",
              "Political factors affecting USD/EUR"],
    'Sentiment Score': [0, -50, 5, -40, 60, 10, 0, -30, 70, 20],
    'Importance Score': [0.077, 0.231, 0.154, 0.192, 0.308, 0.077, 0.000, 0.154, 1.000, 0.385]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    'Topic': ["Future of CBDCs",
              "American investors in European soccer",
              "Most traded currency pairs in 2023",
              "SOFR puzzle and how to solve it",
              "Impact of Bretton Woods System",
              "European vs. U.S. stance on Russia",
              "Corporate withdrawals from Myanmar",
              "Legal rulings on regional food products",
              "Travel restrictions post-Brexit",
              "Business achievements of automotive brands"],
    'Sentiment Score': [10, 80, 20, 30, 40, -60, -70, 50, -90, 70],
    'Importance Score': [0.128, 0.192, 0.064, 0.096, 0.064, 0.256, 0.160, 0.096, 1.000, 0.320]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "US Rate Rises Highlight European Fixed-Income Opportunities",
        "Best Hours to Trade the Euro",
        "Dollar Rises from Two-Week Low after U.S. Jobs Surprise",
        "2021 Year-End Sanctions and Export Controls Update",
        "Dollar Up, Euro Down as Pair Face Off in Rate Hike Tussle",
        "Lebanon: US Dollar Savers Fear They’ll Foot Crisis Bill"
        "Ukraine and Dollar Weaponization",
        "EU and U.S. Starting to Align on AI Regulation",
        "US versus Europe: Will Their Shared Path Continue in 2022?",
        "Costa Rica Withdraws Certain Colones Bills"
    ],
    "Sentiment Score": [
        25, 10, 45, -20, 15, -65, -70, 40, 30, 5
    ],
    "Importance Score": [
        0.726, 0.435, 0.852, 0.248, 0.612, 0.123, 0.116, 0.798, 0.735, 0.387
    ]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)
#5

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "High Inflation Impact on USD-EUR Exchange Rate",
        "Billions from Europe's Recovery Fund Transforming Spain's Economy",
        "Corporate Forex Hedging Challenges",
        "Impact of U.S. Rate Hikes on Dollarized Emerging Market Banks",
        "European Strategy for Global Projection",
        "Digital Euro Bill Announcement",
        "Concerns Over 'Dark Money' Influence on Equal Rights Movements",
        "Russia's Energy Influence on Europe Despite Sanctions Threats",
        "Revival of Private Banking in Europe",
        "EU's Efforts to Boost Microchip Output"
    ],
    "Sentiment Score": [
        -80, 60, -20, -50, 40, 30, -70, -30, 50, 20
    ],
    "Importance Score": [
        0.856, 0.422, 0.312, 0.587, 0.754, 0.921, 0.173, 0.698, 0.636, 0.835
    ]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "Introduction of Euro Banknotes and Coins in 2002",
        "Russia-China Dedollarization Concerns",
        "EU Ban on Caymans Over Money Laundering",
        "Top Court Clears EU to Cut Funds Over Rule-of-Law Concerns",
        "European Commission's Digital Euro Bill Announcement",
        "Recovery of Funds After Crypto-Currency Scam",
        "Credit Suisse Leak Reveals High-Risk Clients",
        "AU-EU Summit and Deeper Relationship Challenges",
        "Inflation's Correlation with Corruption",
        "Rising Global Popularity of Renminbi (RMB)"
    ],
    "Sentiment Score": [
        50, -70, -60, -40, 30, 40, -50, -30, -20, 60
    ],
    "Importance Score": [
        0.987, 0.754, 0.632, 0.856, 0.421, 0.598, 0.365, 0.789, 0.523, 0.921
    ]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "Russia's Central Bank Reserve and Currency Stability",
        "Sanctions on Russia's Central Bank",
        "Effectiveness of Sanctions on Russia",
        "Fresh US Sanctions on Russian Bonds",
        "Russia's Efforts to Counteract Sanctions",
        "International Response to Russia's Invasion of Ukraine",
        "Impact of Sanctions on Global Economic Players",
        "European Monetary Policy and Exchange Rate Dynamics",
        "Market Response to Geopolitical Events",
        "Currency Market Developments in Response to Ukraine Crisis"
    ],
    "Sentiment Score": [
        60, -80, -70, -60, 40, -90, -50, 30, -70, -80
    ],
    "Importance Score": [
        0.923, 0.781, 0.645, 0.523, 0.789, 0.856, 0.456, 0.632, 0.754, 0.921
    ]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "Euro's Decline and Dollar Strength Ahead of Jobs Data",
        "Russia's Response to Sanctions",
        "Impact of Sanctions on Ruble and Russian Banks",
        "US and EU Discussion on Russia Sanctions",
        "Market Response to Ukraine Crisis",
        "Sanctions' Effect on North Korea's Currency Intake",
        "US Dollar's Dominance in Sanctions",
        "Russian Central Bank's Foreign Reserves",
        "Impact of Sanctions on Russian Economy",
        "US-Led Western Block's Sanctions Against Russia"
    ],
    "Sentiment Score": [
        -60, -80, -90, -70, -80, -40, 70, 50, -90, -80
    ],
    "Importance Score": [
        0.895, 0.782, 0.921, 0.654, 0.812, 0.579, 0.723, 0.736, 0.854, 0.912
    ]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "Further Economic Costs on Russia by US, EU, and G7",
        "Euro's Near Parity with US Dollar",
        "Escalation of Sanctions by US, UK, and EU Against Russia",
        "Impact of Ukraine Conflict on Currency Markets",
        "Currency Volatility and Geopolitical Developments",
        "Digital Euro and Disruption in European Payment Systems",
        "Russian Central Bank's Controls on Dollar Purchases",
        "Effects of Sanctions on Russian Economy and Reserves",
        "Sanctions Impacting Global Commerce and Financial Systems",
        "Croatia's Adoption of Euro"
    ],
    "Sentiment Score": [
        -70, -90, -80, -80, -60, 50, -70, -90, -80, 70
    ],
    "Importance Score": [
       0.912, 0.854, 0.812, 0.782, 0.736, 0.723, 0.695, 0.654, 0.579, 0.532
    ]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)
#10

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "Saudi Arabia Considers Accepting Yuan Instead of Dollars for Chinese Oil Sales",
        "Impact of Sanctions on Global Economy",
        "Central Bank of Uzbekistan Updates Exchange Rates: USD and EUR Skyrocketing Against UZS",
        "Paradigm Shift in World Order and Its Financial Implications",
        "De-dollarisation and Its Imminent Consequences",
        "Sanction-Proof Status of the Russian Economy",
        "German Chip Manufacturing Investment and Its Impact on Global Economy",
        "U.S. Spending on Ukraine and Its Effects on Currency Markets",
        "Qatar-Germany Gas Deal and Its Influence on European Economy",
        "Euro to USD Exchange Rate Dynamics"
    ],
    "Sentiment Score": [
        -40, -80, -90, -70, -60, -70, 60, 50, 60, 70
    ],
    "Importance Score": [
        0.917, 0.872, 0.824, 0.785, 0.739, 0.695, 0.661, 0.617, 0.574, 0.532
    ]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "EU Defense Funding Benefiting European Military Companies",
        "Market Implications of the Russia-Ukraine Crisis",
        "Impact of Russia Sanctions on the Chinese Yuan",
        "U.S.-EU LNG Deal to Reduce European Dependency on Russian Gas",
        "Putin's Announcement on Gas Currency Switch for 'Unfriendly Countries'",
        "Stealth Erosion of Dollar Dominance Due to Ukraine War",
        "Printing of African Money in Europe Raises Questions",
        "Impact of Freezing Russia's Central Bank Reserves on Global Economy",
        "Russian Stock Market Opening with Restrictions",
        "India-Russia Currency Swaps Impacting USD Reserve System"
    ],
    "Sentiment Score": [
        20, -70, -30, 50, -60, -80, -40, -70, -50, 30
    ],
    "Importance Score": [
        0.982, 0.945, 0.904, 0.864, 0.825, 0.788, 0.752, 0.717, 0.683, 0.650
    ]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "Russian Ruble Recovery",
        "US Dollar Rally Ahead of Federal Reserve Rate Hike",
        "Emergence of Russian Black Market for Foreign Currency",
        "Moroccan Dirham Performance Against US Dollar",
        "US Dollar Reserve Currency Status and Inflation Impact",
        "Best Travel Money Exchange Rates",
        "Profitable Forex Pairs for Trading",
        "Impact of US Dollar Strength on Gold Price",
        "Potential Threat to US Dollar Dominance",
        "Impact of Strong Dollar on Crude Oil Prices"
    ],
    "Sentiment Score": [
        70, 60, -50, 40, -30, 20, 10, -20, -60, -80
    ],
    "Importance Score": [
        0.982, 0.945, 0.904, 0.864, 0.825, 0.788, 0.752, 0.717, 0.683, 0.650
    ]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "US Dollar Strength",
        "Russian Ruble Performance",
        "Federal Reserve Policy Impact on Currency Hedging",
        "Swedish Krona as Safe-Haven Currency",
        "Impact of Debt Build-Up on Currency Markets",
        "Ruble Defense and Implications",
        "Impact of Global Tensions on GBP/USD Exchange Rate",
        "U.S. Dollar Index Momentum",
        "U.S. Dollar Dominance Amid Fed Policy",
        "Bitcoin Price Impact by Dollar Strength"
    ],
    "Sentiment Score": [
        80, 60, -40, 30, -20, 50, -10, 70, 40, -70
    ],
    "Importance Score": [
        0.983, 0.948, 0.914, 0.880, 0.847, 0.814, 0.781, 0.748, 0.716, 0.684
    ]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "European Reaction to Russian Oil Purchases",
        "Inflation Impact on Dollar and Euro",
        "European Visa Requirements",
        "US Dollar Exchange Rates in Foreign Markets",
        "UK GDP Data and Pound/Euro Exchange Rate",
        "Euro Performance Amid Global Events",
        "Dollar Strength Against Basket of Currencies",
        "Central Bank Policies Impacting Exchange Rates",
        "Cryptocurrency Regulation in Europe",
        "Impact of US Real Yields on Stock Market"
    ],
    "Sentiment Score": [
        -80, -60, -30, 40, -10, 20, 50, 70, 90, -50
    ],
    "Importance Score": [
        0.978, 0.946, 0.914, 0.882, 0.850, 0.818, 0.786, 0.754, 0.722, 0.690
    ]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)
#15

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "European Response to Russian Oil Purchases",
        "U.S. Dollar Hegemony Ending",
        "Impact of EU and UK AML Regulations",
        "Official Dollar Exchange Rate in Kyrgyzstan",
        "Japanese Yen Depreciation",
        "US Dollar Hits 2-Year High",
        "Impact of Rising Interest Rates on Dollar",
        "Impact of Dollar Strength on Global Markets",
        "Euro's Performance Amid Economic Factors",
        "Impact of US Inflation on Dollar Strength"
    ],
    "Sentiment Score": [
        -80, -60, -30, 40, -10, 20, 50, 70, 90, -50
    ],
    "Importance Score": [
        0.978, 0.946, 0.914, 0.882, 0.850, 0.818, 0.786, 0.754, 0.722, 0.690
    ]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": ["U.S. dollar strengthens to two-year high",
              "Euro weakens against the U.S. dollar",
              "Impact of Covid and Russia's invasion on the strength of the Western system",
              "Economic sanctions against Russia and its effects on global markets",
              "Euro nearing five-year low stoking recession fears",
              "European energy firms' strategies for paying for Russian gas",
              "Macron's re-election and implications for the EU leadership",
              "Bank loan supply's role in the effects of exchange rate depreciation",
              "Impact of U.S.-China technological decoupling on global trade",
              "The freezing of Russia's central bank reserves and its global repercussions"],
    "Sentiment Score": [100, -90, 80, -70, -85, 75, 70, 65, -60, -75],
    "Importance Score": [0.975, 0.950, 0.925, 0.900, 0.875, 0.850, 0.825, 0.800, 0.775, 0.750]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": ["EUR/USD parity due to German economic struggles",
              "Impact of U.S. dollar strength on global growth",
              "Europe's debt to China and its consequences",
              "China's efforts to reduce dependence on the U.S. dollar",
              "Multi-currency bond issuance in Europe",
              "Impact of Russia's invasion of Ukraine on global systems",
              "Regulatory scrutiny on cryptocurrency and stablecoins",
              "EU funds fraud and money laundering investigation",
              "Moroccan dirham performance against major currencies",
              "Russia's shift to gold amid sanctions"],
    "Sentiment Score": [90, -85, -80, -75, 70, 65, -60, -55, 50, 45],
    "Importance Score": [0.975, 0.950, 0.925, 0.900, 0.875, 0.850, 0.825, 0.800, 0.775, 0.750]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = [
    ["U.S. Dollar Hits 20-Year High", 100, 1.000],
    ["Forex News: Dollar Pauses as US Yields Fall", -90, 0.950],
    ["Euro Bounces Off Lows but Heads for Big Weekly Loss", -80, 0.900],
    ["Free Forex Signals: Sell EUR/USD – 10 May 2022", -70, 0.850],
    ["Chart of the Day: U.S. Dollar Is Breaking Major Levels", 90, 0.800],
    ["US Inflation: Has It Peaked?", 80, 0.750],
    ["Euro to Hit Parity Against the Dollar Within Six Months", -60, 0.700],
    ["Dollar Starts Week on Strong Footing on Firm Safe-Haven Bid", 70, 0.650],
    ["US Fed's Persistence Challenges Gold's Safe-Haven Status", -50, 0.600],
    ["Euro-USD Latest FX Rates: Dollar and Euro May Reach Parity", 60, 0.550]
]

# Create the DataFrame
df = pd.DataFrame(data, columns=["Topic", "Sentiment Score", "Importance Score"])

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": ["Weakened Euro nearing parity with U.S. Dollar",
              "Introduction of digital euro project",
              "Europe's response to Ukrainian refugee crisis",
              "Impact of strong U.S. Dollar on European vacations",
              "EU allowing companies to purchase gas from Russia",
              "Surging Dollar approaching parity with Euro",
              "Alternatives to SWIFT and dollar dominance",
              "Impact of Ukraine war on global monetary order",
              "Benefits of central bank digital euro",
              "Influence of stronger U.S. dollar on crude oil prices"],
    "Sentiment Score": [90, -70, 60, -50, 80, 85, -65, 75, -45, -60],
    "Importance Score": [0.975, 0.950, 0.925, 0.900, 0.875, 0.850, 0.825, 0.800, 0.775, 0.750]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)
#20

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": ["Euro strengthens as ECB eyes rate hikes, dollar slides",
              "Dollar weakens as Lagarde comments lift euro",
              "Potential impact of digital dollar on payment systems",
              "Effects of strong ruble on shielding Russia",
              "European Union's acceptance of Putin's ruble payment system",
              "EU's $40 billion aid package for Ukraine",
              "End of borderless data era and its impact on digital currency",
              "Launch of Verto's multi-currency global account",
              "Impact of Marshall Plan on postwar Europe and Ukraine",
              "Rising interest rates and hedging of euro area banks' books"],
    "Sentiment Score": [-90, -85, 60, 70, -75, 80, -50, 65, 75, 60],
    "Importance Score": [0.975, 0.950, 0.925, 0.900, 0.875, 0.850, 0.825, 0.800, 0.775, 0.750]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": ["Twitter inquiry about the dollar's global reserve currency status",
              "Central banks embracing digital currencies",
              "Euro's performance and monthly gain",
              "EU banning Russian oil and its impact",
              "Turkish lira's plunge and market concerns",
              "US whistleblower collaborating on a privacy project",
              "Iran's proposal for a new currency for trade",
              "Microsoft's warning on currency impact",
              "Forex market outlook and technical analysis",
              "Dollar's dominance and impact on global markets"],
    "Sentiment Score": [-80, 70, -60, -75, -90, 50, 60, -85, 0, 80],
    "Importance Score": [0.950, 0.900, 0.850, 0.825, 0.800, 0.775, 0.750, 0.725, 0.700, 0.675]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": ["Invoicing currencies in extra-EU exports and imports",
              "Growing European preference for China's currency",
              "Factors influencing the strength of the US dollar",
              "Euro notes and denominations",
              "European companies investing in R&D in China",
              "Record oil prices and the impact of a strong dollar",
              "ECB meeting and euro outlook",
              "ECB's interest rate policies",
              "Russian banks charging fees on FX accounts",
              "Impact of geopolitical events"],
    "Sentiment Score": [10, -70, 40, 20, 60, -90, -30, -50, -60, -80],
    "Importance Score": [0.950, 0.900, 0.850, 0.825, 0.800, 0.775, 0.750, 0.725, 0.700, 0.675]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Euro's International Use Stability",
    "Global Inflation Impact",
    "Monetary Policy Challenges in Eurozone",
    "Competition Between Dollar and Euro",
    "Climate Change Impact on Currencies",
    "Launch of Euro Stablecoin",
    "Adoption of Euro in Croatia",
    "Impact of Monetary Policy Decisions",
    "Cross-Currency Rate Switch",
    "Central Bank Actions"
]

sentiment_scores = [50, -80, -30, 10, 40, 20, 30, -70, 5, 15]

importance_scores = [1.000, 0.925, 0.850, 0.775, 0.700, 0.625, 0.550, 0.475, 0.400, 0.325]

# Create a DataFrame
df = pd.DataFrame({
    'Topic': topics,
    'Sentiment Score': sentiment_scores,
    'Importance Score': importance_scores
})

print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Eurozone Economic Performance",
    "Sanctions and Geopolitical Events",
    "Summer Travel Costs",
    "Central Bank Decisions",
    "Global Economic Concerns",
    "Brexit and its Consequences",
    "Consumer Protections and Compensation",
    "Market Performance and Risk Appetite",
    "International Fuel Prices",
    "Currency Converter Services"
]

sentiment_scores = [-80, -70, -50, -30, -20, -10, 0, 10, 20, 40]

importance_scores = [1.000, 0.925, 0.850, 0.775, 0.700, 0.625, 0.550, 0.475, 0.400, 0.325]

# Create a DataFrame
df = pd.DataFrame({
    'Topic': topics,
    'Sentiment Score': sentiment_scores,
    'Importance Score': importance_scores
})

print(df)
#25

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Eurozone Economic Stability",
    "Chinese Yuan's Global Share Gain",
    "Abortion Rights Debate in Europe",
    "Marshall Plan and Economic Recovery",
    "Cryptocurrency Regulation in the EU",
    "Venezuelan Perception of Europe",
    "Euro Forecast against USD",
    "Russian Influence and Sanctions Impact",
    "US Supreme Court's Abortion Ruling Impact",
    "European Commission President's Income"
]

sentiment_scores = [-80, -70, -60, -50, -40, -30, -20, -10, 10, 20]

importance_scores = [1.000, 0.925, 0.850, 0.775, 0.700, 0.625, 0.550, 0.475, 0.400, 0.325]

# Create a DataFrame
df = pd.DataFrame({
    'Topic': topics,
    'Sentiment Score': sentiment_scores,
    'Importance Score': importance_scores
})

print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Euro Hits 20-Year Low Against Dollar",
    "US Dollar Strength and Euro Weakness",
    "Euro-Dollar Parity Concerns",
    "Impact of Strong Dollar on Global Economy",
    "Exchange Rate Trends Over Two Decades",
    "Economic Recession and Euro Decline",
    "Currency Parity and its Implications",
    "US Treasury Influence on European Currency Markets",
    "Wealthy Americans Exploiting Euro Weakness",
    "Euro's Sensitivity to Economic Forecasts"
]

sentiment_scores = [100, -90, 80, -70, -60, 50, -40, 30, -20, -10]

importance_scores = [1.000, 0.925, 0.850, 0.775, 0.700, 0.625, 0.550, 0.475, 0.400, 0.325]

# Create a DataFrame
df = pd.DataFrame({
    'Topic': topics,
    'Sentiment Score': sentiment_scores,
    'Importance Score': importance_scores
})

print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Euro Hits Parity with US Dollar",
    "Impact of Euro's Fall to Dollar Parity",
    "Recession Fears in Europe Weigh on Euro",
    "Consequences of Euro-Dollar Parity",
    "Tourism and Trade Effects of Dollar-Euro Parity",
    "Investors Favoring US Dollar Over Euro",
    "US Dollar Strengthens Against Euro",
    "Economic Implications of Euro's Slide to Parity",
    "Euro's Value Decrease Against Dollar",
    "Euro's Impact on Global Economy"
]

sentiment_scores = [100, 90, -80, 70, -60, -50, 40, -30, -20, 10]

importance_scores = [1.000, 0.975, 0.950, 0.925, 0.900, 0.875, 0.850, 0.825, 0.800, 0.775]

# Create a DataFrame
df = pd.DataFrame({
    'Topic': topics,
    'Sentiment Score': sentiment_scores,
    'Importance Score': importance_scores
})

print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Euro-dollar parity",
    "Impact of euro-dollar parity on portfolios",
    "Travel benefits of a strong dollar",
    "Strength of the U.S. dollar",
    "Impact of a strong dollar on U.S. multinationals",
    "Impact of euro's depreciation on Moroccan economy",
    "Impact of euro's depreciation on Maltese importers",
    "Impact of euro's depreciation on European ski vacations",
    "Impact of euro's depreciation on American tourists",
    "Impact of euro's depreciation on international students"
]

sentiment_scores = [90, 70, 80, 85, 75, -60, -70, 65, 75, -80]

importance_scores = [1.000, 0.987, 0.974, 0.961, 0.948, 0.935, 0.922, 0.909, 0.896, 0.883]

# Create a DataFrame
df = pd.DataFrame({
    'Topic': topics,
    'Sentiment Score': sentiment_scores,
    'Importance Score': importance_scores
})

print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Euro reaches parity with US dollar",
    "Impact of euro's depreciation on Moroccan economy",
    "Impact of euro's depreciation on Maltese importers",
    "Strong dollar benefits American tourists in Europe",
    "Impact of euro's depreciation on American tourists",
    "Impact of euro's depreciation on international students",
    "Euro's value impacts CFA franc and 'imported inflation'",
    "Euro's plunge affects carry traders in emerging markets",
    "Economic slowdown affects global growth",
    "USD's strength affects art market"
]

sentiment_scores = [-85, 70, 75, -80, -75, 80, 60, 65, 50, -70]

importance_scores = [1.000, 0.988, 0.976, 0.964, 0.952, 0.940, 0.928, 0.916, 0.904, 0.892]

# Create a DataFrame
df = pd.DataFrame({
    'Topic': topics,
    'Sentiment Score': sentiment_scores,
    'Importance Score': importance_scores
})

print(df)
#30

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and updated importance scores
topics = [
    "ECB's potential rule-breaking",
    "Carry traders exploiting weak Euro",
    "Impact of US dollar's strength on global economy",
    "Multi-polar trade moves away from USD",
    "Comparative cost of living crisis",
    "Reasons behind US dollar's strength",
    "Impact of US dollar's rise on global markets",
    "US dollar's impact on specific currencies (Naira)",
    "Central bank actions affecting currency exchange rates",
    "Technical analysis on currency pairs"
]

sentiment_scores = [-85, 75, -80, 70, -65, -60, -55, -50, 65, 60]

importance_scores = [0.987, 0.876, 0.965, 0.789, 0.678, 0.564, 0.453, 0.345, 0.234, 0.123]

# Create the DataFrame
df = pd.DataFrame({
    'Topic': topics,
    'Sentiment Score': sentiment_scores,
    'Importance Score': importance_scores
})

print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Euro-dollar parity",
    "Impact of Fed rate hikes on USD strength",
    "USD and Euro exchange rate dynamics",
    "Euro's depreciation and implications",
    "US dollar's strength against Euro",
    "Impact of Euro and Dollar on travel expenses",
    "China's displacement of Europe in money markets",
    "US Treasury sanctions on cryptocurrency mixer",
    "Israel's currency strength against USD and Euro",
    "Economic implications of Euro's value"
]

sentiment_scores = [90, 85, 80, 75, 70, 65, 60, 55, -80, 50]

importance_scores = [0.988, 0.965, 0.876, 0.789, 0.678, 0.564, 0.453, 0.345, 0.234, 0.123]

# Create the DataFrame
df = pd.DataFrame({
    'Topic': topics,
    'Sentiment Score': sentiment_scores,
    'Importance Score': importance_scores
})

print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Efforts to challenge USD dominance (China & Russia)",
    "Euro's depreciation and potential impact on businesses",
    "Euro weakening against USD",
    "Global implications of de-dollarization",
    "Eurozone's response to inflation",
    "Impact of USD strength on non-US funds and companies",
    "Central bank policies affecting currency exchange rates",
    "Importance of stablecoins in decentralized finance",
    "Impact of global exchange rate fluctuations",
    "Market reactions to USD strength"
]

sentiment_scores = [-85, -80, -75, -70, -65, -60, -55, 75, -50, -45]

importance_scores = [0.987, 0.965, 0.876, 0.789, 0.678, 0.564, 0.453, 0.345, 0.234, 0.123]

# Create the DataFrame
df = pd.DataFrame({
    'Topic': topics,
    'Sentiment Score': sentiment_scores,
    'Importance Score': importance_scores
})

print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Euro falls below parity with the dollar",
    "Europe's energy crisis affects the euro",
    "Concerns rise as euro trades at two-decade low against the dollar",
    "Predictions of further euro depreciation against the dollar",
    "Impact of sinking euro on economy and inflation",
    "Crossing of the euro-dollar parity line",
    "Concerns over digital currencies affecting democracy",
    "Market analysis and trends of EUR/USD currency pair",
    "Impact of dollar strength on earnings growth",
    "EU regulations affecting stablecoins pegged to the dollar"
]

sentiment_scores = [95, 85, 90, 85, 80, 75, 65, -70, -75, 60]

importance_scores = [1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550]

# Create the DataFrame
df = pd.DataFrame({
    'Topic': topics,
    'Sentiment Score': sentiment_scores,
    'Importance Score': importance_scores
})

print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    'Topic': [
        "Dollar hits 20-year high as data support aggressive Fed",
        "Inflation tax hits $4.5tn in U.S., Europe amid global price hikes",
        "Why is the U.S. dollar so strong right now?",
        "Yen plunges to new 24-year low against US dollar",
        "Euro falls below parity with the US dollar. What's the impact?",
        "Americans getting deals on European homes due to strong dollar, exchange rate",
        "As the U.S. Dollar Surges, American Buyers Splurge on European Homes",
        "Chart Of The Day: Interest Rate Differential To Push Euro To 0.9500?",
        "Inflation in the euro area hit another record",
        "Could China's Yuan replace the U.S. dollar as the world's dominant currency?"
    ],
    'Sentiment Score': [90, -80, 85, 95, -100, 75, 85, 70, -95, 65],
    'Importance Score': [1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550]
}

# Create DataFrame
df = pd.DataFrame(data)

print(df)
#35

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    "Topic": ["Dollar Trading Near Two-Decade High Against Euro",
              "Dollar Gains, Euro Slips Further from Parity",
              "Strong U.S. Dollar Wreaking Havoc Globally",
              "U.S. Travelers Getting Bigger Discounts in Europe",
              "U.S. Dollar Rises vs Yen as Fed Reinforces Hawkish Stance",
              "Euro Weakly Depreciates Against Dollar",
              "Dollar Strength Lifts Americans' Relative Spending Power",
              "Dollar Eases Back from Recent Gains",
              "Dollar Slides as Investors Balance Positions",
              "Dollar Hits New 20-Year High Against Euro"],
    "Sentiment Score": [95, 85, 85, 80, 75, -70, 70, -65, -60, 55],
    "Importance Score": [0.114, 0.103, 0.098, 0.091, 0.086, 0.080, 0.074, 0.069, 0.063, 0.057]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    "Topic": ["US Dollar Strength Driven by Economic and Geopolitical Uncertainty",
              "Impact of European Energy Crisis on Currency Markets",
              "Euro's Response to Hawkish ECB Signals and Weakening Dollar",
              "US Dollar Continues to Strengthen Against Major Currencies",
              "Concerns Over Rising US Inflation and Its Effect on Dollar Value",
              "Uncertainty Surrounding US Auto Industry Exports Due to Strong Dollar",
              "Impact of US CPI Shock on Dollar's Performance",
              "Market Response to Rising US Treasury Yields and Dollar's Surge",
              "Euro's Rally Amid Ukraine Developments and ECB Rate Outlook",
              "Global Economic Slowdown and Inflation Concerns Amid Dollar Surge"],
    "Sentiment Score": [90, -80, 85, 75, -70, -65, -60, 70, 75, -55],
    "Importance Score": [0.300, 0.280, 0.250, 0.220, 0.190, 0.165, 0.140, 0.120, 0.100, 0.080]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    "Topic": ["USD hits two-decade high against Euro",
              "Euro plummets amid war in Ukraine",
              "Fed raises interest rates, Dollar surges",
              "Nations struggle against strong US Dollar",
              "China accelerates regional de-dollarization",
              "Eurozone business activity contracts, Euro weakens",
              "Euro payment flows shrink as Dollar strengthens",
              "Sterling and Euro hit multi-year lows against Dollar",
              "Russia's Ruble gains against Dollar",
              "Central banks raise rates to combat inflation"],
    "Sentiment Score": [95, 90, 90, -85, -80, -75, -70, -65, 60, 55],
    "Importance Score": [1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Bank of England's impact on Sterling",
              "ECB's stance on price stability",
              "Brexit's effect on British Pound",
              "USD share of global FX reserves",
              "US Dollar's strength amid recession worries",
              "Impact of global currency chaos on Canadian economy",
              "ECB's initiatives for inflation control",
              "Eurozone inflation reaching record highs",
              "Swiss Franc's impact on EUR",
              "US dollar's influence on global financial markets"],
    "Sentiment Score": [60, 50, -70, 40, 80, -50, 40, -70, -30, 70],
    "Importance Score": [0.335, 0.163, 0.138, 0.115, 0.098, 0.093, 0.082, 0.078, 0.066, 0.058]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "Interest rate hikes in the US and Eurozone",
        "EU crypto rules limiting dollar-pegged stablecoins",
        "US dollar supremacy as the world's currency",
        "European Central Bank rate increase",
        "US dollar strength affecting global currencies",
        "US dollar's impact on corporate earnings",
        "Eurozone inflation concerns",
        "EU-US data privacy deal",
        "Transatlantic tensions over Ukraine",
        "Dollar's record high against Nepalese currency"
    ],
    "Sentiment Score": [
        70, -65, 60, 70, -60, -55, -50, 50, -45, 55
    ],
    "Importance Score": [
        0.369, 0.350, 0.332, 0.315, 0.298, 0.281, 0.265, 0.249, 0.234, 0.220
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)
#40

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "Impact of a strong U.S. dollar on international travel",
        "Extension of currency swap agreement between China and EU",
        "Growth outlook downgrade by IMF",
        "Factors influencing U.S. dollar strength",
        "Eurozone defense industry challenges",
        "GBP/USD exchange rate impact on British expats",
        "Central bank actions affecting currency exchange rates",
        "Impact of Euro-USD equivalency on international students",
        "Concerns over Afghanistan's economic stability",
        "Swiss National Bank's draw on Fed swap line"
    ],
    "Sentiment Score": [
        70, -65, -60, 60, -55, -50, 50, 45, -40, 40
    ],
    "Importance Score": [
        0.378, 0.362, 0.346, 0.330, 0.314, 0.298, 0.282, 0.266, 0.250, 0.234
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    'Topic': ['Surging U.S. Dollar', 'Digital Euro and Digital Dollar', 'Real-Time USD-Euro Payments',
              'Record Trade Deficit in Europe', 'USD-Euro Exchange Rate Climbs', 'Impact of Surging US Dollar Globally',
              'Currency Indicator Development in Egypt', 'Anna May Wong on US Currency',
              'Economic Challenges Due to Strong Dollar', 'Impact of Strong Dollar on Blue Chip Companies'],
    'Sentiment Score': [80, 70, 65, -75, 60, -85, 50, 80, -90, -95],
    'Importance Score': [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    'Topic': ['European Central Bank Interest Rate Hikes', 'Euro-Dollar Parity', 'US Dollar Appreciation',
              'Currency Trading Volume Hits Record', 'Emerging Market Currency Instability',
              'Impact of ECB\'s Monetary Policy', 'US Dollar and Euro Exchange Rates',
              'UK Political Changes and Exchange Rates', 'Shift in FX Trading Hubs',
              'Euro Reaches Highest Value Against USD in Two Decades'],
    'Sentiment Score': [85, -80, 80, 75, -90, 70, 65, 60, 55, 50],
    'Importance Score': [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    'Topic': ['European Central Bank Monetary Policy', 'US Nonfarm Payrolls Report', 'Currency Volatility',
              'CME Group Launches €STR Futures', 'Oil Pricing Without Dollars',
              'Inflation in Europe', 'Iran\'s Currency Plunge', 'US Military Clinical Currency Program',
              'COP27 and Deforestation', 'Expiring Money as a Monetary Policy Tool'],
    'Sentiment Score': [85, -80, 80, 75, -90, 70, -65, 60, 55, 50],
    'Importance Score': [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    'Topic': ['European Central Bank Monetary Policy', 'US Nonfarm Payrolls Report', 'Currency Volatility',
              'CME Group Launches €STR Futures', 'Oil Pricing Without Dollars',
              'Inflation in Europe', 'Iran\'s Currency Plunge', 'US Military Clinical Currency Program',
              'COP27 and Deforestation', 'Expiring Money as a Monetary Policy Tool'],
    'Sentiment Score': [-85, 80, -80, -75, 90, -70, 65, -60, -55, -50],
    'Importance Score': [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)
#45

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    'Topic': ['European Central Bank Monetary Policy', 'US Economic Data', 'EU-US Trade Relations',
              'European Economy', 'Geopolitical Tensions', 'UK Inflation', 'Climate Change and COP27',
              'Currency and Energy Markets', 'Global Economic Outlook', 'Central Bank Policy'],
    'Sentiment Score': [-85, 80, -75, -70, 65, -60, -55, -50, -45, -40],
    'Importance Score': [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    'Topic': ['Interest Rate Differentials', 'Cybersecurity Investments in the EU', 'Geopolitical Tensions',
              'Space Agency Budget Increase', 'US Dollar Strength', 'Policy Responses to Strong Dollar',
              'Financial Outlook for 2023', 'EU Chip Funding Plan', 'EU Anti-Money Laundering Regulations',
              'Currency Exchange Rates'],
    'Sentiment Score': [-85, -80, -75, -70, 65, -60, -55, -50, -45, -40],
    'Importance Score': [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    'Topic': ['ECB Rate Hike Bets', 'Geopolitical Impacts', 'Cryptocurrency Regulation in the EU',
              'Eurozone Monetary Policy', 'Impact of USD Strength on EUR', 'EU-US Trade Relations',
              'China-Russia Yuan Settlement', "European Central Bank's Warnings", "Euro's Weakness Against USD",
              "EU's Rule-of-Law Concerns"],
    'Sentiment Score': [90, -85, -80, -70, 65, -60, -50, -45, -40, -30],
    'Importance Score': [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    'Topic': ['US Dollar Strength in 2023', 'Global Crackdown on Money Laundering',
              'Internationalization of Currency Trading', 'Corruption and Bribery Investigations',
              'Impact of Iran Unrest on Exchange Rates', 'Impact of Currency Pegs on Exchange Rates',
              'Impact of Exchange Rates on Shopping Overseas', 'Impact of Russia-Ukraine Conflict on Exchange Rates',
              'Impact of Sanctions on Russia on Exchange Rates', 'Impact of Central Bank Policies on Exchange Rates'],
    'Sentiment Score': [90, -85, -80, -70, -60, -50, 45, -40, -30, -20],
    'Importance Score': [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    'Topic': ['U.S. Dollar Strength in 2023', 'Impact of U.S. Inflation Reduction Act on EUR',
              'Impact of ECB Interest Rate Decisions on EUR', 'Global Concerns Over Strong Dollar Policy',
              'Impact of U.S. Corruption Scandals on EUR', 'Impact of Central Bank Digital Currencies on EUR',
              'Impact of Capital Flows on EUR/USD Exchange Rate', 'Impact of Eurozone Inflation on EUR/USD',
              'Impact of EU Corruption Scandals on EUR', 'Impact of Eurozone Economic Recovery on EUR/USD'],
    'Sentiment Score': [90, 80, 70, 60, 50, -40, -30, -20, 10, -5],
    'Importance Score': [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)
#50

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    'Topic': ['USD\'s Impact on Commodities and Earnings', 'EU and UK Price Cap on Russian Crude Oil',
              'Americans Traveling Abroad to Benefit from a Strong Dollar', 'Global Efforts to Circumvent the Strong Dollar',
              'Military Aid to Ukraine Amidst USD Diplomacy', 'Rise of Non-SDR Currency Reserves',
              'Impact of ECB Interest Rate Decisions on European Economy', 'EU\'s Need for Unity',
              'Cryptocurrencies and Sanctions Evasion', 'Digital Euro Concept Criticism'],
    'Sentiment Score': [90, 85, 80, 70, 60, 50, -40, -60, -70, -90],
    'Importance Score': [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    'Topic': ['Croatia Adopting Euro and Joining Schengen Area',
              'Chinese Yuan Surpassing Euro in Settlements Among Russian SMEs',
              'Impact of US Dollar\'s Status as World\'s Reserve Currency',
              'Euro\'s Appeal Enduring Amid Croatia Joining Eurozone',
              'China Cutting Weighting of Dollar and Euro in Yuan Basket',
              'Concerns and Skepticism About Croatia Joining Eurozone',
              'USD Outlook for 2023',
              'Market Impact of Ukraine War Turbulence Ending',
              'Impact of Fed Rate Hikes on US Dollar in 2023',
              'Dollar\'s Performance in 2022'],
    'Sentiment Score': [85, 80, 75, 70, 65, -60, 50, -40, -30, 25],
    'Importance Score': [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

print(len(bound))
bound=pd.DataFrame(bound)
bound.to_csv('eurusdscore2022.csv')

topics=pd.DataFrame([])
for i in range(52):
  topics=pd.concat([topics,raw_data[i].iloc[:,0]],ignore_index=True)
topics.to_csv('eurusdtopics2022.csv')