# -*- coding: utf-8 -*-
"""eur2023.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FKR7A31RZk6q2VTZE0_nrJquDX7nQ0lE
"""

from sklearn.preprocessing import MinMaxScaler
import numpy as np

def weekly_score(df):
  transfer=MinMaxScaler(feature_range=(0.1,0.5))
  df_1=np.array(df.iloc[:,2]).reshape(-1, 1)
  df_1=transfer.fit_transform(df_1)
  d=np.array(df.iloc[:,1])*df_1.reshape(1, -1)
  upper=int(sum(np.maximum(d,0).T))
  lower=int(sum(np.minimum(d,0).T))
  return upper,lower

bound=[]
raw_data=[]

import pandas as pd

# Creating the DataFrame
data = {
    'Topic': ['Croatia Adopting Euro and Joining Schengen Area',
              'Euro Climbing High Amid Global Economic Landscape',
              'Europe\'s New Climate Policy',
              'Impact of US Dollar\'s Status on Global Recession Prediction',
              'Euro\'s Strength Despite German Inflation',
              'Impact of Wall Street Predictions on Dollar',
              'USD/EUR Exchange Rate Forecast for 2023',
              'Impact of Currency Forecast on Dollar',
              'Dollar Performance in Global Economy',
              'Influence of US Economic Data on Dollar'],
    'Sentiment Score': [-90, -85, -80, -75, -70, -60, 55, 65, 75, 85],
    'Importance Score': [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

# Define the topics, sentiment scores, and importance scores
topics = [
    "Croatia adapting to the euro",
    "EU industry Clean Tech Act against America's green subsidies",
    "Crypto regulations in Singapore and the EU",
    "Romania's economy outpacing stagnating neighbours",
    "ESG accounts for 65% of all flows into European ETFs",
    "US Dollar and Euro Currency Trading",
    "Boom in US LNG exports to Europe",
    "Polish PM warns adopting euro would spike prices",
    "China, US, Europe betting on Green Hydrogen",
    "France's 'Made in Europe' strategy"
]

sentiment_scores = [-75, -80, -70, 60, 75, -90, -65, -85, 80, -75]
importance_scores = [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]


df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Euro becomes Moldova's main remittance currency",
    "Dollar-dominated global order is 'fading away'",
    "EUR/USD: We're giving our euro dollar forecast a factory reset",
    "U.S., EU authorities crush crypto exchange Bitzlato as $700 million Russian laundering hub",
    "Why EU Objects to US Green Subsidies, Tax Breaks: QuickTake",
    "Brazil and Argentina to start preparations for a common currency",
    "Italian Minister Giorgetti nominates Italy as the seat of the European anti-money laundering authority",
    "The Disappearing Japanese Bid for Global Bonds",
    "By the numbers: The de-dollarisation of global trade",
    "Central-Bank Digital Currencies Are Coming—Whether Countries Are Ready or Not",
]

sentiment_scores = [-85, -90, -80, -95, -75, 70, 60, -65, -70, -60]
importance_scores = [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]

# Create a DataFrame
df = pd.DataFrame({
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
})

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "The digital euro: our money wherever, whenever we need it",
    "Dollar slips as upbeat euro zone business activity data lifts euro",
    "Netherlands opposes new EU money to counter US green subsidies",
    "The quiet, unexpected vindication of the euro",
    "US, EU Seize Crypto Exchange Used by Russian Criminals",
    "Could the “Sur” become the Euro of Latin America?",
    "The Dollar Will Vanquish Pretenders to Its Throne",
    "Dutch PM Rutte wants EU to play it frugal in face of mega US subsidies",
    "Test your knowledge",
    "The sur: Argentina, Brazil put common currency plan on ice"
]

sentiment_scores = [-80, -70, -90, 60, -95, -75, 85, -85, 0, -65]
importance_scores = [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]

# Create a DataFrame
df = pd.DataFrame({
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
})

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create DataFrame
data = {
    "Topic": ["Ray Dalio warns about the future of money",
              "EU announces Green Deal Industrial Plan",
              "EU unveils plan to counter US spending spree",
              "Europe shows slight economic growth",
              "Discussion on top 10 most traded currencies",
              "Debate on European response to US subsidies",
              "Dollar's impact on hedging costs for U.S. companies",
              "EU's struggle to keep up with the US on green subsidies",
              "EU's efforts to compete in green tech race with the US",
              "EU's conflict with Big Pharma to lower medicine prices"],
    "Sentiment": [-80, 50, 60, 20, 40, -30, -10, -40, 70, -20],
    "Importance": [0.536, 0.951, 0.912, 0.786, 0.659, 0.478, 0.725, 0.612, 0.843, 0.564]
}

df = pd.DataFrame(data)

# Print DataFrame
print(df)
#5

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the adjusted matrix
data_adjusted = {
    "Topic": [
        "Euro's comeback against the US dollar",
        "Global role of the euro",
        "US jobs report boosts the dollar against the euro",
        "Decline of the US dollar",
        "Euro's rapid decline against G-10 currencies",
        "Impact of global central bank rate hikes",
        "Effects of the US dollar's slide on European stocks",
        "Payment preferences in the euro area",
        "Interest in wholesale central bank digital currency",
        "Prediction of future dominant currency"
    ],
    "Sentiment Score": [
        -65.342, -52.678, -78.905, 84.219, 76.501,
        -67.845, -43.290, -28.753, -36.124, -79.462
    ],
    "Importance Score": [
        0.932, 0.876, 0.982, 0.794, 0.725,
        0.901, 0.856, 0.647, 0.723, 0.988
    ]
}

# Creating the adjusted DataFrame
df = pd.DataFrame(data_adjusted)

# Displaying the adjusted DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "US Dollar Strengthens on Strong Economic Data",
        "Europe's Consideration of Digital Currency",
        "Euro's Decline Amid ECB's Digital Currency Plans",
        "European Parliament Debate on ECB Annual Report",
        "Morgan Stanley's Optimism on Euro Strength",
        "Eurozone Growth and Expansion",
        "South America's De-dollarization Efforts",
        "Concerns over US Dollar's Recent Slide",
        "EU's Transparency Laws and Lobbying Regulation",
        "European Energy Crisis and Spending"
    ],
    "Sentiment Score": [
        89.765, -54.320, -73.498, -42.569, 68.213,
        63.421, -76.109, -78.632, -32.457, -39.234
    ],
    "Importance Score": [
        0.978, 0.925, 0.901, 0.876, 0.853,
        0.821, 0.789, 0.757, 0.723, 0.692
    ]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    'Topic': ['Russia\'s invasion of Ukraine',
              'European Union\'s frozen assets of Russian Central Bank',
              'Strength of the US dollar affecting UK investors',
              'Aid provided to Ukraine by the West',
              'Availability of currency exchange services',
              'Iran\'s economic crisis and currency depreciation',
              'Inflation rates of various countries',
              'Sanctions against Russia and impact on its economy',
              'Flight refund issues with Lufthansa',
              'Export of food commodities amid Ukraine-Russia war'],
    'Sentiment Score': [-90, -80, 70, 40, 20, -90, -10, -80, -20, 10],
    'Importance Score': [0.181, 0.125, 0.088, 0.063, 0.032, 0.032, 0.032, 0.032, 0.032, 0.032]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    'Topic': ['Commodity currencies gain on China optimism',
              'CBDC (Central Bank Digital Currency)',
              'Investment attractiveness of UK compared to US and EU',
              'Saving money on college tuition by going to Europe',
              'Top AML fines in 2022',
              'Yuan becoming an international currency',
              "Switzerland's inflation success",
              "Google's EU antitrust attack",
              "Dollar's temporary strength according to analysts",
              "Talks about a common currency for Latin America"],
    'Sentiment Score': [45.000, 10.000, -25.000, 35.000, 0.000, 55.000, 40.000, -15.000, 5.000, 15.000],
    'Importance Score': [0.586, 0.559, 0.620, 0.663, 0.445, 0.711, 0.614, 0.501, 0.533, 0.577]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    'Topic': ['Effect of Russian rouble tumble on USD/EUR exchange rate',
              'Impact of U.S. jobs data on USD weakening',
              'Preference of Chinese companies for Switzerland over the US and UK',
              'Potential risks of T+1 settlement in Europe on ETF spreads',
              'Accelerated efforts on the Capital markets union in Europe',
              'Concerns about FX hedging costs affecting Japanese investment in the US',
              'Transition to a cashless Europe and its impact on the USD/EUR exchange rate',
              'Speculation on the impact of Russia sanctions on the USD/EUR exchange rate',
              'EU subsidy race with the US to retain green projects',
              'Impact of European banks\' performance on the USD/EUR exchange rate'],
    'Sentiment Score': [-60.000, -35.000, 20.000, -10.000, 25.000, -5.000, 15.000, -30.000, 10.000, -20.000],
    'Importance Score': [0.162, 0.354, 0.191, 0.285, 0.122, 0.213, 0.243, 0.134, 0.313, 0.185]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)
#10

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    'Topic': ['ECB raises interest rates, leading to USD weakening and EUR strengthening',
              'Central bank action to enhance USD liquidity',
              'Impact of currency appreciation on prices: rise of the U.S. dollar',
              'European competition in green initiatives',
              'Market reactions to U.S. bank failures',
              'Concerns about de-dollarization and economic consequences',
              'Impact of European banking sector stability on USD/EUR exchange rate',
              'Global market stress and its effect on USD/EUR',
              'Gold prices rise amid weaker dollar and banking worries',
              'Impact of SVB collapse on USD and global financial markets'],
    'Sentiment Score': [-70.000, 15.000, 10.000, 20.000, -25.000, -40.000, -15.000, -20.000, 25.000, -35.000],
    'Importance Score': [0.405, 0.162, 0.233, 0.294, 0.120, 0.091, 0.348, 0.181, 0.057, 0.224]
}

df = pd.DataFrame(data)

# Print the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data
data = {
    'Topic': ['European banking jitters weaken euro and sterling against a strengthening dollar',
              'Shift towards renminbi in response to western sanctions impacts USD/EUR exchange rate',
              'EU leaders downplay banking risks amidst weak economy',
              'USD remains dominant, impacting USD/EUR exchange rate',
              'Speculation about potential threats to USD dominance',
              'De-dollarization trends affecting global currency dynamics',
              'Regulatory actions against cryptocurrency mixers influence USD/EUR exchange rate',
              'Market turmoil and banking stress impact USD/EUR',
              'Central bank policies and their effect on USD/EUR',
              'Economic growth and inflation affecting USD/EUR exchange rate'],
    'Sentiment Score': [70.000, -20.000, -10.000, 40.000, -25.000, -30.000, -10.000, -15.000, 15.000, 20.000],
    'Importance Score': [1.000, 0.788, 0.576, 0.364, 0.264, 0.152, 0.112, 0.088, 0.056, 0.024]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a list of tuples containing the topics, sentiment scores, and importance scores
topics_data = [
    ("US dollar replaces euro as Brazil's second currency", 60, 1.000),
    ("Record money pulled from eurozone banks in February", -70, 0.923),
    ("European lawmakers cap on anonymous crypto transactions", -50, 0.846),
    ("Decline in US dollar's share as global reserve currency", -60, 0.769),
    ("De-dollarization concerns and global alliances", -30, 0.692),
    ("US becomes top crude oil supplier for Europe", 40, 0.615),
    ("Concerns over de-dollarization and financial stability", -20, 0.538),
    ("De-Dollarization skepticism and financial stability", -20, 0.462),
    ("Efforts to stabilize banking sector boost USD", 30, 0.385),
    ("Market optimism and USD rebound", 40, 0.308)
]

# Create a DataFrame from the list of tuples
df = pd.DataFrame(topics_data, columns=["Topic", "Sentiment Score", "Importance Score"])

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
topics = [
    "Travel to Europe is no longer a 'screaming, bargain-basement' deal",
    "Euro-U.S. dollar exchange rate hits parity for the first time since 2002",
    "China's Yuan Replaces Dollar as Most Traded Currency in Russia",
    "African countries face shortage of US dollars",
    "ECB's Lagarde reveals limited control over digital euro",
    "U.S. dollar slumps after weak economic data",
    "Exchange rate volatility and monetary policy",
    "US-EU diplomatic remarks",
    "British Pound leads European currency rebound",
    "RMB Yuan vs the US Dollar: Implications for the Greenback's Dominance"
]

sentiment_scores = [-50, -90, -60, -40, -20, -70, 0, 20, 40, -30]
importance_scores = [0.923, 1.000, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]

# Create DataFrame
df = pd.DataFrame({
    'Topic': topics,
    'Sentiment Score': sentiment_scores,
    'Importance Score': importance_scores
})

print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data for the matrix
data = {
    "Topic": ["US Dollar Weakens Ahead of Inflation Data", "Dollar Dips as Inflation Cools", "Dollar Drops to 2-Month Low Against Euro", "US Dollar Index Dips on Cooling Producer Prices", "Dollar Pauses Amid Hawkish Fed Bets", "Dollar Eases as US Inflation Cools", "Dollar Collapses to Yearly Low", "Dollar Slides to 1-Year Low", "Dollar Loses Steam on Fed Pause Expectation", "Dollar Jumps on Strong Manufacturing Survey"],
    "Sentiment Score": [-70, -50, -70, 20, 40, 0, -90, -30, -40, 40],
    "Importance Score": [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)#15

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data for the matrix
data = {
    "Topic": ["Dollar May Fall to Yuan, Crypto But Not Soon", "Dollar's Dominance Eroded at 10 Times the Pace", "De-Dollarization Is Happening at a 'Stunning' Pace", "Anti-Dollar Drive Spreads to Europe", "Central banks in a fragmenting world", "Euro, dollar status should not be taken for granted", "US-China economic rivalry leaves EU squeezed", "BRICS Is Coming Together to Challenge the U.S. Dollar", "US-China split may weaken growth and fuel inflation", "Is the U.S. dollar still a viable reserve currency?"],
    "Sentiment Score": [-80, -60, -90, -70, -50, -40, 20, 30, 40, 60],
    "Importance Score": [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dataframe
data = {
    "Topic": ["Digital Euro Project", "Calls to move away from USD", "Dollar weakens on fresh signs of slowdown",
              "BRICS Currency Could End Dollar Dominance", "Eurozone Economic Integration", "US Dollar Defense",
              "Gas Industry Influence on Policy Priorities", "EU, US, UK Sanctions against Russia",
              "Cross-Border Anti-Money Laundering Legislation", "Global Money Market Funds Inflows"],
    "Sentiment Score": [-80, -70, -60, -50, 70, 60, -80, -70, 50, 70],
    "Importance Score": [0.192, 0.180, 0.168, 0.156, 0.144, 0.132, 0.120, 0.108, 0.096, 0.084]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    'Topic': [
        "European Central Bank raises interest rates",
        "U.S. Federal Reserve hikes rates",
        "Chinese efforts to internationalize the yuan",
        "Dollar's depreciation against the euro",
        "Concerns over the U.S. dollar's role as a reserve currency",
        "Global shift away from the U.S. dollar",
        "Economic implications of yuan not replacing the dollar",
        "Impact of fintech on traditional banking and currency markets",
        "ASEAN considering dropping USD/EUR in favor of local currencies",
        "Euro's stability amidst currency fluctuations"
    ],
    'Sentiment Score': [
        -70, -60, 60, -80, -50, 70, -30, 40, 20, 50
    ],
    'Importance Score': [
        0.290, 0.289, 0.287, 0.286, 0.285, 0.284, 0.283, 0.282, 0.281, 0.280
    ]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dataframe
data = {
    "Topic": ["ECB Raises Interest Rates", "Federal Reserve Rate Decisions",
              "US Dollar Strengthens Against Euro", "De-dollarization Efforts",
              "Global Currency Power Shift", "China's Yuan Globalization Efforts",
              "European Central Bank Policy Decisions", "ASEAN Considering Currency Trade Decision",
              "US Banking Concerns", "Digital Euro Project"],
    "Sentiment Score": [70, -60, 80, -50, 70, -70, -60, -80, -70, 80],
    "Importance Score": [0.247, 0.239, 0.198, 0.160, 0.127, 0.115, 0.092, 0.084, 0.072, 0.066]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data for the matrix
data = {
    "Topic": ["Euro's Use in International Payments Drops", "De-dollarization: Alternative assets", "US dollar skids as Fed's Powell hints", "Is France Backing China's Currency", "Why the dollar's dominance is declining", "Do we need the digital euro?", "The end of dollar supremacy", "A new Brics currency", "The digital euro: a solution seeking a problem?", "De-dollarization: What Happens if the Dollar Loses"],
    "Sentiment Score": [60, -90, -40, -80, -70, -20, -50, -30, 40, 70],
    "Importance Score": [1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)
#20

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": ["De-dollarization", "US Dollar's Dominance Under Threat", "Inflation",
              "US debt default risk", "European Union's debt credibility problem",
              "U.S. Dollar's Strength", "US Monetary Policy Outlook",
              "Flight Prices to Europe Soar", "ASEAN Currency Transactions Increase",
              "Central Banks' Emergency Actions"],
    "Sentiment Score": [-90, -80, -70, -70, -60, 70, 60, -50, 50, 40],
    "Importance Score": [1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600,0.55]}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    'Topic': ["Traveling overseas becoming more expensive",
              "Disintegration of the world financial system",
              "Euro's historic downfall",
              "Euro rebounds against USD from two-month low",
              "Impact of BRICS currency on USD hold",
              "Federal Reserve officials suggest skipping rate hike",
              "EU unveils new Western Balkans support plan",
              "Dollar backs off highs after Fed officials' comments",
              "Dollar eases as deal over US debt ceiling",
              "Dollar Outlook: USD Is Overbought"],
    'Sentiment Score': [-80, -70, 90, 70, -60, -50, 60, 40, 50, 30],
    'Importance Score': [0.250, 0.363, 0.500, 0.625, 0.750, 0.875, 0.938, 0.313, 0.188, 0.63]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    'Topic': ["Eurozone economy enters technical recession",
              "European Central Bank's policy impact on EUR/USD",
              "Euro's value against the US dollar",
              "Dollar dominance in global trade",
              "EU's regulatory framework for cryptoassets",
              "Impact of US economic policies on EUR/USD",
              "European stocks outperforming US equities",
              "Eurozone's struggle with inflation",
              "Central banks' interventions affecting EUR/USD",
              "Geopolitical tensions and EUR/USD volatility"],
    'Sentiment Score': [-80, -70, -60, -50, 70, -40, 60, -30, 50, -20],
    'Importance Score': [1.000, 0.938, 0.875, 0.813, 0.750, 0.688, 0.625, 0.563, 0.500, 0.438]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    'Topic': ["US wants Europe to buy American weapons",
              "Yen sags to 15-year low vs euro after BOJ rate decision",
              "Traditional vs digital development multilateralism",
              "Strength of USD and its impact on global currencies",
              "European Union's antitrust complaint against Google",
              "Factors affecting the value of Turkish lira",
              "EU's leaked digital euro bill and its implications",
              "Investment trends in Japan",
              "US Treasury's findings on currency manipulation",
              "Impact of Russia's nuclear agency on USD payments"],
    'Sentiment Score': [60, -75, 5, 85, -70, -80, 20, 75, 90, -40],
    'Importance Score': [0.235, 0.248, 0.212, 0.267, 0.224, 0.255, 0.196, 0.258, 0.280, 0.217]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    'Topic': ["The international role of the euro",
              "The international role of the U.S. dollar",
              "US dollar doomsayers",
              "Dollar higher on safety bid",
              "The dollar as the world's default currency",
              "Leading international currency replacement",
              "Euro's position as a reserve currency",
              "Euro's resilience on the world stage",
              "Geopolitical fragmentation risks and international currencies",
              "Determinants of currency choice in cross-border bank loans"],
    'Sentiment Score': [60, 70, -50, 80, 90, 20, 75, 85, -40, 30],
    'Importance Score': [0.268, 0.280, 0.209, 0.301, 0.325, 0.186, 0.297, 0.312, 0.177, 0.230]
}

df = pd.DataFrame(data)
print(df)
#25

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": [
        "Central Bank Actions on Yuan and USD/EUR Exchange Rate",
        "Euro's Stability Amid Global Issues",
        "Effect of Economic Data on USD and EUR",
        "Inflation and Central Bank Policies in Eurozone",
        "EU's Digital Currency Plans and Impact on Euro",
        "US Dollar's Dominance and Future Projections",
        "Global Efforts to Diversify Currency Reserves",
        "Bulgaria's Interest in Euro Adoption",
        "Geopolitical Dynamics Affecting USD and EUR",
        "EU Legislation on Digital Euro and Privacy"
    ],
    "Sentiment Score": [
        -80, 60, -40, -50, 70, 50, -30, 40, 20, 60
    ],
    "Importance Score": [
        1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    'Topic': [
        "US Dollar Weakens Against Euro Amid Rate Hike Expectations",
        "Pound Sterling Expected to Slip Against Euro",
        "Euro's Fundamental Equilibrium Exchange Rate Near 0.94",
        "Euro Strengthens Against Weakening Pound and Dollar",
        "Euro-Pound Exchange Rate Forecast",
        "Dollar Stability After ISM Data",
        "External Catalysts Weighing on US Dollar in Q3",
        "US Dollar Drops to Three-Week Low Amid Rate Hike Expectations",
        "Dollar Gains After Fed Minutes",
        "Dollar Weakens as US Job Growth Slows"
    ],
    'Sentiment Score': [
        -80, -60, 70, 60, 50, -30, -40, -50, 20, -10
    ],
    'Importance Score': [
        1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "Euro Banknote Themes Survey by ECB",
        "US Dollar Weakness Against Global Currencies",
        "Adequacy Decision for EU-US Data Flows",
        "US-EU Cooperation on Methane Emissions Reduction",
        "New US Sanctions Against Myanmar Banks",
        "Creation of BRICS Currency and Global Financial Impact",
        "Data Sharing Pact Between EU and US",
        "Tourism Rebound in Europe",
        "Impact of Inflation and Travel Costs on European Travel",
        "US Dollar Status as Global Reserve Currency"
    ],
    "Sentiment Score": [20, -90, 50, 70, -70, 60, 70, 80, -60, -30],
    "Importance Score": [0.213, 0.359, 0.154, 0.139, 0.256, 0.171, 0.130, 0.094, 0.171, 0.123]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "Euro Set for Longest Rally in Almost Two Decades as Dollar Sinks",
        "Dollar bounces from 15-month low on strong core U.S. retail sales",
        "Europe Poorer, U.S. Richer as Wage Gap Widens - What's News",
        "EU, US Sanctions Aim to Curb Funds for War in Myanmar",
        "Europe's dwindling wealth, increasing austerity",
        "US Dollar and European euro experience minor decline, British Pound Sterling stable on Saturday",
        "More Oil Sales Move to Non-Dollar Currencies",
        "US Fed fines Deutsche Bank $186 million for slow progress against money laundering",
        "US Dollar gains as drop in US jobless claims boosts rate-hike bets",
        "Complete guide to earning and redeeming Avianca LifeMiles"
    ],
    "Sentiment Score": [-90, -80, -50, -70, -40, -20, -10, -60, 80, 10],
    "Importance Score": [0.901, 0.903, 0.902, 0.904, 0.906, 0.907, 0.909, 0.911, 0.912, 0.913]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Central bank meetings impact on USD", "European Central Bank interest rate hike",
              "USD depreciation affecting Latin American economies", "USD relationship with its economy",
              "Euro and Pound rebound against USD", "US dollar losing appeal as global reserve currency",
              "BIS global liquidity indicators", "Euro regains momentum against Albanian lek",
              "US dollar strengthens against euro", "Federal Reserve rate hike impact on USD"],
    "Sentiment Score": [50, -60, -70, 40, 60, -30, -20, 40, 70, 50],
    "Importance Score": [0.191, 0.164, 0.141, 0.121, 0.111, 0.095, 0.086, 0.078, 0.072, 0.067]
}

df = pd.DataFrame(data)
print(df)
#30

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data
data = {
    'Topic': ["Dollar gains after relatively strong data, Aussie dollar tumbles",
              "Rising Money Flows, Fueled by Record Migration, Prop Up Autocrats",
              "Europe’s economy is growing again as inflation continues to fall",
              "US Dollar likely to maintain its position against foreign currencies over next 3 months, says Reuters Survey | Mint",
              "Euro To Dollar Year-Ahead Forecast: 'Around 1.12' Say Berenberg",
              "EUR/USD Weekly Forecast: Inflation to confirm or deny an interim bottom",
              "Euro Area Growth Ticks Higher; EUR/USD Holds Above 1.1000",
              "US Dollar Index: DXY bulls are still in the game around 102.50 as yields remain firmer ahead of US NFP",
              "Dubai gold price today: Rates in UAE near lowest level in a week",
              "Gold at three-week low as higher dollar, yields dim shine"],
    'Sentiment Score': [70.000, -50.000, 80.000, 70.000, -60.000, -20.000, 60.000, 40.000, 40.000, -70.000],
    'Importance Score': [1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550]
}

# Create DataFrame
df = pd.DataFrame(data)

# Print DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    "Topic": [
        "Impact of Moody's downgrade and Chinese data on USD",
        "Deflation in China and its global implications",
        "BRICS summit and de-dollarization talks",
        "EU trade patterns and economic globalization",
        "US inflation report anticipation and USD movement",
        "Moroccan Dirham's performance against USD and EUR",
        "Australian dollar's decline against EUR",
        "Forecasts on EUR/USD exchange rate",
        "Impact of US inflation on EUR/USD exchange rate",
        "Euro's response to US CPI and energy prices"
    ],
    "Sentiment Score": [
        80, -30, 60, 70, -40, 50, -50, 40, -30, -20
    ],
    "Importance Score": [
        1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550
    ]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    "Topic": [
        "US Dollar near two-month high against Euro",
        "US Dollar Index Reaches Key Decision Point",
        "DXY: US Dollar Index Picks Up Momentum",
        "US Dollar index at crossroads",
        "US Dollar stays close to multi-month highs",
        "Dollar jumps, oil slides on China worries",
        "Dollar hits highest in more than a month on China economy concerns",
        "Dollar slips on black market",
        "Dollar plunges against dong",
        "Dollar firm, yuan slides after China unexpectedly cuts rates"
    ],
    "Sentiment Score": [
        80, 70, 60, -10, 20, -30, -40, -50, -70, -60
    ],
    "Importance Score": [
        0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550, 0.500
    ]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Creating the DataFrame
data = {
    "Topic": [
        "US Dollar near two-month high against Euro",
        "Dollar retreats as data shows US economy near stalling point",
        "Dollar Usage in Global Payments in July Rises to Record",
        "Dollar firm as traders look to Jackson Hole gathering",
        "US dollar weakens as other countries raise their own interest rates",
        "US Dollar gets hammered as US PMI points to a contraction",
        "Dollar slips on black market",
        "Dollar index dips, briefly hits 9-month high against yen",
        "Dollar rises ahead of Jackson Hole, Turkish lira rallies",
        "Dollar steady as Fed's Powell says higher rates may be needed"
    ],
    "Sentiment Score": [
        90, -60, 80, 70, -70, -80, -50, 60, 50, 40
    ],
    "Importance Score": [
        1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550
    ]
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": [
        "Euro To Dollar Forecast: 1.04 By 2024 Say RBC Capital Markets",
        "Euro To Dollar Forecast: Support To Hold At 1.0760",
        "US Dollar Falls Against Euro And Pound On Weak US Data",
        "US Dollar turns two-faced ahead of Friday's NFP",
        "Dollar drops on jobs data, yen rises from 10-month low",
        "Dollar gains on solid data, euro drops on cautious ECB comments",
        "Traders Are Bailing on the Euro as End to ECB Hikes Draws Near",
        "EUR/USD Slides as Euro Area Makes Progress on Core Inflation",
        "EUR/USD: Bears Setting up Bull Trap",
        "EUR/USD attempts some consolidation near term"
    ],
    "Sentiment Score": [
        -90, -85, -75, -70, -65, -60, -50, -45, -40, -35
    ],
    "Importance Score": [
        0.832, 0.826, 0.816, 0.800, 0.788, 0.774, 0.764, 0.752, 0.740, 0.724
    ]
}

df = pd.DataFrame(data)
print(df)
#35

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a DataFrame
data = {
    "Topic": ["Euro weakens against USD for eight weeks", "Launch of digital euro project",
              "European aid to Ukraine surpasses US aid", "Impact of uncoordinated economic policies",
              "Strengthening of US dollar", "Comparison of inflation fight in EU vs US",
              "Interview insights on inflation outlook", "EU budget revision due to Ukraine war",
              "Wall Street preference for EU banking rules", "Russian central bank's currency sales"],
    "Sentiment Score": [-70, 10, 50, -30, 80, -20, 30, 20, 40, -10],
    "Importance Score": [0.087, 0.041, 0.071, 0.046, 0.089, 0.048, 0.051, 0.052, 0.055, 0.057]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data
data = {
    "Topic": ["ECB Raises Interest Rates", "International Sanctions Impact on USD Role",
              "Strong Dollar Amid ECB Announcement", "Euro Struggles Against Robust Dollar",
              "Economic Outlook and ECB Rate Decisions", "USD Strength against Euro Despite ECB Moves",
              "Inflation Impact on USD/EUR Exchange Rate", "Eurozone Economic Woes and ECB Decisions",
              "USD and EUR Performance Amid Global Factors", "Green Subsidies and USD/EUR Exchange Rate"],
    "Sentiment Score": [80, -70, 75, -80, -60, 70, -50, -65, 60, 50],
    "Importance Score": [0.250, 0.100, 0.150, 0.200, 0.050, 0.075, 0.070, 0.030, 0.025, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": ["USD strength driven by robust growth",
              "Impact of Fed's interest rate decisions",
              "Euro vulnerability post-FOMC",
              "Euro outlook amid ECB messages",
              "German business sentiment and the Euro",
              "Impact of US aid on Ukrainian economy",
              "Dollar index movements and economic resilience",
              "Euro-Dollar exchange rate forecast",
              "Fed's hawkish stance and Dollar strength",
              "EU's response to geopolitical tensions"],
    "Sentiment Score": [90, 80, -70, -60, 70, 60, 85, 50, 90, -80],
    "Importance Score": [0.577, 0.671, 0.734, 0.781, 0.828, 0.874, 0.920, 0.967, 1.000, 0.533]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": [
        "Dollar Strengthens to 10-Month High",
        "US Bond Yields Surge",
        "Euro Under Pressure Amidst Dollar Rally",
        "Impact of US Government Shutdown on Dollar",
        "Rising US Treasury Yields Support Dollar",
        "Dollar Hits 10-Month High",
        "Fed's Monetary Policy Impact on USD",
        "Gold Prices Decline Amid Dollar Surge",
        "Impact of Rising Oil Prices on EUR/USD",
        "Market Fear Drives Bearish Sentiment for EUR/USD"
    ],
    "Sentiment Score": [90, 80, -80, -70, 70, 80, 70, -70, -60, -60],
    "Importance Score": [0.137, 0.132, 0.127, 0.122, 0.117, 0.113, 0.108, 0.103, 0.098, 0.093]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": [
        "European leaders unable to fully replace U.S. support",
        "Euro-Dollar recovery anticipated by UniCredit",
        "Investor loyalty to European biotech",
        "Theft of $10,000 wallet with U.S. and European currency",
        "Hackers steal $20 million from Revolut",
        "U.S. commitment to aid Ukraine",
        "Hungarian proposal to split EU package for Ukraine",
        "U.S. pressure on Ukraine to counter corruption",
        "Confidence in continued U.S. support for Ukraine",
        "New EU deal affecting Ireland's migrant policies"
    ],
    "Sentiment Score": [-70, 80, 70, 0, -80, 70, -60, -70, 80, 0],
    "Importance Score": [0.120, 0.130, 0.110, 0.090, 0.100, 0.140, 0.080, 0.070, 0.150, 0.100]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)
#40

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create DataFrame with topic, sentiment score, and importance score
data = {
    'Topic': ['Euro expected to fall to parity with US dollar',
              'European Central Bank\'s digital euro initiative',
              'Potential adoption of local currencies for oil purchases',
              'Discussions on adopting euro and dumping krona in Sweden',
              'European Parliament approves additional funds for Ukraine',
              'Mastercard\'s initiatives impacting finance and currencies',
              'US companies preparing for EU climate disclosure rules',
              'Chinese yuan surpassing euro in SWIFT currency rankings',
              'Ferrari accepting Bitcoin payments in the US and Europe'],
    'Sentiment Score': [-80, 70, -30, 50, 20, 30, -10, 30, 20],
    'Importance Score': [0.300, 0.250, 0.200, 0.150, 0.100, 0.080, 0.060, 0.040, 0.030]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the data
data = {
    'Topic': ['Dovish Fed remarks and its impact on USD/EUR exchange rate',
              'Support for African railway development by the US and EU',
              'Impact of higher interest rates on borrowers and its effect on USD/EUR',
              'Suspension and reversal of Palestinian aid by the EU',
              'Forecast and market sentiment regarding EUR/USD exchange rate',
              'Impact of Russian ruble surge on USD/EUR exchange rate',
              'Geopolitical events affecting the USD/EUR exchange rate',
              'Economic disparities between European doctors\' salaries and their US counterparts',
              'Speculation on alternative currencies such as BRICS currency',
              'Impact of US economic data and geopolitical tensions on USD/EUR exchange rate'],
    'Sentiment Score': [-80, 50, -60, -40, 70, 30, -20, -10, 20, -30],
    'Importance Score': [0.384, 0.217, 0.213, 0.170, 0.104, 0.079, 0.061, 0.045, 0.040, 0.028]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create DataFrame
data = {
    'Topic': ['US dollar rises as risk sentiment sours',
              'European Central Bank halts rate hikes',
              'EU\'s green funding compared to US IRA',
              'ECB ends consecutive rate hikes despite inflation risks',
              'Euroclear profits from frozen Russian assets',
              'US startups invest in UK startups',
              'European payment firms face investor exodus',
              'Japan to end negative rate policy',
              'Zimbabwe loses billions to EU sanctions',
              'Russia\'s currency crisis impacts global markets'],
    'Sentiment Score': [60, -30, 20, -20, 40, 30, -10, 10, -50, -40],
    'Importance Score': [0.400, 0.350, 0.300, 0.250, 0.200, 0.150, 0.100, 0.050, 0.025, 0.010]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create DataFrame
data = {
    'Topic': ['US dollar weakens as markets believe Fed is done hiking rates',
              'US dollar tumbles to six-week low after soft jobs data',
              'Eurozone economy lags behind US recovery',
              'Europe\'s economic slowdown contrasts with US growth',
              'Fed holds interest rates, hints at possible tightening',
              'European Union\'s Global Gateway initiative',
              'US-China tensions impact global currency dynamics',
              'European payment firms face investor exodus',
              'Japan considers policy adjustment amid global economic shifts',
              'BRICS currency potential challenges USD dominance'],
    'Sentiment Score': [-80, -70, -60, -50, -40, 30, -20, -10, 10, 20],
    'Importance Score': [0.400, 0.350, 0.300, 0.250, 0.200, 0.150, 0.100, 0.050, 0.025, 0.010]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    'Topic': ['US Dollar rebounds after sharp selloff, weak data hurts euro',
              'Dollar gains after Powell warns on rates, yen at one-week low',
              'Dollar bounces after sharp selloff, weak data hurts euro',
              'Crack in US dollar strength to spread as economy slows: Reuters poll',
              'Dollar rebounds, Fed officials take center stage',
              'Europe\'s economic slowdown contrasts with US growth',
              'US-China tensions impact global currency dynamics',
              'Euro to Dollar Forecast 2024: Large Swings Around 1.08, say Nordea',
              'Central bank digital currency evolution in 2023: From investigation to preparation',
              'European Union\'s Global Gateway initiative'],
    'Sentiment Score': [80, 70, 60, -50, 40, -30, -20, 10, 0, 20],
    'Importance Score': [1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)
#45

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    'Topic': ["US-China currency wars in unstable lull",
              "Dollar steady as U.S. jobless claims boost Fed rate cuts",
              "Chinese Yuan Passes Euro as Second Top Trade Currency",
              "US-EU unity ruptures over climate damage payments",
              "Importance of US CPI inflation data",
              "CBDCs could threaten the dollar",
              "Euro to Dollar Outlook: 'Advance to 1.1500 in 2024'",
              "Euro to Dollar Week Ahead Forecast",
              "Euro to Dollar Outlook: 'Could Gain 10% vs USD in 2 Years'",
              "Euro to Dollar Forecast: Federal Reserve Debate"],
    'Sentiment Score': [-80, -20, 70, -60, -40, -50, 90, 85, 70, 60],
    'Importance Score': [0.457, 0.291, 0.997, 0.636, 0.382, 0.564, 0.800, 0.700, 0.900, 0.719]
}

# Create DataFrame
df = pd.DataFrame(data)

# Print DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    'Topic': ["Euro to Dollar Exchange Rate Outlook: 'EUR/USD to rise to around 1.12'",
              "US Aid to Ukraine Helps the American Economy and Boosts US Jobs",
              "Euro to Dollar Week Ahead Forecast",
              "Euro to Dollar Outlook: 'Could Gain 10% vs USD in 2 Years'",
              "Dollar steady and sideways in tight range ahead of Fed Minutes",
              "US-EU unity ruptures over climate damage payments",
              "US Dollar Index (DXY) Unfazed as Business Activity in the US Held Firm",
              "Euro to Dollar Forecast: Federal Reserve Debate",
              "Euro to Dollar Outlook: 'Advance to 1.1500 in 2024'",
              "Dollar poised to halt slide after Fed minutes"],
    'Sentiment Score': [80, 20, 75, 70, -20, -60, -10, 60, 90, 10],
    'Importance Score': [1.000, 0.901, 0.899, 0.801, 0.799, 0.703, 0.697, 0.681, 0.499, 0.372]
}

# Create DataFrame
df = pd.DataFrame(data)

# Print DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the data
data = {
    "Topic": [
        "USD Strengthens Against Euro",
        "Euro Climbs Against Dollar",
        "US Dollar Faces Worst Month, Euro Surges",
        "Global Currency Quake - Dollar Dominance Questioned",
        "Euro Instant Payments Provisional Agreement Reached",
        "USD Weakens as Fed Rate Cut View Weighs",
        "EU Budget Dispute Threatens Ukraine War Lifeline",
        "US Dollar Rises, Set for Worst Monthly Loss in a Year",
        "European Start-up Funding Halved in 2023",
        "Fed Chair's Dovish Remarks Weaken Dollar"
    ],
    "Sentiment Score": [
        90, 80, -70, -50, 50, -80, -30, 60, -40, -60
    ],
    "Importance Score": [
        0.391, 0.296, 0.258, 0.25, 0.223, 0.207, 0.191, 0.17, 0.158, 0.152
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": ["BRICS' Dedollarization Efforts",
              "European Countries Not Using Euro",
              "Financial Podcast on Currency Market",
              "Delay in Funds for Ukraine's War Effort",
              "EU Support for Ukraine",
              "US Economy Outperforming Other Rich Nations",
              "EU Corruption Scandal",
              "US vs EU Industrial Policies",
              "ECB Rate Cut Bets",
              "US Investment in Euro Soccer Club"],
    "Sentiment Score": [80, 60, -40, 70, -20, -70, 90, -10, 60, -50],
    "Importance Score": [0.52, 0.65, 0.73, 0.56, 0.78, 0.89, 0.43, 0.81, 0.67, 0.77]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create a dictionary with the data
data = {
    "Topic": ["Fed signals rate cuts, Dollar tumbles against Euro",
              "EU funding for Ukraine blocked by Hungary",
              "Ukraine struggles, US and EU blamed",
              "Yuan surpasses Euro in global trade",
              "Dollar dominance in global trade",
              "ECB seeks funds for Ukraine from Russia",
              "EU accession talks, aid vetoed by Hungary",
              "Fed hints at rate cuts, Dollar drops against Euro",
              "Bretton Woods System collapse",
              "Dollar rebounds after Fed official's remarks"],
    "Sentiment Score": [-90, -70, -60, -20, 50, 30, -80, -80, -40, 70],
    "Importance Score": [0.150, 0.145, 0.140, 0.135, 0.130, 0.125, 0.120, 0.115, 0.110, 0.105]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)
#50

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": ["USD strengthens against EUR",
              "Fed expectations drive USD losses",
              "Euro outlook predicts rise above 1.10",
              "Concerns about US inflation",
              "Impact of US GDP revision on USD index",
              "Market sentiment on USD amid rate cut expectations",
              "DXY index movements",
              "Euro's resilience against USD",
              "Speculation on USD decline",
              "Euro's bullish trend"],
    "Sentiment Score": [90, -80, 70, -60, -50, -70, -50, 80, -70, 80],
    "Importance Score": [0.650, 0.653, 0.656, 0.659, 0.662, 0.665, 0.668, 0.671, 0.674, 0.677]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Euro hits highest against dollar since August",
              "Fed signals rate cuts, euro strengthens",
              "Dollar falls to 5-month low against euro",
              "World pays tribute to Jacques Delors",
              "Ukraine secures funds from World Bank",
              "Europe considers BRICS currency acceptance",
              "US sanctions Yemeni money network tied to Houthis",
              "Reflections on euro adoption",
              "Stablecoin innovation in 2024",
              "Dollar weakens amid risk-positive trade"],
    "Sentiment Score": [-85, -85, 85, 10, 25, 50, -60, -40, 30, -60],
    "Importance Score": [0.281, 0.281, 0.281, 0.087, 0.087, 0.087, 0.087, 0.087, 0.087, 0.087]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

print(len(bound))
bound=pd.DataFrame(bound)
bound.to_csv('eurusdscore2023.csv')

topics=pd.DataFrame([])
for i in range(52):
  topics=pd.concat([topics,raw_data[i].iloc[:,0]],ignore_index=True)
topics.to_csv('eurusdtopics2023.csv')