# -*- coding: utf-8 -*-
"""eur2021.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kO_wGRcLKd5LTJ5H0ryleZvKrn1wVkl5
"""

from sklearn.preprocessing import MinMaxScaler
import numpy as np

def weekly_score(df):
  transfer=MinMaxScaler(feature_range=(0.1,0.5))
  df_1=np.array(df.iloc[:,2]).reshape(-1, 1)
  df_1=transfer.fit_transform(df_1)
  d=np.array(df.iloc[:,1])*df_1.reshape(1, -1)
  upper=int(sum(np.maximum(d,0).T))
  lower=int(sum(np.minimum(d,0).T))
  return upper,lower

bound=[]
raw_data=[]

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "Blue sweep of Congress will add pressure to weak dollar, analysts say",
        "Best Pound-Dollar Exchange Rate for Over Two-and-a-Half Years",
        "Euro drops on weak inflation, retail sales",
        "Ebury ranked #1 EUR/USD forecaster on Bloomberg",
        "How to Buy Bitcoin With Euro?",
        "Factors in Focus: Val-come Back! Shifting Factors as the Cycle Turns",
        "USD Price Outlook: US Dollar Tracking Yields Higher, NFPs Eyed",
        "G3 Forecast Revision – January 2021",
        "The US Dollar's Share of Global Reserve Currencies Drops as Japanese Yen's Share Increases",
        "Avoiding Latin America's Currency Disasters"
    ],
    "Sentiment Score": [
        -92.000,
        89.000,
        -85.000,
        80.000,
        75.000,
        70.000,
        -65.000,
        60.000,
        -55.000,
        50.000
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "U.S. dollar is forecast to depreciate further in 2021",
        "CIBC Currency Exchange Forecasts 2021-2022",
        "Dollar edges lower as recent rally runs out of steam",
        "Pound Euro Exchange Rate Gains as Economic Recovery Eyed for March",
        "GBP/USD Weekly Forecast: GBP/USD Rally Out of Steam?",
        "EU clears LSE's $27 billion takeover of Refinitiv",
        "US Anti-Money Laundering Act 2020: Key Highlights",
        "Progress in Netherlands demand rise in minimum wage",
        "US Treasury Under New Mandate to Probe Chinese Money Laundering",
        "Market Update 2021: the dollar, the euro and the pound"
    ],
    "Sentiment Score": [
        -95.000,
        90.000,
        -85.000,
        80.000,
        75.000,
        70.000,
        -65.000,
        60.000,
        -55.000,
        50.000
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "EU seeks to cut reliance on U.S. dollar, other financial centres",
        "EU immigration: Frontex faces scrutiny over its growing role",
        "Perry Anderson · The Breakaway: Goodbye Europe",
        "China, Europe look to cut dollar dependence as US clout declines",
        "Euro Rises Ahead Of Biden's Inauguration",
        "Euro strengthens as US stimulus hopes lift mood",
        "JP Morgan Forecast Euro-Dollar at and Below 1.20 in 2021",
        "Dollar slips as US stimulus hopes lift mood",
        "EUR/USD Daily Forecast – U.S. Dollar Is Losing Ground Against Euro",
        "US, China must act to avoid monetary breakdown"
    ],
    "Sentiment Score": [
        -95.000,
        -90.000,
        -85.000,
        -80.000,
        75.000,
        70.000,
        65.000,
        -60.000,
        55.000,
        -50.000
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "ECB in 'Currency War' Over Euro, Commerzbank Strategist Says",
        "Euro to US Dollar (EUR/USD) Exchange Rate Plummets",
        "Selling Euro-Dollar Exchange Rate is 'Trade of the Week'",
        "US Dollar Technical Forecast: DXY, EUR/USD, GBP/USD, AUD/USD",
        "Outlook 2021: Sovereign debt can boost euro’s reserve currency status",
        "Digital currencies: Economic and geopolitical challenges",
        "Cross currency opportunities: EUR spreads to outperform USD counterparts",
        "Euro strengthens as US stimulus hopes lift mood",
        "Taking action to protect our economic sovereignty",
        "When flexible exchange rates don't insulate economies from external shocks"
    ],
    "Sentiment Score": [
        -100.000,
        -95.000,
        -90.000,
        85.000,
        80.000,
        -85.000,
        90.000,
        75.000,
        70.000,
        -80.000
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "USD strengthens as US stimulus hopes lift mood",
        "US Air Force bomber unit sets up shop in Norway",
        "Prize Money Opened Up to Endurance-Only Teams",
        "US, EU and UN slam Turkey’s handling of Boğaziçi University protests",
        "Geographic Insights: 2021 Darknet Market Trends",
        "Latest Foreign Exchange Rate Forecasts 2021 - 2022",
        "Will the U.S. Dollar Lose Its Place as the World's No. 1 Reserve Currency?",
        "Everything you should know about the Japanese Yen (JPY)",
        "Buy Black: Black Dollar Index ranks companies supporting Black America",
        "EU Awards USD 13m Worth of Translation Contracts in January 2021"
    ],
    "Sentiment Score": [
        100.000,
        95.000,
        90.000,
        -85.000,
        -80.000,
        -75.000,
        -70.000,
        85.000,
        80.000,
        75.000
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

#5

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "US Dollar Strength in 2021",
        "Euro Strength in 2021",
        "EU Considering New Airbus Subsidy Model",
        "China and SWIFT Partnership for Digital Currency",
        "IMF SDR Increase Impact",
        "Cuba's Currency Unification",
        "European Warehouse Demand Surge",
        "Biden Administration Measures Impact",
        "Transparency in Luxembourg's Investment Funds",
        "Central Banks' Stance on Bitcoin"
    ],
    "Sentiment Score": [
        85,
        -80,
        -40,
        70,
        60,
        -60,
        75,
        65,
        -25,
        -50
    ],
    "Importance Score": [
        0.542,
        0.488,
        0.354,
        0.670,
        0.823,
        0.314,
        0.715,
        0.587,
        0.202,
        0.445
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "US Dollar Strength in 2021",
        "Europe's Chip Independence Amid US-China Conflict",
        "Central Bank Digital Currencies",
        "DXY Trading Analysis",
        "Europe Leading in Crypto ETPs",
        "Dan Gertler Money Laundering Allegations",
        "Impact of US Sanctions on Iran's Economy",
        "Biden Administration's Diplomatic Approach",
        "Cross-Border Tax Reforms Impact",
        "Bitcoin's Impact on Dollar Dominance"
    ],
    "Sentiment Score": [
        85,
        75,
        70,
        60,
        55,
        -50,
        -60,
        40,
        30,
        -70
    ],
    "Importance Score": [
        0.798,
        0.654,
        0.512,
        0.431,
        0.379,
        0.293,
        0.251,
        0.567,
        0.421,
        0.188
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "European Commission and ECB's digital euro project",
        "Brexit impact on sterling value",
        "US dollar vs. euro in vaccine race",
        "TransferWise rebrands to Wise",
        "Impact of Brexit on online orders",
        "Forex market hours",
        "US vs. Europe: vaccine rollout",
        "Capital One's AML fine",
        "Plug Power's European expansion",
        "EU's stance on Luxembourg as tax haven"
    ],
    "Sentiment Score": [
        80,
        -70,
        60,
        70,
        -60,
        50,
        40,
        -50,
        30,
        -40
    ],
    "Importance Score": [
        0.812,
        0.719,
        0.621,
        0.553,
        0.489,
        0.418,
        0.365,
        0.322,
        0.278,
        0.233
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "US, EU impose sanctions on Russia over Navalny",
        "Dollar advances against euro amid rising interest rates",
        "Pentagon seeks involvement in EU military planning",
        "De-Dollarization strategies and efforts",
        "US Dollar Index reaches 2021 highs",
        "China's dominance in AI concerns US and Europe",
        "US Dollar shortage globally",
        "Impact of Covid-19 on dollar funding of non-US banks",
        "ECB and US economic developments in 2020",
        "Temporary suspension of tariffs between US and EU"
    ],
    "Sentiment Score": [
        -80,
        70,
        60,
        -50,
        40,
        -30,
        -20,
        -10,
        10,
        20
    ],
    "Importance Score": [
        1.000,
        0.917,
        0.833,
        0.750,
        0.667,
        0.583,
        0.500,
        0.417,
        0.333,
        0.250
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "USD Index reaches 3-1/2-month high",
        "Euro plunges to worst 2021 levels against US Dollar",
        "ECB staff projections for euro area economy in March 2021",
        "Comparison of COVID-19 stimulus spending across countries",
        "Impact of new anti-money laundering laws on business",
        "European efforts to double chip manufacturing output",
        "US Dollar and Euro exchange rate forecasts for 6-12 months",
        "Biden stimulus package and its effect on job preservation",
        "Central Bank of Uzbekistan updates foreign currency rates",
        "EU aims to incentivize foreign investment"
    ],
    "Sentiment Score": [
        80,
        -70,
        60,
        -50,
        40,
        -30,
        20,
        -10,
        10,
        0
    ],
    "Importance Score": [
        1.000,
        0.917,
        0.833,
        0.750,
        0.667,
        0.583,
        0.500,
        0.417,
        0.333,
        0.250
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)
#10

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "Joint operation seizes euro and dollar banknotes",
        "Bitcoin ranked among top three world currencies",
        "Commerzbank's outlook on EUR/USD exchange rate",
        "British Pound and Euro exchange rate forecasts",
        "Bulgaria seizes counterfeit euro and dollar banknotes",
        "Bank of Japan announces adjustments impacting JPY and EUR",
        "Hapag-Lloyd publishes annual report with earnings growth",
        "HSBC revises dollar forecasts with impact on EUR/USD",
        "Euro area money markets changes and implications",
        "European vs. US COVID-19 response and economic impact"
    ],
    "Sentiment Score": [
        90,
        80,
        -70,
        -60,
        70,
        60,
        50,
        -50,
        40,
        30
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "EU leaders push for stronger euro",
        "U.S. dollar rises as sentiment turns cautious",
        "DWS cuts fees on gold currency-hedged ETCs",
        "Hidden repercussions of public debt in the West",
        "ECB and US Federal Reserve’s CDI2 standards",
        "Bond yield differentials drive cross-currency trends",
        "Football in Europe transformed by US private equity",
        "Impact of strong vs. weak dollar on U.S. businesses",
        "Spamming of US dollar hurts emerging markets",
        "Rebuilding US-German relations amid challenges"
    ],
    "Sentiment Score": [
        90,
        -80,
        70,
        -60,
        50,
        -40,
        30,
        -20,
        10,
        -10
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "US dollar’s hegemony looking fragile",
        "China's exchange-rate system modernization",
        "UK's contribution to Horizon Europe",
        "US-China economic battle over climate change",
        "New rules in China impacting foreign banks and companies",
        "Eurozone's mishandling of the pandemic",
        "De-globalization driven by global crises",
        "US Dollar’s status as global reserve currency declines",
        "Euro's rebound amid lack of fresh data",
        "Impact of US pandemic recovery optimism on USD"
    ],
    "Sentiment Score": [
        -100,
        -90,
        80,
        70,
        -60,
        -50,
        -40,
        -30,
        20,
        10
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "USD-EUR rates divergence: More in the tank",
        "US-EU: political convergence, economic divergence",
        "EUR/USD Forecast: Bullish interest still shy",
        "South African Rand's Outperformance Puts USD/ZAR Under Strain",
        "Sterling at 'lowest levels since February' yesterday",
        "US dollar maintains multi-month heights",
        "EUR/USD flirting with the 1.1900 level as week draws to a close",
        "USD-EUR rates divergence: More in the tank",
        "EUR/USD Forming Minor Parabolic Wedge Top",
        "EUR/USD Forecast: Dollar’s decline continues"
    ],
    "Sentiment Score": [
        -100,
        -90,
        80,
        70,
        -60,
        -50,
        -40,
        -30,
        20,
        10
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "EUR/USD Forecast: Upbeat US inflation fuels optimism",
        "US Dollar Forecast: Sinking Despite Rising Inflation",
        "Euro Pound Exchange Rate At 0.91 By End-2021",
        "Rate Rises Spell Success for Canadian Dollar and Euro",
        "USD/EUR rates divergence: More in the tank",
        "US dollar maintains multi-month heights",
        "EUR/USD struggles for direction, targets 1.2000",
        "Danske Bank: Latest Exchange Rates Forecast",
        "EUR/USD Forming Minor Parabolic Wedge Top",
        "EUR/USD Forecast: Dollar’s decline continues"
    ],
    "Sentiment Score": [
        100,
        -90,
        80,
        70,
        -60,
        -50,
        -40,
        -30,
        20,
        10
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)
#15

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "US dollar, euro exchange rate up",
        "Euro and U.S. dollar waffle as markets weigh ECB policy talk",
        "European Super League: a history of splits over money in professional sport",
        "U.S dollar under pressure amid rising inflation",
        "The breakaway European Super League is all about big money",
        "European Super League clubs promised €200m-€300m 'welcome bonus'",
        "Dollar falls as U.S. yields languish, euro gets boost from survey",
        "Opinion: US owners find American-style greed doesn't play well in European soccer",
        "European Super League will pour €400m into grassroots football, says new chief",
        "US Dollar Index drops to 5-week lows near 91.30"
    ],
    "Sentiment Score": [
        90,
        -80,
        -70,
        -60,
        -50,
        40,
        30,
        20,
        -10,
        0
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "US Covid-19 response: How stimulus checks, unemployment insurance, and tax credits sped up economic recovery",
        "US Dollar Slides Most in 9 Months in April As Global Outlook Brightens",
        "Putin's Bid to Ditch Dollar Picks Up as Exports Move to Euro",
        "EUR/USD Next 6-12 Month Forecasts: Top FX Institutional Analysis And Euro-Dollar Predictions",
        "Expanding the Non-USD Denominated S&P GSCI Single Commodity Index Series",
        "USD/JPY Bank Forecasts 2021-2022: Top 10 Investment Bank Dollar-Yen Predictions",
        "Uncovering The Hidden Costs Of The Petrodollar",
        "Economic Crises in Foreign Markets Reduce U.S. Agricultural Exports",
        "Euro money market study 2020",
        "Euro-to-Dollar Exchange Rate Forecasts: Consensus Hides Divergence, Fed Experiment Will Amplify Shift in Global Capital Flows"
    ],
    "Sentiment Score": [
        80,
        -90,
        -80,
        70,
        60,
        -70,
        -50,
        -30,
        40,
        50
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "US Dollar Share of Global Foreign Exchange Reserves Drops to 25-Year Low",
        "Euro US Dollar Strengthens on German Industrial Production",
        "European Central Bank CBDC Survey Finds Privacy Is The Number One Concern For Digital Euro",
        "Dollar’s Lucky Month Is Sputtering as Technicals Foil Gains",
        "US and Europe apply different COVID values for different end results",
        "Cryptos Are a Threat to Central Banks. Why It Goes Beyond Bitcoin.",
        "EUR/USD Outlook: Euro Price Action Mired by Lower Highs",
        "Why have Israeli scientists won so many ERC grants?",
        "Top Personal Income Tax Rates in Europe",
        "Nearly 1 in 3 new stores opening in the US is a Dollar General"
    ],
    "Sentiment Score": [
        -90,
        80,
        70,
        -60,
        -50,
        -40,
        -30,
        20,
        10,
        0
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)
#18

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "Dollar hovers near 10-week lows as inflation expectations skyrocket",
        "US dollar dominance waning as CBDCs enter global spotlight",
        "Invoicing currency in developing countries' imports: Do exchange rates and tariffs affect prices the same way?",
        "Brexit, Global OTC IRS markets - Q1 review",
        "'Asian century' won't come until global governance becomes more inclusive",
        "U.S. companies issuing bonds in foreign markets again after pandemic drop - Goldman",
        "US investment into Europe's startups hits an all-time high",
        "Putin's Bid to Ditch Dollar Picks Up as Exports Move to Euro",
        "'One Analyst says this is 'as Good as it Gets' for Pound Sterling against the Euro",
        "'Comparing USD/CAD Exchange Rate Forecasts Over Next 6-12 Months: 6/10 Banks Predict A Higher US Dollar'"
    ],
    "Sentiment Score": [
        -90,
        -80,
        -70,
        -60,
        -50,
        -40,
        50,
        60,
        70,
        80
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "EUR/USD Sinks as FOMC Minutes Show Threat of Fed Tapering",
        "Dollar left wounded, Fed minutes and inflation in focus",
        "Regulating the Globalisation of Data: Which Model Works Best?",
        "U.S. waives sanctions on Nord Stream 2 as Biden seeks to mend Europe ties",
        "Let's put economic competitiveness above politics for Europe's future",
        "US stock market opens lower with extreme volatility",
        "Police Across Europe Crush Ponzi Schemes, Recover Lost Money",
        "Central Bank Digital Currencies: The Next Big Disruption?",
        "Anti-Money Laundering Update",
        "Use-case illustrations for PMI by S&P Global"
    ],
    "Sentiment Score": [
        -100,
        -90,
        -80,
        -70,
        -60,
        -50,
        50,
        60,
        70,
        80
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)
#20

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "The demise of the dollar? Reserve currencies in the era of 'going big'",
        "Euro-Dollar Week Ahead Forecast: Striving for 2021 Highs",
        "USD explained: A guide to the US dollar",
        "Revealed: Syrians pay tax to rebuild after war but see little benefit",
        "European groups pump money into Swedish 'green steel' start-up",
        "Equities rally, dollar falls as inflation concerns grow",
        "Bank of Uzbekistan updates foreign currency exchange rates",
        "Eurocup vs Copa América: How much money does each one pays?",
        "Swiss Franc Has Gained 200% Vs Weighted Basket Of Dollars And Euros Since 1975",
        "Winners of giant USDA pollock, catfish buys announced"
    ],
    "Sentiment Score": [
        -100,
        -90,
        -80,
        -70,
        -60,
        -50,
        50,
        60,
        70,
        80
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "International use of the euro broadly stable in 2020",
        "Digital euro could boost single currency's international use, ECB says",
        "The international role of the euro, June 2021",
        "EUR TO PKR: Today 1 Euro rate in Pakistan Rupee, on 5th June 2021",
        "A world tour of digital currency projects | PaymentsSource",
        "The Case for EU Defense",
        "China's cryptocurrency in Africa should not worry the US",
        "African farmers could benefit from more friendly EU agriculture policies",
        "Norway an EV role model? Their pathway is expensive and paid for with oil & gas exports",
        "A Russian doll of money laundering: Magnitsky-related crime group’s assets seized in Belgium and Latvia as larger EU ..."
    ],
    "Sentiment Score": [
        60,
        40,
        20,
        80,
        -10,
        30,
        -30,
        50,
        -20,
        -50
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "International cost comparison 2021 | Features | Building",
        "How to prevent Germany from becoming Eurosceptic",
        "800 criminals arrested in biggest ever law enforcement operation against encrypted communication | Europol",
        "Why Europe's banks want to end US dominance in payments",
        "The impact of Brexit on Africa",
        "Top 4 money transfer apps in the European market",
        "COVID-19 Vaccine Prices: Comparing the EU with the US",
        "EUR/USD Forecast: Euro-Dollar To Rise To 1.26 By End 2021 Say MUFG",
        "U.S dollar settles high as Bitcoin and Gold bow low",
        "Another Billion-Dollar Team Jumps Firms, This Time to Raymond James"
    ],
    "Sentiment Score": [
        50,
        -70,
        -90,
        -30,
        -40,
        20,
        -10,
        60,
        80,
        40
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Migration and risk sharing in currency unions: The euro area versus the US",
    "Remarks by President Biden at the U.S.-EU Summit Expanded Plenary Session",
    "US and EU look for ways to boost American participation in Horizon Europe R&D",
    "Interview with Financial Times",
    "U.S, EU agree truce in 17-year Airbus-Boeing conflict",
    "EU, U.S. React Sharply After Hungary Passes Bill Banning LGBT Content In Schools",
    "EU-US aircraft deal heralds new trade cooperation in Biden era",
    "U.S. and E.U. End Aviation Trade Spat and Turn to China's Rise (Published 2021)",
    "U.S. and EU resolve 17-year Boeing-Airbus trade dispute",
    "Europe and the US keep investing in Chinese coal"
]

sentiment_scores = [
    -60,
    40,
    30,
    10,
    60,
    -80,
    70,
    50,
    70,
    -50
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

#25
import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "European recovery fund offers twofold challenge",
        "U.S., EU Willing to Review Venezuela Sanctions on Conditions",
        "Euro loses strength against the dollar",
        "Dollar rally sputters as Fed sends mixed signals on inflation",
        "Bullish Price Action in EUR/USD After Softer US Data",
        "When is the German IFO survey and how it could affect EUR/USD?",
        "The international role of the euro",
        "Cryptocurrency crackdown looms as states enter digital currency race",
        "Work on cross-currency instant payments in TIPS moves forward",
        "The EU’s Financial Sector Mercantilism Will Lead to Weakness, Not Strength"
    ],
    "Sentiment Score": [
        -70,
        -10,
        -80,
        30,
        70,
        40,
        50,
        -30,
        20,
        -60
    ],
    "Importance Score": [
        1.000,
        0.900,
        0.800,
        0.700,
        0.600,
        0.500,
        0.400,
        0.300,
        0.200,
        0.100
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Extra-EU trade in goods by invoicing currency",
    "Options, yields and economic growth improve Euro’s prospects",
    "Huawei enlists army of European talent for 'battle' with US",
    "After Brexit, Ireland can't have it both ways",
    "Geo-Economics in 2030: How the EU Can Squeeze Out From Between the US and China",
    "Highlights of the 6th Anti Money Laundering Directive (6AMLD)",
    "Timothy Garton Ash: ‘Hungary shows us that we haven’t yet succeeded in linking the Europe of values to the Europe of ...",
    "China's anti-foreign sanctions law: Companies in the crosshairs",
    "When the U.S. Gave Up Gold - WSJ",
    "VAT Exemption Thresholds in Europe, 2021"
]

sentiment_scores = [
    30,
    40,
    -20,
    -10,
    -60,
    50,
    -40,
    -70,
    -50,
    20
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Montenegro's debt deal with European and U.S. banks",
    "Central banks' $9 trillion spending spree",
    "Montenegro's conversion of loan from China to euros",
    "Vietnam pilots national digital currency",
    "Central banks' consideration of digital currency",
    "European Payments Initiative and its geopolitical implications",
    "Impact of Europe's 'green' energy on the American South",
    "Right to repair movement in the US and Europe",
    "Belarusian oligarch's family selling firm and bank before EU sanctions",
    "Pan-European politics: The EU's need for a new narrative"
]

sentiment_scores = [
    30,
    50,
    40,
    20,
    -10,
    -20,
    -30,
    -40,
    -50,
    -60
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Bitcoin labelled as a crypto-asset",
    "Renminbi's current strength and outlook",
    "US Treasury secretary's impact on EU's digital levy plans",
    "Europe's fight against corruption and dark money politics",
    "Launch of Eurosystem's digital euro project",
    "European Central Bank's efforts towards digital euro",
    "Potential currency war and EU's decision-making",
    "Introduction of ECB's new e-euro",
    "Austria's opposition to EU plan on cash payment cap",
    "National debt in EU countries"
]

sentiment_scores = [
    -20,
    -40,
    30,
    50,
    60,
    70,
    -10,
    -30,
    40,
    20
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Invoicing currency choices of Japanese subsidiaries",
    "Euro's performance in volatile trading",
    "Impact of Brexit on UK's invoicing currency",
    "U.S.-EU Counterterrorism Cooperation",
    "Europe's semiconductor strategy",
    "Hungary's loss of Norwegian funds",
    "EU's plan for traceable Bitcoin transfers",
    "European Commission's AML/CFT measures",
    "Opinion on the future of cash and virtual currency",
    "Russia's economic influence in the Mediterranean"
]

sentiment_scores = [
    20,
    -30,
    -40,
    50,
    -10,
    -50,
    30,
    40,
    10,
    -20
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Impact of banks' cross-border claims on USD to EUR exchange rate",
    "Role of US dollar and euro in global trade invoicing",
    "DZ Bank's role in supporting EU bond programmes",
    "BIS global liquidity indicators and their effect on USD to EUR exchange rate",
    "EU's efforts in anti-money laundering compliance",
    "ECOWAS's pursuit of a common currency",
    "Bank of Italy's contribution to the digital euro discussion",
    "Regulatory guidance on marine insurance KYC and its impact on USD to EUR exchange rate",
    "Impact of US and European investment banks' losses on USD to EUR exchange rate",
    "Russian support to Belarus and its effect on USD to EUR exchange rate"
]

sentiment_scores = [
    50,
    20,
    40,
    30,
    -30,
    10,
    60,
    -20,
    -10,
    -40
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)
#30

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Impact of US foreign aid spending on USD to EUR exchange rate",
    "Influence of venture capital investment on USD to EUR exchange rate",
    "Effect of COVID-19 vaccine passports on USD to EUR exchange rate",
    "Tesla's expansion of Supercharger network and its effect on USD to EUR exchange rate",
    "US non-farm payrolls data impact on USD to EUR exchange rate",
    "Bitcoin price movement and its impact on USD to EUR exchange rate",
    "Eliud Kipchoge's Olympic marathon win and its effect on USD to EUR exchange rate",
    "US stock market performance and its effect on USD to EUR exchange rate",
    "Luxury watch market news and its impact on USD to EUR exchange rate",
    "Forex market sentiment and its influence on USD to EUR exchange rate"
]

sentiment_scores = [
    -20,
    -30,
    10,
    40,
    20,
    -10,
    30,
    20,
    10,
    0
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Impact of US jobs report on USD to EUR exchange rate",
    "Cambodia's economic ties with China and EU sanctions",
    "EU travel restrictions and their effect on USD to EUR exchange rate",
    "Emergence of the euromarket and its influence on USD to EUR exchange rate",
    "Gas taxes in Europe and their impact on USD to EUR exchange rate",
    "Proposed changes to EU AML/CFT supervision regime and their effect on USD to EUR exchange rate",
    "Potential alternatives to the US dollar as global reserve currency",
    "US real estate market as a destination for illicit funds and its effect on USD to EUR exchange rate",
    "US investment in Cape Verde and its impact on USD to EUR exchange rate",
    "European Payments Initiative and its potential impact on USD to EUR exchange rate"
]

sentiment_scores = [
    60,
    -40,
    -20,
    30,
    -10,
    -30,
    40,
    -50,
    20,
    10
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Impact of US dollar scaling 9-month peak on Fed taper outlook",
    "GBP/USD forecast and its effect on USD to EUR exchange rate",
    "Risk aversion affecting CAD and AUD and its impact on USD to EUR exchange rate",
    "US dollar gaining due to Afghanistan and Delta variant concerns",
    "Impact of technical levels on USD to EUR exchange rate",
    "Silver price pressure and its correlation with USD strength",
    "US stocks performance and its influence on USD to EUR exchange rate",
    "BNM warning on ringgit's volatility and its effect on USD to EUR exchange rate",
    "Outlook of US dollar index and its implications for USD to EUR exchange rate",
    "Euro forecast and its impact on EUR/USD exchange rate"
]

sentiment_scores = [
    70,
    20,
    -30,
    -40,
    10,
    -20,
    30,
    -50,
    60,
    40
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Macroeconomic Euro-U.S. Dollar Drivers",
    "Rise of non-bank finance and implications for monetary policy",
    "Fall of Afghan government and its impact on Europe",
    "Economic views on US reserve currency status",
    "Euro near nine-month low due to diverging Fed, ECB policies",
    "US-European concerns over military movements",
    "Progressive critique of Eurozone and Euro's viability",
    "Comparison of US and European venture capitalists",
    "US dollar gains against euro and British pound",
    "Impact of sanctions on Turkey on Euro-US dollar exchange rate"
]

sentiment_scores = [
    50,
    -20,
    -30,
    -60,
    -40,
    -30,
    -70,
    10,
    30,
    -50
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Impact of US-EU fintech competition on EUR-USD exchange rate",
    "Brexit's implications for the UK-EU relationship",
    "European concerns about US reliability post-Afghanistan",
    "Importance of USD dominance in global payment systems",
    "Forex trading trends in Nigeria and its impact on USD-EUR",
    "Humanitarian crisis in Afghanistan and its global repercussions",
    "Cancellation of VAT Retail Export Scheme and its economic effects",
    "Pound Sterling's exchange rate performance against Euro and Dollar",
    "Dollar's influence on global currency exchange rates",
    "Montenegro's potential currency shift and EU membership"
]

sentiment_scores = [
    10,
    -70,
    -40,
    60,
    -20,
    -80,
    -50,
    30,
    50,
    -30
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)
#35

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "EU AML regime overhaul impact on USD-EUR exchange rate",
    "US seizure of Canadian dollars in Memphis affecting USD-EUR exchange rate",
    "Afghanistan remittance payouts in local currency impact on USD-EUR exchange rate",
    "Rethinking of Bretton Woods and its implications on USD-EUR exchange rate",
    "Dollar's movement based on US Treasury yields affecting USD-EUR exchange rate",
    "Merkel's legacy and its influence on EUR-USD exchange rate",
    "Bitcoin ATM distribution and its impact on USD-EUR exchange rate",
    "Chinese venture funds and their effect on USD-EUR exchange rate",
    "US pharmaceutical ads and their correlation to USD-EUR exchange rate",
    "US foreign policy decisions and their effect on USD-EUR exchange rate"
]

sentiment_scores = [
    -30,
    -40,
    -60,
    -20,
    10,
    20,
    30,
    -50,
    -70,
    -80
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Impact of EU R&D budget allocations on USD-EUR exchange rate",
    "Lessons from Nixon's 'dollar shock' and its relevance to USD-EUR exchange rate",
    "EU's increased climate funds pledge and its effect on USD-EUR exchange rate",
    "EU's new Indo-Pacific strategy and its implications on USD-EUR exchange rate",
    "Legacy of Angela Merkel and its influence on USD-EUR exchange rate",
    "US-EU methane emissions reduction commitment and its impact on USD-EUR exchange rate",
    "Variety in currency across Central and Eastern Europe and its relation to USD-EUR exchange rate",
    "Global rankings on financial crime risks and its significance for USD-EUR exchange rate",
    "Evolution of UK's Money Laundering Regulations and its effect on USD-EUR exchange rate",
    "Transition of Europe-based carmakers to electric vehicles and its impact on USD-EUR exchange rate"
]

sentiment_scores = [
    -10,
    -20,
    20,
    10,
    30,
    30,
    -40,
    -50,
    -30,
    20
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Stress in European money market funds at the outbreak of the pandemic",
    "Venture Capital resilience during the pandemic",
    "US-EU unified approach to limit Big Tech market power",
    "Impact of Western governments raising taxes post-pandemic on USD-EUR exchange rate",
    "Effect of central bank efforts on foreign exchange market stability",
    "Transatlantic Data Flows: Importance for U.S.-EU Economic Partnership",
    "Trust erosion in US-EU relations and its implications",
    "EU's enforcement of fines on Poland and its effect on USD-EUR exchange rate",
    "Impact of Money 20/20 Europe conference on payments in the EU on USD-EUR exchange rate",
    "ECB's increase in gold reserves and its significance for USD-EUR exchange rate"
]

sentiment_scores = [
    -20,
    20,
    -30,
    -40,
    10,
    0,
    -10,
    -30,
    20,
    30
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "U.S. Dollar-British Pound Rate Drivers",
    "Rising Demand for U.S. Dollars in Q4",
    "Research Findings on Retail CBDCs",
    "EU Decision on Panama's Tax-Haven Status",
    "European Banks Contemplate Competition with US Payment Giants",
    "EUR/USD Exchange Rate Hits 14-Month Low",
    "Impact of US Debt Default on Global Economy",
    "Seizure of Counterfeit US Currency",
    "Effectiveness of ECB Euro Liquidity Lines",
    "Anticipation of Interest Rate Surge Boosting USD"
]

sentiment_scores = [
    -30,
    -10,
    20,
    -20,
    -40,
    -50,
    -30,
    -20,
    10,
    -20
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "US Dollar Role in International Trade",
    "Innovative Blockchain Technology in Finance",
    "European Carbon Allowance Strategy ETF",
    "EU-US Relationship and Multilateralism",
    "Impact of Higher Inflation on Currency Volatility",
    "Poland's Legal Challenge to EU Laws",
    "Reparations Payment Impact on Currency",
    "US Role in Global Financial Secrecy",
    "Global Energy Crisis Impact on Currency",
    "Turkey's Climate Accord Ratification"
]

sentiment_scores = [
    20,
    30,
    10,
    5,
    -15,
    -25,
    -30,
    -35,
    -20,
    -10
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)
#40

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "EU Aid Package for Afghanistan",
    "Cross-Border Payments Collaboration",
    "Technological Transformation in Finance",
    "EU Market Entry Strategies Post-Brexit",
    "Crypto Impact on USD Dominance",
    "Investment Boom in Eastern Europe",
    "Venture Capital Funding in Europe",
    "Pandemic's Effect on Currency Demand",
    "Global Response to Iran's Actions",
    "Consumer Behavior and Crisis Savings"
]

sentiment_scores = [
    20,
    30,
    15,
    10,
    -25,
    35,
    5,
    20,
    -15,
    -10
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "US Dollar-Yuan Exchange Rate",
    "Central Bank Digital Currencies",
    "Pandora Papers on Money Laundering",
    "Battery Materials Plants Expansion",
    "Microchips Industry in Europe",
    "Assad Regime and Currency Manipulation",
    "Political Meddling in Hungary",
    "US-EU Digital Tax Agreement",
    "Global Energy Crisis Response",
    "Aid Diversion in Syria"
]

sentiment_scores = [
    -20,
    10,
    -30,
    15,
    -25,
    -40,
    -15,
    5,
    -10,
    -35
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the topics, sentiment scores, and importance scores
topics = [
    "Global Liquidity and Foreign Credit Growth",
    "Currency Volatility Impact on USD Index",
    "ECB's Digital Euro and Exclusion of US Firms",
    "Mario Draghi's Role in Multilateral Order",
    "Syrian Regime's Aid Diversion",
    "ECB Stimulus and Economic Impact",
    "Inflationary Pressures and USD Alternatives",
    "Impact of ECB Comments on Dollar",
    "EU Projects Funding Criticism by UK Minister",
    "Taliban's Effort to Access Afghan Reserves"
]

sentiment_scores = [
    20,
    -30,
    -10,
    25,
    -35,
    -15,
    -5,
    -20,
    -25,
    -40
]

importance_scores = [
    1.000,
    0.900,
    0.800,
    0.700,
    0.600,
    0.500,
    0.400,
    0.300,
    0.200,
    0.100
]

# Create the dataframe
data = {
    "Topic": topics,
    "Sentiment Score": sentiment_scores,
    "Importance Score": importance_scores
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = [
    ["Digitalisation Impact on Payments", 65, 1.000],
    ["ECB's Monetary Policy and Sovereign Spreads", -40, 0.900],
    ["Taliban Ban on Foreign Currencies", -75, 0.800],
    ["Support for South Africa's Shift from Coal", 60, 0.700],
    ["Differences in US and European Organic Food Policies", -30, 0.600],
    ["Crackdown on Money Laundering in Art Markets", -50, 0.500],
    ["US Aid to Europe Post-World War II", 70, 0.400],
    ["EU Competition Policy and Anti-Competitive Practices", -20, 0.300],
    ["EU Regulation of Crypto Assets", 45, 0.200],
    ["Euro and Dollar Transactions in Digital Banking", 35, 0.100]
]

# Create the DataFrame
df = pd.DataFrame(data, columns=["Topic", "Sentiment Score", "Importance Score"])

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = [
    ["EU, US Efforts on Climate Disaster Funding", -70, 1.000],
    ["EU's Embrace of Crypto (Web3)", 50, 0.900],
    ["Poland's Dependence on EU Aid", -20, 0.800],
    ["Bulgarian Justice Minister Criticizes Chief Prosecutor", -40, 0.700],
    ["Turkish Lira Hits Record Lows against USD", -90, 0.600],
    ["US Outperforming Europe on ESG", 60, 0.500],
    ["Euro/Dollar Stability Amid Rate Uncertainty", 10, 0.400],
    ["Bank of England's Digital Money Plan", 30, 0.300],
    ["Vegan Diets Cost Savings Study", 40, 0.200],
    ["EU's Consideration of Funding for Border Walls", -30, 0.100]
]

# Create the DataFrame
df = pd.DataFrame(data, columns=["Topic", "Sentiment Score", "Importance Score"])

# Display the DataFrame
print(df)
#45

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = [
    ["Euro Adoption by European Union", 80, 1.000],
    ["USD Strength vs. Euro amid COVID Fears in Europe", -70, 0.900],
    ["USD near 16-Month High Against Euro", -60, 0.800],
    ["EU and US Plans to Confront China's Steel Industry", -20, 0.700],
    ["Euro at 20 Years", 50, 0.600],
    ["ECB's Case for Central Bank Digital Currencies", 30, 0.500],
    ["Croatia's Eurosceptic Movement", -40, 0.400],
    ["USD Dominance and Its Impact on Emerging Market Currencies", 10, 0.300],
    ["Swiss Franc's Performance Against Euro and USD", 40, 0.200],
    ["Impact of US Retail Sales Data on USD Strength", 20, 0.100]
]

# Create the DataFrame
df = pd.DataFrame(data, columns=["Topic", "Sentiment Score", "Importance Score"])

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = [
    ["Plunge of the Euro Exchange Rate", -90, 1.000],
    ["Turkish Lira Hits Record Low Against USD and EUR", -80, 0.900],
    ["Surging Dollar and Volatility in Currency Markets", 70, 0.800],
    ["US Dollar Index (USDX) and Monetary Policy", 60, 0.700],
    ["Impact of UUP on Hedge Strategies", 50, 0.600],
    ["Technical Analysis of EUR/USD Exchange Rate", 40, 0.500],
    ["Economic Effects of World War I", -30, 0.400],
    ["Impact of Turkish Lira Crisis on European Banks", -20, 0.300],
    ["Pound Sterling Strength and GBP/EUR Forecast", 10, 0.200],
    ["Nigerian Naira Performance Against USD", 20, 0.100]
]

# Create the DataFrame
df = pd.DataFrame(data, columns=["Topic", "Sentiment Score", "Importance Score"])

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = [
    ["European Commission Fines Banks for Forex Cartel", -80, 1.000],
    ["Euro Weakens Against US Dollar", -70, 0.900],
    ["Turkey's Currency Plunge", -60, 0.800],
    ["European Union's Global Gateway Initiative", 50, 0.700],
    ["European Money Mule Action", 40, 0.600],
    ["US Dollar Revenue Boost for European Stocks", 30, 0.500],
    ["Central Bank Digital Currencies Impact", 20, 0.400],
    ["EU and US Defense and Security Talks", 10, 0.300],
    ["Facebook Data Case Ruling", -10, 0.200],
    ["Impact of Cold War on Supply-Side Economics", -20, 0.100]
]

# Create the DataFrame
df = pd.DataFrame(data, columns=["Topic", "Sentiment Score", "Importance Score"])

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = [
    ["Euro Banknote Redesign", 40, 1.000],
    ["US Dollar Strength Forecast", 60, 0.900],
    ["Turkey's Currency Crisis", -70, 0.800],
    ["European Tech Startups VC Funding", 20, 0.700],
    ["Trans-Atlantic Strategy on Russia Sanctions", -80, 0.600],
    ["European VC Investments Outperform US", 30, 0.500],
    ["Bitcoin Impact on Turkey's Currency Crisis", -90, 0.400],
    ["Impact of Climate Migration on Euro", -50, 0.300],
    ["Euro Banknote Consultation", 10, 0.200],
    ["Euro Falls Amid Currency Market Appetite Increase", -30, 0.100]
]

# Create the DataFrame
df = pd.DataFrame(data, columns=["Topic", "Sentiment Score", "Importance Score"])

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = [
    ["European Central Bank Interest Rate Hike", 60, 1.000],
    ["Swiss National Bank Exchange Rate Assessment", 40, 0.900],
    ["Dollar Climbs Ahead of Fed and ECB Meetings", 70, 0.800],
    ["Eurozone Cash Glut Driving Dollar Demand", 50, 0.700],
    ["US-China UAE Weapons Deal Suspension", -30, 0.600],
    ["Euro Area Macroeconomic Projections", 20, 0.500],
    ["HSBC Fined for Money Laundering Failures", -80, 0.400],
    ["Eurosystem Staff Macroeconomic Projections", 10, 0.300],
    ["ECB Eases Pandemic-era Stimulus", 30, 0.200],
    ["Dollar General Worker Safety Concerns", -90, 0.100]
]

# Create the DataFrame
df = pd.DataFrame(data, columns=["Topic", "Sentiment Score", "Importance Score"])

# Display the DataFrame
print(df)
#50

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = [
    ["Euroclear Bank Migration to T2S Platform", 30, 1.000],
    ["Turkish Lira Plunges Against Dollar and Euro", -90, 0.900],
    ["European Central Bank Interest Rate Hike", 60, 0.800],
    ["US-EU Competition Policy Cooperation", 20, 0.700],
    ["European Real Estate Securitization Platform", 40, 0.600],
    ["New US-EU Competition Policy Cooperation", 10, 0.500],
    ["Impact of Omicron Variant on Currency Markets", -50, 0.400],
    ["Belarus-EU Asylum Seekers Situation", -70, 0.300],
    ["US Federal Reserve Interest Rate Hike Speculation", 50, 0.200],
    ["European Energy Crisis and NATO Response", -30, 0.100]
]

# Create the DataFrame
df = pd.DataFrame(data, columns=["Topic", "Sentiment Score", "Importance Score"])

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = [
    ["Dollar Strengthens in Year-End Trading", 70, 1.000],
    ["Euro Reaches Monthly High Against Dollar", 40, 0.900],
    ["Gold Prices Steady Amid Weak Dollar", 50, 0.800],
    ["EUR/USD Forecast for 2022", 30, 0.700],
    ["Euro Marks 20th Anniversary", 60, 0.600],
    ["European Rail Project Financed by China", -20, 0.500],
    ["Euro's Successes and Challenges at 20 Years", 20, 0.400],
    ["USD and EUR Performance at Year-End", 10, 0.300],
    ["Euro's Resilience and Role in Europe", 30, 0.200],
    ["US Dollar's Status as Global Reserve Currency", 40, 0.100]
]

# Create the DataFrame
df = pd.DataFrame(data, columns=["Topic", "Sentiment Score", "Importance Score"])

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

print(len(bound))
bound=pd.DataFrame(bound)
bound.to_csv('eurusdscore2021.csv')

topics=pd.DataFrame([])
for i in range(52):
  topics=pd.concat([topics,raw_data[i].iloc[:,0]],ignore_index=True)
topics.to_csv('eurusdtopics2021.csv')