# -*- coding: utf-8 -*-
"""eur2020.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9EALpv1Y7GbbvEveQlp3HDmCPvaPM6Q
"""



from sklearn.preprocessing import MinMaxScaler
import numpy as np

def weekly_score(df):
  transfer=MinMaxScaler(feature_range=(0.1,0.5))
  df_1=np.array(df.iloc[:,2]).reshape(-1, 1)
  df_1=transfer.fit_transform(df_1)
  d=np.array(df.iloc[:,1])*df_1.reshape(1, -1)
  upper=int(sum(np.maximum(d,0).T))
  lower=int(sum(np.minimum(d,0).T))
  return upper,lower

bound=[]
raw_data=[]

import pandas as pd

data = {
    "Topic": ["Dollar rebounds from six-month low",
              "Global optimism weighs on dollar",
              "China reduces US dollar weighting in yuan exchange index",
              "Supermarket exchange rates comparison for USD/EUR",
              "Moroccan tourists face foreign currency limit",
              "Binance adds USD/EUR pairs, plans expansion",
              "Pound expected to weaken against US Dollar",
              "UBS facilitates China's return to USD-denominated bonds",
              "Euro introduced as currency in multiple countries",
              "Gold prices rally despite rising dollar"],
    "Sentiment Score": [-70, -30, -50, 10, -20, 40, -70, 45, 60, 30],
    "Importance Score": [0.296, 0.236, 0.192, 0.148, 0.104, 0.088, 0.088, 0.088, 0.088, 0.088]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

data = {
    "Topic": ["Travelex cyber-attack", "US dollar dominance", "Euro debate heat-up", "Eastern Europe's nationalist turn",
              "Health-care costs comparison", "Czech town's role in shaping the dollar", "Pound-to-Euro exchange rate fluctuation",
              "Unclaimed old Irish money", "Central banks setting new exchange rates", "Currency rates in different countries"],
    "Sentiment Score": [-90, 80, 50, -60, -30, 70, -40, 20, 10, 30],
    "Importance Score": [0.543, 0.957, 0.671, 0.412, 0.321, 0.801, 0.753, 0.246, 0.589, 0.467]
}

df = pd.DataFrame(data)
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "US Dollar's Dominance in Global Currency Markets",
        "Europe's Response to US Tariffs",
        "Impact of Artificial Intelligence on Global Dominance",
        "Uncertainty Surrounding Facebook's Libra Cryptocurrency",
        "Challenges to the Existing World Order",
        "European Green Deal Investment Plan",
        "US Monetary Policy and Its Global Effects",
        "China's Currency Swap Deal with Zimbabwe",
        "Iran Nuclear Deal and European Response",
        "Increasing Venture Capital Investments in Europe"
    ],
    "Sentiment Score": [
        80, -70, 70, -60, -50, 60, 50, -40, -30, 40
    ],
    "Importance Score": [
        1.000, 0.977, 0.955, 0.932, 0.909, 0.886, 0.864, 0.841, 0.818, 0.795
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "Global Growth Outlook",
        "Brexit's Impact on GBP, EUR, and USD",
        "US Dollar Dominance in Forex Trading",
        "European Economic Choices",
        "Geopolitical Concerns and Currency Markets",
        "Forex Earnings Impact",
        "Eurozone Launches Satellites with Ariane 6",
        "Coronavirus Outbreak's Impact on Safe-Haven Currencies",
        "Importance of Compliance Programs",
        "Emerging Market Currency Trends"
    ],
    "Sentiment Score": [
        60.000, -70.000, 80.000, -50.000, -40.000, -30.000, 50.000, -60.000, 20.000, 40.000
    ],
    "Importance Score": [
        0.911, 0.905, 0.898, 0.892, 0.885, 0.879, 0.873, 0.867, 0.860, 0.854
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "EU-Iran Instex Trade Mechanism",
        "Impact of Brexit on EU and GBP/EUR",
        "Hungary's Resistance to Euro Adoption",
        "Eurozone Economic Outlook and Monetary Policy",
        "Brexit's Historical Perspective",
        "GBP Strength Post-Bank of England Decision",
        "US Dollar's Financial Influence on Global Politics",
        "Australian Dollar's Reaction to Coronavirus Outbreak",
        "Global Economic Growth Trends",
        "Technical Analysis of EUR/USD Exchange Rate"
    ],
    "Sentiment Score": [
        -30.000, -70.000, -10.000, 40.000, -50.000, 60.000, 80.000, -20.000, 50.000, 70.000
    ],
    "Importance Score": [
        0.956, 0.950, 0.944, 0.938, 0.931, 0.925, 0.919, 0.913, 0.906, 0.900
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "US Warning on Joining European Horizon Deal",
        "Ethiopia's Effort to Attract European Investment",
        "European Banking Apps Expanding into US Market",
        "Italy's Push to Redirect EU Funds from Euro Laggards",
        "Currency Hedged Versions of Vanguard Japan ETF",
        "Modern Monetary Theory's Impact on Cash-Strapped Governments",
        "Dollar Strength Post-US Non-Farm Payrolls Report",
        "US Dollar's Influence on American Trade Balance",
        "France's Efforts to Shift Euro Clearing from London",
        "Mark Ruffalo's Opposition to American LNG in Europe"
    ],
    "Sentiment Score": [
        -40.000, 20.000, 30.000, -20.000, 10.000, 50.000, 70.000, 40.000, -30.000, -60.000
    ],
    "Importance Score": [
        0.895, 0.890, 0.884, 0.878, 0.873, 0.867, 0.861, 0.855, 0.849, 0.844
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)
#5

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "Euro's Decline Reflects Political Turmoil, Economic Woes",
        "US demands better terms for taking part in Horizon Europe",
        "Euro drops to weakest level since 2017 - Currencies",
        "Euro sinks against dollar as US assets look more attractive",
        "EUR/USD Price Forecast – Euro Continues To Slide",
        "Euro skids to new low ahead of GDP data, dollar shines",
        "Pink Diamond Prices Appreciated 116% Over the Last Decade",
        "Swiss Central Bank Stuck Between Trump and Its Currency",
        "Global markets: Stocks gain as China says fewer new coronavirus cases",
        "U.S. commits $1 billion dollars to develop Central European infrastructure"
    ],
    "Sentiment Score": [
        -80.000, -50.000, -90.000, -85.000, -85.000, -90.000, 65.000, -30.000, 40.000, 60.000
    ],
    "Importance Score": [
        0.935, 0.927, 0.918, 0.909, 0.900, 0.891, 0.882, 0.873, 0.864, 0.855
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "Euro Is Swept Up in Global Funding Frenzy, Set for More Pain",
        "Some NI shops out of Euros over increase in demand",
        "Political risk and exchange rates: The lessons of Brexit",
        "The euro's slide against the US dollar looks set to continue",
        "Citi: Euro Not Cheap, Exchange Rates can Keep Falling",
        "HSBC To Scale Back In Europe As Profit Falls By A Third",
        "The weakening euro",
        "Ciao, Italia: Why Italy's Youth are Leaving in Droves",
        "Execution data: are month-end moves still predictable?",
        "Unintended consequences: Trump and Warren's bipartisan plan for the US dollar"
    ],
    "Sentiment Score": [
        -90.000, -70.000, -90.000, -85.000, -85.000,
        -70.000, -85.000, -70.000, 10.000, -10.000
    ],
    "Importance Score": [
        0.950, 0.920, 0.890, 0.860, 0.830,
        0.800, 0.770, 0.740, 0.710, 0.680
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "Euro To US Dollar Exchange Rate Unwinds Gains As Italian Contagion Count Rises",
        "Dollar retreats as coronavirus fallout raises expectations of rate cut",
        "The Global Dollar Short Squeeze",
        "The Eurozone Braces for a Rocky Year",
        "EUR/USD Forex Market Trading Strategies: What's Ahead Today?",
        "Euroscepticism, Thatcherism and Brexit",
        "The Euro-to-Dollar Rate Can Outperform Even as Coronavirus Outbreak Grows",
        "EUR/USD Price Forecast – Euro Continues to Show Sluggish Behavior",
        "5 reasons why the Eurodollar may continue to fall",
        "Dollar falls, euro has best day since May 2018"
    ],
    "Sentiment Score": [
        -95.000, -85.000, -80.000, -75.000, -70.000,
        -65.000, -60.000, -55.000, -50.000, -45.000
    ],
    "Importance Score": [
        0.940, 0.880, 0.820, 0.760, 0.700,
        0.640, 0.580, 0.520, 0.460, 0.400
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "Dollar sinks after US Federal Reserve cuts interest rates to battle coronavirus",
        "Dollar dented as coronavirus damage spurs interest rate cut bets",
        "Eurozone final Services PMI crashes to 26.4, Italy at 17.4, EUR/USD pressured under 1.08",
        "How should the currency composition of intercompany debt receivable and payable balances be reported on the BE",
        "'What happens if we're kicked out?' Seven Swiss scientists contemplate a possible future outside EU R&D programmes",
        "'Exclusive: EU fumes at Turk migration 'blackmail', mulls more money for Ankara'",
        "Financial Integration and Structure in the Euro Area, March 2020",
        "Network of impunity: Corruption and European foreign policy",
        "'Eurozone Braces for a Rocky Year'",
        "US prosecutors accuse Honduran president of taking drug money"
    ],
    "Sentiment Score": [
        -100.000, -95.000, -90.000, -85.000, -80.000,
        -75.000, -70.000, -65.000, -60.000, -55.000
    ],
    "Importance Score": [
        1.000, 0.950, 0.900, 0.850, 0.800,
        0.750, 0.700, 0.650, 0.600, 0.550
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "US Fed injects $1.5tn to markets as Dow and FTSE suffer worst day since 1987",
        "Trump suspends travel between U.S. and Europe for 30 days",
        "European Union leaders slam Trump's sweeping coronavirus travel ban",
        "EUR/USD Prepares for Uptrend after ABC Flat Correction",
        "Market Meltdown Hits Pound Sterling and Dollar but Triggers Further Demand for the Euro",
        "Trump travel ban MAPPED: Which countries are banned from travelling to USA?",
        "Emerging Currencies Face Losses of Up to 30% in Virus Sell-Down",
        "US dollar depreciates amid risk-off sentiment",
        "Wall Street's roller coaster week continues: Live updates",
        "Coordinated central bank action to enhance the provision of global US dollar liquidity"
    ],
    "Sentiment Score": [
        -90.000, -80.000, -70.000, 10.000, 20.000,
        -50.000, -60.000, -30.000, -40.000, 0.000
    ],
    "Importance Score": [
        1.000, 0.900, 0.800, 0.700, 0.600,
        0.500, 0.400, 0.300, 0.200, 0.100
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)
#10

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    "Topic": [
        "Dollar strengthens, set for best week since the financial crisis",
        "Coronavirus: Pound plunges to its lowest level in over 30 years",
        "Dollar crunch eases as central banks step up swaps action",
        "Market meltdown extends - GBP loses further ground vs. EUR and USD",
        "Dollar Swap Lines: Welcome Support but Only Part of the Solution",
        "Patchy Progress in Setting Up Public Beneficial Ownership Registers in the EU",
        "Fed moves to ease strains as dollar demand surges",
        "Coronavirus: Why the pound is taking a pummelling as crisis deepens",
        "EUR/USD Forex Market Trading Strategies For March 19, 2020",
        "Pound Sterling to Remain Under Pressure against Dollar and Euro as Fed Hike Fails to Boost Dour Investor Sentiment"
    ],
    "Sentiment Score": [
        100.000, -100.000, 80.000, -90.000, 70.000,
        -80.000, 60.000, -70.000, 50.000, -60.000
    ],
    "Importance Score": [
        1.000, 0.900, 0.800, 0.700, 0.600,
        0.500, 0.400, 0.300, 0.200, 0.100
    ]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    'Topic': ["US dollar depreciation against sterling and euro",
              "Exchange rate forecasts for pound-dollar and euro-dollar",
              "Surge in demand for Euros and depreciation of Sterling",
              "Strengthening dollar causing stress in global economy",
              "Impact of coronavirus on global economy and currencies",
              "Euro-pound exchange rate movements due to COVID-19",
              "US dollar strength against euro",
              "Euro-dollar exchange rate movements due to COVID-19",
              "Euro gaining against lek",
              "European fintech Revolut launching in US"],
    'Sentiment Score': [-90, 40, 50, -70, -80, 60, 80, 60, 50, 30],
    'Importance Score': [0.380, 0.214, 0.185, 0.154, 0.130, 0.119, 0.102, 0.096, 0.075, 0.062]
}

df = pd.DataFrame(data)

# Print the DataFrame
print(df)
#12

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the DataFrame
data = {
    'Topic': ["Decision on Coronabonds critical for EUR/USD outlook",
              "COVID-19 impact on Europe's economic sentiment",
              "Euro-dollar week ahead: charts tip losses but virus slowdown",
              "US accused of 'modern piracy' for diverting masks from Europe",
              "EU Anti Money Laundering Directive (AMLD)",
              "Pound to euro exchange rate volatility due to COVID-19",
              "USD strength despite massive money printing",
              "Eurozone decision on issuing bonds",
              "Exchange rate forecasts for pound and euro",
              "Coronavirus impact on FX market"],
    'Sentiment Score': [-80, -70, -60, -90, 40, 60, -80, 50, 30, -50],
    'Importance Score': [0.250, 0.200, 0.150, 0.125, 0.100, 0.080, 0.070, 0.060, 0.040, 0.035]
}

df = pd.DataFrame(data)

# Print the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    'Topic': ['Eurobonds proposal amid Eurozone crisis',
              'EU budget comparison with Marshall Plan',
              'Action against investment fraud in multiple countries',
              'Dutch resistance to EU coronavirus debt',
              'Impact of COVID-19 on Europe\'s biotech industry',
              'G3 FX Update: COVID-19 impact and short-term expectations',
              'COVID-19 effects on global aid efforts',
              'Strategic rivalry between US and China',
              'Impact of US, EU, Russia, and China aid on COVID-19',
              'US economy hit by COVID-19, USD remains strong'],
    'Sentiment Score': [-90, -70, -80, -60, 30, -50, -60, 20, -60, -80],
    'Importance Score': [0.800, 0.700, 0.600, 0.550, 0.500, 0.450, 0.400, 0.350, 0.300, 0.250]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    'Topic': ['Eurozone country defaults and its impact on EUR',
              'EU responses to the COVID-19 crisis',
              'Global economic impact of COVID-19',
              'US dollar strength amid COVID-19',
              'Brexit implications on EUR usage in UK',
              'Bilateral currency swap lines and their impact',
              'Authoritarian capitalism\'s rise and impact on EUR',
              'Central bank monetary policy consequences',
              'EU banking system stability and EUR monopoly',
              'IMF loans and their effects on EUR countries'],
    'Sentiment Score': [-90, -50, -70, 50, -20, 30, -80, -30, -70, -40],
    'Importance Score': [0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550, 0.500, 0.450]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    'Topic': ['Dollar demand surge during pandemic',
              'Eurozone recession amid prisoner\'s dilemma',
              'Central bank investment response to negative rates',
              'Need for financial aid in Europe due to pandemic',
              'Euro\'s performance amid COVID-19 treatments',
              'Debt relief for Global South during pandemic',
              'Geopolitical impact of Central Bank Digital Currencies',
              'Employment policies in Europe during crisis',
              'Economic responsibility amidst crisis',
              'Consumer behavior trends during lockdown'],
    'Sentiment Score': [70, -60, -20, -80, 40, -90, 30, -50, -10, 20],
    'Importance Score': [0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550, 0.500, 0.450]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

#16

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    'Topic': ['Growth of US dollar credit to non-bank borrowers',
              'Impact of USD hedging costs on European investors',
              'Euro sentiment turning positive',
              'Financial technology gap between US and Europe',
              'USD as safe asset during COVID-19',
              'Economic benefits of coal exit',
              'Impact of Euro area GDP data on US firms',
              'Stock market recovery amid economic collapse',
              'Widening gap between emerging and developed markets',
              'Printing money to revive economies'],
    'Sentiment Score': [70, 40, 60, -30, 80, -50, -20, 10, -40, 90],
    'Importance Score': [0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550, 0.500, 0.450]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    'Topic': ['European vs. US economic resilience during the crisis',
              'Global sustainable investing trends',
              'Regulatory perspective on stablecoins',
              'Pandemic\'s impact on US and European safety nets',
              'Eurozone private sector decline',
              'US dollar dominance during COVID-19',
              'Eurozone\'s vulnerability to pandemic shock',
              'COVID-19 bailouts comparison',
              'EU anti-money laundering measures',
              'Partnership and cooperation amid crisis'],
    'Sentiment Score': [50, 40, -30, -60, -70, 80, -75, -20, -10, 60],
    'Importance Score': [0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550, 0.500, 0.450]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    'Topic': ['Impact of Bitcoin\'s all-time high on USD to EUR exchange rate',
              'Effects of travel restrictions on exchange rate',
              'Kim Jong-un\'s actions and their influence on exchange rate',
              'Collaboration and urgency in financial sector',
              'Need for stronger anti-money laundering measures',
              'Trading Taiwan Dollars and its impact on exchange rate',
              'Predictions for Pound to Dollar exchange rate',
              'Economic impact of pandemic on retail stores',
              'Performance of USD as a safe haven currency',
              'Pound\'s stability amid economic concerns'],
    'Sentiment Score': [80, -70, -60, 50, -30, 40, 30, -20, 90, 10],
    'Importance Score': [0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550, 0.500, 0.450]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    'Topic': ['Germany’s Courts and the Euro',
              'Currency Exchange Rates Update',
              'EU\'s Money Laundering Blacklist and Caribbean Nations',
              'U.S. Dollar Performance and Tensions with China',
              'Norway\'s Krone Performance amid Oil Market Changes',
              'Forex Market Trends for May',
              'Impact of Trump\'s Statements on USD Demand',
              'Euro Strengthens as Dollar Weakens',
              'Investment Recommendations for International Funds',
              'Efforts to Combat Money Laundering and EU\'s Recognition'],
    'Sentiment Score': [-80, -20, -40, -60, -10, 30, -70, 50, 10, 20],
    'Importance Score': [0.920, 0.880, 0.840, 0.800, 0.760, 0.720, 0.680, 0.640, 0.600, 0.560]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    'Topic': ['ECB\'s Response to COVID-19 Crisis',
              'EU\'s €750bn Recovery Fund Proposal',
              'Stress in Money Market Funds',
              'European Commission\'s Anti-Money Laundering Action Plan',
              'Euro US Dollar Exchange Rate and Economic Recovery Hopes',
              'Black Market Currency Trade in Lebanon',
              'Government Handouts Impact on Europe\'s Single Market',
              'Impact of Gold on Long-term Purchasing Power',
              'US Dollar Performance and GDP Revision',
              'China\'s Digital Currency Challenge to the US Dollar'],
    'Sentiment Score': [30, 50, -30, 20, 40, -70, -50, 10, -60, -40],
    'Importance Score': [0.950, 0.910, 0.870, 0.830, 0.790, 0.750, 0.710, 0.670, 0.630, 0.590]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)
#21

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": [
        "ECB Increases Stimulus",
        "Euro's Jump Against USD",
        "EU Member States Pushing for EU Vapor Tax",
        "Euro-to-Dollar Exchange Rate Outlook",
        "Eurozone's Economic Recovery and EUR/USD Rates",
        "Euro's 12-Week High",
        "US Dollar's Impact on Risk Sentiment",
        "US Dollar's Decline Boosts Euro",
        "Dollar's Loss of Safe-Haven Shine",
        "Impact of Evercore's Offer on Dollar's Charm"
    ],
    "Sentiment Score": [
        80, -70, 20, -60, -50, -40, 40, -30, 50, 60
    ],
    "Importance Score": [
        1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Print DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": [
        "Eurozone's Economic Recovery and EUR/USD Rates",
        "Euro's 12-Week High",
        "Will the dollar remain an instrument of US international dominance?",
        "US sanctions add to Syrian economic crisis",
        "Euro-to-Dollar Rate: More Forecasts Upgraded but Rally Seen Slowing",
        "Weakening US dollar still unrivaled as world's reserve currency",
        "International use of the euro broadly stable in 2019",
        "U.S. Dollar Index Vs. Chinese Yuan",
        "EUR/USD Chart Signals a Possible Pullback",
        "Share prices go up at US and European stock markets"
    ],
    "Sentiment Score": [
        -80, -80, -60, -50, -40, 70, 60, -30, 50, 40
    ],
    "Importance Score": [
        1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Print DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": [
        "European Central Bank hands out 1.3 trillion euros in loans",
        "Consequences of US Financial Warfare in the Middle East",
        "Trump troop cut shows need for EU defense push, says Thierry Breton",
        "Eurozone's Economic Recovery and EUR/USD Rates",
        "Pound to Euro currency exchange rate: Latest update during Brexit talks",
        "Short-Term US Dollar Trends Dominated By Risk Conditions, EU Stance Crucial For Euro-Dollar",
        "What Countries Use US Dollars? Areas Where Greenbacks Are King - KFX",
        "How Coronavirus has Affected the Forex Market",
        "The Recent Drop In The Dollar Is Only The Beginning, Says Goldman",
        "Full Line of LEGO Super Mario Sets Revealed"
    ],
    "Sentiment Score": [
        -80, -60, -40, -30, -20, 70, 60, 50, 40, 30
    ],
    "Importance Score": [
        1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Print DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": [
        "EU pushing ahead with digital tax despite US resistance, Vestager says",
        "Reverse yankee supply outlook to reach up to €80bn",
        "United States, Europe battle resurgence of Covid-19 cases",
        "Germany is doomed to lead Europe",
        "Asylum Outsourced: McKinsey's Secret Role in Europe's Refugee Crisis",
        "Why U.S. and EU Officials Are Worried Putin Might Make Another Move in Ukraine",
        "This chart shows just how badly the U.S. coronavirus response has damaged America’s reputation in Europe",
        "The 5 Most Traded Currency Pairs in 2022",
        "Euro Strengthened Too Much",
        "Exposing the truth to save taxpayers' money - Blog"
    ],
    "Sentiment Score": [
        -90, -80, -70, -60, -50, -40, -30, -20, 80, 70
    ],
    "Importance Score": [
        1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Print DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix
data = {
    "Topic": [
        "U.S. can 'change the world' by devaluing the dollar, analyst claims",
        "Time To Short The U.S. Dollar",
        "Virus Halts Suitcases of Cash in Europe Laundering Hotspot Latvia",
        "BIS Innovation Hub to expand to new locations in Europe and North America",
        "COVID-19 and global capital flows",
        "Taking Stock | American Magazine",
        "European Workers Draw Paychecks. American Workers Scrounge for Food. (Published 2020)",
        "Dinner at Jefferson's (or how the USA created the federal public debt)",
        "Undermining Sanctions: How mining magnate Dan Gertler appears to have dodged US penalties",
        "'Hamilton' Review: The Revolution, Now Televised - WSJ"
    ],
    "Sentiment Score": [
        -100, -90, -80, -70, -60, -50, -40, -30, -20, 80
    ],
    "Importance Score": [
        1.000, 0.950, 0.900, 0.850, 0.800, 0.750, 0.700, 0.650, 0.600, 0.550
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Print DataFrame
print(df)
#26

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the data
data = {
    "Topic": [
        "Croatia, Bulgaria Cleared to Join Waiting Room to Adopt Euro",
        "Euro News (EUR USD): Bulgaria, Croatia Closer to Using Currency",
        "China's support for US dollar can no longer be relied upon",
        "Will the e-money boom make the UK a hub of money laundering?",
        "How banks’ dollar holdings drive exchange rate dynamics",
        "Currency exchange: US dollar, Euro up against the Soum",
        "How Do Gas Taxes Compare in Europe?",
        "Euro-Zone Queue Shows Crisis-Plagued Currency Still Has Appeal",
        "Most MENA currencies to weaken in 2020",
        "USD TO EUR: 1 USD TO EURO Rate, 7 July 2020"
    ],
    "Sentiment Score": [
        90, 80, -70, -60, -50, -40, -30, -20, -10, 100
    ],
    "Importance Score": [
        1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Define the data
data = {
    "Topic": [
        "EU's Trade Impact with China: Weighing Economic and Political Consequences",
        "Surge in Cash Demand Amid Coronavirus Panic",
        "Sterling Strengthens Above $1.26 as US Dollar Weakens",
        "Euro Rises to Four-Month High vs Dollar on Stimulus Hopes",
        "EU Court Overturns Apple's €13bn Irish Tax Bill",
        "US Dollar's Global Dominance and its Implications",
        "Euro Rates Gain After Italy Maintains Credit Rating",
        "US Dollar Gains Ground as Safe-Haven Asset Amid Market Uncertainty",
        "Pound's Volatility Against Euro and Dollar in Global Risk Conditions",
        "EU's Preparation for a Global Gold Standard Since the 1970s"
    ],
    "Sentiment Score": [
        85, -80, 90, 85, -75, 80, 85, 90, 95, 80
    ],
    "Importance Score": [
        1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Euro Skeptics Are Now Believers and It's Driving Markets Higher",
        "Euro highest since 2018, dollar hurt by coronavirus spread",
        "Croatia and Bulgaria join ERM II",
        "Dominant Currencies and the Limits of Exchange Rate Flexibility",
        "Europe Could Soon Have Fiscal Firepower of the U.S.",
        "Euro Currency ETF Pops After Historic Stimulus Deal",
        "EU leaders strike 'historic' $2 trillion deal",
        "U.S. Relations With Italy",
        "Italian Police Bust Largest Ever Euro Forging Network",
        "Dark clouds on the horizon for European Venture Capital"
    ],
    "Sentiment Score": [
        80, -90, 70, -60, 75, 85, 95, 50, -70, -50
    ],
    "Importance Score": [
        0.932, 0.865, 0.798, 0.731, 0.664, 0.597, 0.530, 0.463, 0.396, 0.329
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Dollar blues: pandemic testing confidence in US currency",
        "BIS global liquidity indicators at end-March 2020",
        "Antitrust: Commission fines five banks €1.07 billion",
        "The Euro's Ascent Won't Knock the Dollar Off Its Perch",
        "Dollar move signals new era of weakness, as gold gains",
        "US dollar suffers worst month in a decade",
        "US dollar losing clout as world's reserve currency",
        "America coming apart, Europe coming together",
        "What should the EU be?",
        "European Markets Offering Alternative to S&P 500"
    ],
    "Sentiment Score": [
        -80, 60, -70, 75, -90, -85, -95, 70, 55, 80
    ],
    "Importance Score": [
        0.915, 0.831, 0.746, 0.662, 0.577, 0.493, 0.408, 0.323, 0.239, 0.154
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Emerging market currencies rebound against USD",
        "Serbia investigates money laundering allegations",
        "Euro-to-Dollar rate tumbles amid geopolitical tensions",
        "Views on the weakening US dollar",
        "Federal Reserve's role during the pandemic",
        "Influence of dark money on British politics",
        "Impact of negative interest rates",
        "Nominee's comments on German immigration policy",
        "Influence of Tory MPs on British politics",
        "Concerns about national security amid global challenges"
    ],
    "Sentiment Score": [
        60, -70, -85, 75, 50, -90, -60, -80, -95, -75
    ],
    "Importance Score": [
        0.943, 0.854, 0.765, 0.676, 0.588, 0.499, 0.411, 0.322, 0.234, 0.146
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)
#31

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Impact of weakening dollar on international economy",
        "Influence of EUR/USD rally on Pound-Euro dynamics",
        "Concerns over Turkish Lira's impact on Euro",
        "Performance of top stocks during weak dollar",
        "Exchange rate forecast comparison for EUR/USD",
        "EUR/USD rate movement amid ECB and market pressures",
        "Gold's performance against various currencies",
        "Appreciation of Moldovan lei against Euro",
        "Impact of weakening dollar on UAE Dirham peg",
        "Unique currency issues: Raam and its value"
    ],
    "Sentiment Score": [
        -85, 70, -75, 60, 50, -80, 65, 55, -90, -95
    ],
    "Importance Score": [
        0.934, 0.853, 0.772, 0.691, 0.610, 0.529, 0.448, 0.367, 0.286, 0.204
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Concerns over US dollar slide",
        "Euro's strength and its impact on currency dynamics",
        "Euro liquidity provision by ECB",
        "Impact of central bank digital currency on USD/EUR",
        "Dollar depreciation trend",
        "European countries outside Eurozone",
        "Bitcoin's role in currency dynamics",
        "Influence of unconventional monetary policy",
        "Impact of dollar strength on Bitcoin and gold",
        "Connection between oil prices and currencies"
    ],
    "Sentiment Score": [
        -85, 80, 65, 70, -75, 60, 50, -80, -90, 55
    ],
    "Importance Score": [
        0.920, 0.841, 0.762, 0.683, 0.604, 0.525, 0.446, 0.367, 0.288, 0.209
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "US economic sanctions against Europe",
        "Weakened dollar: causes and consequences",
        "Euro's resilience against USD",
        "Euro-Dollar exchange rate dynamics",
        "Tech stocks dominance in the US market",
        "Russian investments in Cyprus",
        "Legal issues for games businesses in Europe",
        "Market sentiment ahead of Republican convention",
        "Croatia's stance on adopting the euro",
        "Leak of confidential files revealing Cyprus's activities"
    ],
    "Sentiment Score": [
        -80, -85, 75, 80, 70, 60, 50, 65, 55, -75
    ],
    "Importance Score": [
        0.919, 0.871, 0.823, 0.775, 0.727, 0.679, 0.631, 0.583, 0.535, 0.487
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Impact of ECB intervention on USD to EUR",
        "COVID-19's effect on USD's bull run",
        "Dovish BoE's impact on GBP to USD and EUR",
        "EUR/USD rate reaching two-year highs",
        "Chinese yuan as a reserve currency",
        "ECB's potential stimulus effect on EUR/USD",
        "Belarusian rouble's depreciation against USD and EUR",
        "Historical GBP-EUR exchange rate analysis",
        "Gold price influence on EUR and USD",
        "US tech giants' response to European taxes"
    ],
    "Sentiment Score": [
        -75, -80, -70, 80, 75, 70, -65, 60, 55, 50
    ],
    "Importance Score": [
        0.923, 0.887, 0.851, 0.815, 0.779, 0.743, 0.707, 0.671, 0.635, 0.599
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Chinese yuan's rise as global currency",
        "Euro's strength against USD",
        "ECB's meeting and its impact on EUR",
        "US Dollar's performance against EUR",
        "Digital Euro's potential impact",
        "Sterling's decline against EUR",
        "ECB's dilemma with the surging Euro",
        "Gold price movement and its effect on EUR",
        "Forex rates and currency exchange in Europe",
        "Croatia's path towards adopting the Euro"
    ],
    "Sentiment Score": [
        80, 70, 65, -75, 60, -85, -70, 55, 50, 45
    ],
    "Importance Score": [
        1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)
#36

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "EU introducing crypto-assets regime by 2024",
        "US Dollar's potential crash",
        "Euro's strength against USD",
        "EU's stance on LGBT rights",
        "US banks defying money laundering crackdowns",
        "Klarna becoming Europe's most valuable fintech",
        "ECB and Federal Reserve printing money extensively",
        "Euro's impact on the Naira",
        "ECB's challenges with Euro appreciation",
        "Sterling's exchange rate with Euro"
    ],
    "Sentiment Score": [
        80, -85, -75, 65, -90, 60, -95, -70, -80, -75
    ],
    "Importance Score": [
        1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "US Dollar Strength Concerns due to Dovish Fed and Economic Backdrop",
        "EUR/USD Currency Pair's Steep Fall",
        "Impact of USD Direction on Gold Prices",
        "Potential Reversal in EUR/USD Softening Trend",
        "Chinese Yuan's Strengthening Outlook",
        "EU Cloud Regulation's Impact on USD and Tech Giants",
        "Impact of Dollar's Losing Streak on S&P 500",
        "Gold's Price Plunge and Dollar's Influence",
        "ClearBank's Multi-Currency Accounts Offering",
        "Impact of COVID-19 and Brexit on GBP and USD Short Squeeze"
    ],
    "Sentiment Score": [
        -90, -85, -80, 70, 60, -55, -50, -45, 40, -35
    ],
    "Importance Score": [
        1.000, 0.923, 0.846, 0.769, 0.692, 0.615, 0.538, 0.462, 0.385, 0.308
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "European Central Bank's Digital Euro Initiatives",
        "Euro to US Dollar Exchange Rate Trends",
        "US Dollar's Safe-Haven Status",
        "Brexit Impact on Currency Markets",
        "US-China Trade Relations",
        "European Union's Migration and Asylum Policy",
        "Modern Monetary Theory and Fiscal Policy",
        "European Tech Industry Growth",
        "COVID-19 Stimulus Measures and Currency Impact",
        "Market Sentiment Surrounding US Elections"
    ],
    "Sentiment Score": [
        60, -50, 70, -60, -40, -50, 50, 80, -30, -40
    ],
    "Importance Score": [
        0.950, 0.910, 0.870, 0.830, 0.790, 0.750, 0.710, 0.670, 0.630, 0.590
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "US, EU, and Council of Europe Collaboration",
        "Currency Manipulation and Trade Patterns",
        "Interest Rate Differentials",
        "Brexit and Currency Markets",
        "European Start-up Ecosystem Growth",
        "Dominance of the US Dollar",
        "Forex Market Forecasting Accuracy",
        "Political Events and Currency Markets",
        "US Presidential Election Effects on USD",
        "Bitcoin's Role in Global Currency Dynamics"
    ],
    "Sentiment Score": [
        80, -70, 50, -60, 70, 90, 60, -50, -40, 70
    ],
    "Importance Score": [
        0.950, 0.910, 0.870, 0.830, 0.790, 0.750, 0.710, 0.670, 0.630, 0.590
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)
#40

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Introduction of a Digital Euro",
        "Iran's Currency Depreciation Against USD",
        "Attractiveness of European Fixed Income Markets",
        "Central Banks' Exploration of Digital Currencies",
        "Law Enforcement Actions Against Cybercriminals",
        "Impact of Brexit Negotiations on Pound Sterling",
        "European Space Agency's Exploration Contracts",
        "Impact of US Presidential Election on Europe",
        "Efforts to Counter Currency Wars",
        "Importance of Trust in Leadership"
    ],
    "Sentiment Score": [
        80, -70, 60, 50, -90, -60, 70, -40, 30, 85
    ],
    "Importance Score": [
        0.950, 0.910, 0.870, 0.830, 0.790, 0.750, 0.710, 0.670, 0.630, 0.590
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Euro's Limited Reserve Currency Status",
        "Sales of Farmed Seafood in Hawaii in USD",
        "Challenges of Implementing a Single Global Currency",
        "Historical Importance of British Pound",
        "Impact of Climate Change Acknowledgment by ExxonMobil",
        "Influence of US Stimulus Package Expectations",
        "Performance Comparison of US Shares and ASX 200 Index",
        "Market Speculation on Bitcoin Price Rally",
        "Concerns Over Yuan's Appreciation Against USD",
        "Euro's Response to Covid Crisis and US Dollar Weakness"
    ],
    "Sentiment Score": [
        -80, 50, -70, 75, 85, 40, -60, 30, -90, 60
    ],
    "Importance Score": [
        0.912, 0.876, 0.841, 0.805, 0.769, 0.734, 0.700, 0.667, 0.635, 0.604
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "U.S. Election Impact on Exchange Rate",
        "Hackers Steal Funds from Trump Campaign",
        "COVID-19's Influence on Exchange Rates",
        "US Dollar Strength Amid Global Events",
        "Weaker Dollar's Political Ramifications",
        "US Christian Right's Influence in Europe",
        "US Stimulus Package Negotiations Impact",
        "ECB Policy Effects",
        "Brexit Impact on EUR/GBP Exchange Rate",
        "Central Bank Monetary Policy Decisions"
    ],
    "Sentiment Score": [
        -70, -85, -50, 50, -60, -90, 40, -30, -20, 10
    ],
    "Importance Score": [
        0.361, 0.208, 0.194, 0.167, 0.139, 0.111, 0.097, 0.083, 0.069, 0.056
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Impact of US Presidential Election on USD/EUR",
        "Turkish Lira's Slide Against Euro",
        "Goldman Sachs Drops Euro from Outperforming List",
        "COVID-19's Influence on Currency Markets",
        "Russian Rouble's Decline Amidst Uncertainty",
        "Debt Accumulation Amid COVID-19 Pandemic",
        "Focus on US Election's Impact on Currency Trading",
        "Geopolitical Risks Impacting Currency Markets",
        "Impact of US-China Relations on Currency Markets",
        "Rising Defense Spending Among NATO Allies"
    ],
    "Sentiment Score": [
        -80, -90, -70, -60, -70, -50, 40, -30, -20, 30
    ],
    "Importance Score": [
        0.350, 0.250, 0.200, 0.150, 0.125, 0.100, 0.075, 0.050, 0.035, 0.025
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "US Treasury Investigating Vietnam's Currency Manipulation",
        "Samsung, LG, Hyundai on Alert Over Stronger Currency",
        "ECB's Lagarde Foresees Digital Euro by 2025",
        "US Dollar Falls to Eight-Month Low",
        "Impact of Three Seas Initiative on Estonia",
        "US and European Antitrust Probes on Amazon",
        "HSBC Launches Global Money Account in US",
        "Impact of Biden Administration on Dollar",
        "Commodity Currencies Amid COVID-19",
        "Gold Price Trades and Silver Rose Amid Market Conditions"
    ],
    "Sentiment Score": [
        -70, -50, 60, -80, 40, -30, 20, -90, 10, 30
    ],
    "Importance Score": [
        0.320, 0.270, 0.230, 0.180, 0.140, 0.120, 0.100, 0.080, 0.060, 0.040
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)
#45

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Dollar Loses to Euro as Payment Currency for First Time in Years",
        "Euro-Dollar Week Ahead Forecast: 'Sell EUR/USD in to Year-end' - Nordea",
        "US Election: Economists Have High Hopes for the New President Biden",
        "EUR/USD: Euro Rallies On Vaccine Optimism",
        "Vaccine arrival expected to trigger 20% slump in U.S. dollar next year",
        "The Swiss Franc Is Still A Safe-Haven Currency",
        "EUR/USD Price Forecast – Euro Reaching Towards Major Big Figure",
        "Exchange Rates Today 20.11.2020: Pound Advances On Vulnerable Dollar, Euro Rallies On Record German Economic",
        "Live open market Foreign Currency Exchange Rates in Pakistan today - 2020-November-17",
        "Dollar Index Resembles This Moment in Time for TVC:DXY by TradeStation"
    ],
    "Sentiment Score": [
        -90, -70, 80, 70, -80, 40, 60, 50, 10, -20
    ],
    "Importance Score": [
        1.000, 0.890, 0.780, 0.670, 0.560, 0.450, 0.340, 0.230, 0.120, 0.010
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Dollar falls to lowest level in almost 3 months",
        "U.S dollar set for weekly losses, currency traders buy Euro, British Pound",
        "US President-elect Biden speaks with EU leaders",
        "Threats over the external debt of Developing Countries",
        "EUR/USD Mid-Session Technical Analysis for November 27, 2020",
        "Euro area money markets from the global financial crisis to the COVID-19 pandemic",
        "Turkish lira against US dollar: Flashback 2006, outlook 2023",
        "US dollar squeeze and $19K BTC: 5 Things to watch in Bitcoin this week",
        "Currency exchange service now available via CRDB Bank ATM",
        "More UK banks to shut British expat accounts – what to do if yours is closed"
    ],
    "Sentiment Score": [
        -80, 60, 70, -70, 50, 40, -60, -30, 20, -20
    ],
    "Importance Score": [
        1.000, 0.890, 0.780, 0.670, 0.560, 0.450, 0.340, 0.230, 0.120, 0.010
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "U.S. dollar hovers around two-and-a-half year low",
        "Euro heading for the heavens as dollar enters purgatory",
        "Dollar's weakness pushes won to 30-month high",
        "Euro bursts through resistance, dollar holds near 2-1/2 year low",
        "Dollar on track for worst week in a month",
        "Reports a Brexit Deal Could be Agreed Before the Weekend",
        "A weakening US dollar is good news for markets",
        "Euro-Dollar at Two Year Highs but Buyer Conviction Ebbs",
        "U.S dollar drops, nears two and a half years low",
        "Dollar hovers near 2.5 years low as traders eye U.S. stimulus talks"
    ],
    "Sentiment Score": [
        -90, 80, 70, 60, -80, -70, 50, 40, -60, -30
    ],
    "Importance Score": [
        1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the matrix data
data = {
    "Topic": [
        "Dollar weakens on vaccine, U.S. stimulus optimism",
        "Euro gains as ECB holds back 'bazooka,' Sterling falls on Brexit fears",
        "Dollar falls; sterling jumps as Brexit deal hopes lift risk appetite",
        "The broad dollar exchange rate as an EME risk factor",
        "Combination of AstraZeneca, Russian Vaccines to Undergo Trial",
        "Dollar's weakness pushes won to 30-month high",
        "ECB Expands PEPP Stimulus to Help Economy, EUR up",
        "CEO pay landscape in Japan, the U.S. and Europe — 2020 analysis",
        "Sizable Correction in Stock Market Is Not Imminent, Goldman Sachs Says",
        "Facebook Pledges $150 Million to Build Homes for Silicon Valley's Poorest"
    ],
    "Sentiment Score": [
        -80, 70, -60, -90, 50, 40, 30, 20, -30, 10
    ],
    "Importance Score": [
        1.000, 0.900, 0.800, 0.700, 0.600, 0.500, 0.400, 0.300, 0.200, 0.100
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "U.S. dollar loses crown as the world's most used currency",
        "Euro rises above $1.22 for first time in more than two years",
        "U.S. dollar rises on new virus strain",
        "U.S. accuses Switzerland and Vietnam of currency manipulation",
        "Euro tops $1.22 for the first time since 2018",
        "US labels Switzerland a currency manipulator",
        "US accuses Switzerland of currency manipulation",
        "US dollar's dominance in decline",
        "Euro 1Q 2021 Forecast: ECB aims to curb Euro’s strength",
        "Swiss government ready to negotiate currency manipulator label"
    ],
    "Sentiment Score": [
        -90.456,
        85.772,
        -75.125,
        -68.379,
        82.591,
        -63.004,
        -57.298,
        -55.920,
        65.712,
        61.012
    ],
    "Importance Score": [
        1.000,
        0.948,
        0.898,
        0.849,
        0.800,
        0.751,
        0.702,
        0.653,
        0.604,
        0.555
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)
#50

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "New coronavirus strain hits pound as investors flee to dollar",
        "Currency traders flock to U.S dollars amid COVID-19 drama",
        "Spread of virus mutation keeps euro and pound under pressure",
        "U.S. dollar in freefall against Israeli shekel",
        "U.S. Falls Further Behind Europe in Fast-Growing ESG Market",
        "Questions & Answers: EU-UK Trade and Cooperation Agreement",
        "Margaret Thatcher: Ex-PM described euro as a 'rush of blood'",
        "EUR/USD Still On A Sell Signal",
        "EUR/USD Keeps the Asian Gains, But Market Mood Cautious",
        "Margaret Thatcher said no to Euro as `one currency`"
    ],
    "Sentiment Score": [
        -85.729,
        -79.674,
        -73.619,
        -67.563,
        89.785,
        82.728,
        76.673,
        -61.507,
        73.619,
        67.563
    ],
    "Importance Score": [
        1.000,
        0.952,
        0.905,
        0.857,
        0.810,
        0.762,
        0.714,
        0.667,
        0.619,
        0.571
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

import pandas as pd

# Create the dataframe
data = {
    "Topic": [
        "Thatcher was completely right about the Euro",
        "China's tweaks to CFETS index basket could drive yuan higher",
        "EUR/USD Forecast: Possible Further Euro-Dollar Headway In 2021",
        "Brexit: how the new rules will change your visits to the EU",
        "US Dollar as “Global Reserve Currency” amid Fed’s QE and US Government Deficits",
        "The UK and EU begin a new relationship on 1 January 2021",
        "Pound Sterling Rises after Brexit Deal Signed and Astrazeneca Vaccine Approved",
        "Stronger dollar threatens record-setting stock market",
        "What will Cuba’s new single currency mean for the island?",
        "AES Gener launches USD-300m capital hike"
    ],
    "Sentiment Score": [
        -87.500,
        84.375,
        81.250,
        -78.125,
        -75.000,
        -71.875,
        68.750,
        -65.625,
        -62.500,
        59.375
    ],
    "Importance Score": [
        1.000,
        0.925,
        0.850,
        0.775,
        0.700,
        0.625,
        0.550,
        0.475,
        0.400,
        0.325
    ]
}

df = pd.DataFrame(data)

# Display the dataframe
print(df)

upper,lower=weekly_score(df)
bound.append([upper,lower])
raw_data.append(df)
print(bound)

print(len(bound))
bound=pd.DataFrame(bound)
bound.to_csv('eurusdscore2020.csv')

topics=pd.DataFrame([])
for i in range(53):
  topics=pd.concat([topics,raw_data[i].iloc[:,0]],ignore_index=True)

topics.to_csv('eurusdtopics2020.csv')